### ISSUE TITLE
`Nx.from_numpy` for cases where tensor does not come from file

### ISSUE THREAD

**Issue by laursisask** [elixir-nx/nx#1001]
`Nx.from_numpy` only works when reading NumPy arrays from a file.

NumPy arrays may come from other sources besides files. For example, model weights are often stored in S3, and in a typical scenario, they are downloaded directly to memory from S3. In that case, to use the `from_numpy` function it is required first to write the weights to a file, pass that path to `Nx.from_numpy` and once the array has been loaded, delete the file. That is inconvenient and unnecessarily uses disk.

It would be good to have a function for reading NumPy arrays that accepted binaries instead of filepaths.

I think one way would be to remove the file reading logic from the current implementation, i.e.

replace

```elixir
def from_numpy(file) do
  file
  |> File.read!()
  |> parse_numpy()
end
```

with

```elixir
def from_numpy(file) do
  parse_numpy(file)
end
```

That change would be backward incompatible though so not an ideal solution.

The same issue applies to the `from_numpy_archive` function.

**Comment by josevalim** [comment]
Honestly, we should not read worry about reading files because it is literally a `|> File.read!` operation away. My suggestion is to make both work directly on binaries. This can go with the breaking changes from #1002. :)

**Comment by josevalim** [comment]
Closing in favor of #1004.
