### ISSUE TITLE
`Nx.from_numpy_archive` does not retain names

### ISSUE THREAD

**Issue by laursisask** [elixir-nx/nx#1002]
When loading NumPy archive from a file, the file names specified upon saving are ignored.

For example, if you do

```python
import numpy as np
foo = np.array([1, 2, 3])
bar = np.array([100])

np.savez("array.npz", foo=foo, bar=bar)
```

And then load the archive in Elixir, you get back an array of tensors:

```
iex(2)> Nx.from_numpy_archive("array.npz")
[
  #Nx.Tensor<
    s64[3]
    [1, 2, 3]
  >,
  #Nx.Tensor<
    s64[1]
    [100]
  >
]
```

It would be better if a map with array names as keys were returned instead. For example:

```elixir
%{
  "bar" => #Nx.Tensor<
    s64[1]
    [100]
  >,
  "foo" => #Nx.Tensor<
    s64[3]
    [1, 2, 3]
  >
}
```

With maps, extracting individual tensors is much less error-prone. Additionally, it does not rely on the arrays being specified in the same order during saving.

I checked that implementing this would be fairly simple, as the array names are just the file names of the zip entries. My main concern currently is that it would be a backwards incompatible change.

**Comment by josevalim** [comment]
I think we should return lists of tuples instead of maps, because we can have both order and names. If you want to access by name, then you could do `Map.new`on it.

A PR is welcome. It is a breaking change but now is the time for them. :)

**Comment by josevalim** [comment]
Closing in favor of #1004.
