### ISSUE TITLE
Add metrics around Nx.Serving

### ISSUE THREAD

**Issue by josevalim** [elixir-nx/nx#1005]
We should emit events and also have an easy way to compute queue size and similar.

**Comment by sorentwo** [comment]
The Serving module has a handful of public functions, of which `run/2` and `batched_run/2` look most suited toward instrumentation. However, the phrase "compute queue size and similar" leads me to believe the focus here is on `batched_run/2`. Is that accurate?

Also, do you expect to have sub-spans for the `handle_preprocessing`, `receive_batched`, and `handle_postprocessing` invocations?

**Comment by josevalim** [comment]
I think all of those are useful:

1. metrics around run
2. metrics around batched_run
3. metrics around preprocessing and postprocessing

However, those are all client side. I would also like to have metrics on the server side. Especially because I would like to track the queue size. But we can start with the client ones and then add server ones. :)

**Comment by sorentwo** [comment]
Ok, no problem. I'm investigating the server side (which is highly informative) and will take a shot at both client and server telemetry.
