### ISSUE TITLE
Add Nx.swap_axes/2

### ISSUE THREAD

**Issue by kipcole9** [elixir-nx/nx#1011]
This is a feature request to add `Nx.swap_axes/2` that is analogous to the same function in [numpy](https://numpy.org/doc/stable/reference/generated/numpy.swapaxes.html#numpy-swapaxes).

Image data is typically represented as a three dimensional matrix (eg PIL, libvips, stbimage) however whereas PIL and stbimage represent the data as HWC, libvips (and I believe most "photo centric" libraries) represent the data as WHC.  This makes interoperability challenging and requires the H and W axes to be swapped in order to fit into the "ml" and linear algebra ecosystem.

Note this is not the same as a `Nx.transform/2` since image data is really more of a 2D matrix with each cell storing R, G and B data (other other colour space data). Therefore `Nx.swap_axes/2` would be used to swap the `H` and `W` axes as one key use case in image processing.

**Comment by polvalente** [comment]
Nx.transpose/2 accepts more than 2 axes as an option. Doesn't that take your use case into account?

**Comment by josevalim** [comment]
Yes, you can do: `Nx.transpose(x, [0, 2, 1]) or similar with transpose. The only benefit of `swap_axes` is that it would work if you have more axes and you wouldn't have to repeat them but it also means using negative positions:

    Nx.swap_axes(x, -1, -2)

Is that your use case @kipcole9?

Note though it can also be done with transpose as:

    Nx.transpose(x, Enum.to_list(0..Nx.rank(x)-2//1) ++ [-2, -1])

**Comment by kipcole9** [comment]
Thanks for your patience @polvalente and @josevalim. I feel like `Nx.transpose/2` should be all I need, but it appears not.  I expect part of the challenge is my lack of basic knowledge.  Here's the scenario:

* [Image](https://hex.pm/package/image) loads images in WHC order.  I can use [Image.to_nx/1](https://github.com/kipcole9/image/blob/main/lib/image.ex#L4254-L4268) to produce an Nx tensor. And then use [Image.from_nx/1](https://github.com/kipcole9/image/blob/main/lib/image.ex#L4270-L4322) to recreate the images.  The round trip works, the image is recreated. So round trip appears to work.
* I then take the tensor from `Image.to_nx/1`, call `Nx.transpose(tensor, axes: [:height, :width, :bands])` and then with `StbImage.from_nx/1` I create an `StbImage` and save it. The image is very definitely not correct.

So I'm missing something fundamental here. I would think that converting an image from WHC to HWC is nothing more than `Nx.transpose(tensor, axes: [:height, :width, :bands])` ("bands" is the name for "channels" in libvips world) and I'm good to go.  But I'm not.

I appreciate this may not be really an Nx issue - more of idiot programmer issue. But any guidance would most definitely be welcome.  I will work on a Livebook to demonstrate this in the next day or so.

**Comment by josevalim** [comment]
@kipcole9 Maybe try loading the same image directly on both libraries and getting their tensors. Then transpose one to the other, are the tensors equal?

Maybe the root cause is not Nx related but rather that they are somehow not agreeing on the binary representation of the image.

**Comment by kipcole9** [comment]
Apologies for the noise. Turns out all I have to do is reshape the tensor.  Basically (and for posterity):
```elixir
with {:ok, tensor} <- Vix.Vips.Image.write_to_tensor(image) do
 %Vix.Tensor{data: binary, shape: {width, height, bands}, type: type} = tensor

 binary
 |> Nx.from_binary(type, options)
 |> Nx.reshape({height, width, bands}, names: [:height, :width, :channels])
 |> wrap(:ok)
end
```
