### ISSUE TITLE
Prune Nx.Defn.Expr inspection

### ISSUE THREAD

**Issue by josevalim** [elixir-nx/nx#1013]
Printing the whole tree may take too much memory/cpu and make the system unresponsive. We should likely obey inspect limit opts.

**Comment by josevalim** [comment]
Size is definitely an issue but I think we have loops or something else happening. It probably makes sense to rewrite inspect more in the style of other algorithms.

**Comment by Benjamin-Philip** [comment]
Hey @josevalim, could you provide a simpler reproducible instance of this issue? Maybe I might be able to get this fixed.

**Comment by josevalim** [comment]
Sorry, I plan to work on this one because it is a rewrite from scratch on the inspect representation (and it is trickier than I expected). :(

**Comment by josevalim** [comment]
We fixed this issue by making pretty printing fast but others may want on pruning if desired. :)

**Comment by polvalente** [comment]
#1272 adds pruning via the Inspect `:limit` option
