### ISSUE TITLE
Plans to add telemetry to Nx.Serving?

### ISSUE THREAD

**Issue by cigrainger** [elixir-nx/nx#1023]
Are there any plans to add telemetry to Nx.Serving? I think much can be achieved by the user, but some things built in (like execution time, actual batch size on `handle_batch`) might be useful.

**Comment by josevalim** [comment]
Yes, we definitely want and a PR is welcome. There is a basic discussion on #1005 too. I will see if I submit a PR today /cc @sorentwo

**Comment by sorentwo** [comment]
@josevalim I can take this. If not today, in the next couple of days.

**Comment by josevalim** [comment]
Closing, still tracked in #1005.
