### ISSUE TITLE
Hexdocs of each module and function in @allowed_modules and @forbidden_ops of Nx.Defn.Compiler should note "This module can be used in defn" and "This function cannot be used in defn`, respectively.

### ISSUE THREAD

**Issue by zacky1972** [elixir-nx/nx#1041]
Hi,

I think it will be convenient if the hexdocs of each module and function in `@allowed_modules` and `@forbidden_ops` of `Nx.Defn.Compiler` should note "This module can be used in `defn`." and "This function cannot be used in `defn`.`, respectively.

**Comment by josevalim** [comment]
Yes, a pull request is welcome!

**Comment by zacky1972** [comment]
Well, I can write such PR by inserting to each ｀@moduledoc` and `@doc`, directly, but I don't think it will a clever approach because it will enforce us to maintain when updating `@allowed_modules` and `@forbidden_ops`. 

Moreover, I can't imagine how to implement more clever approach to apply meta programming to manage without such maintenance...

**Comment by josevalim** [comment]
Inserting individually is fine. We don't plan for the list to grow considerably. :) Simpler is better!

**Comment by zacky1972** [comment]
I see. Wait a minute.
