### ISSUE TITLE
add sparse matrix checking

### ISSUE THREAD

**Issue by matiascr** [elixir-nx/nx#1053]
Add function `sparse?(tensor) :: boolean` to check if multidimensional tensor is sparse matrix

**Comment by josevalim** [comment]
Do you have any suggestions possible implementation of this function? Is there something similar in JAX/Numpy/Torch?

**Comment by seanmor5** [comment]
JAX has implementations of operations on sparse matrices: https://github.com/google/jax/tree/main/jax/experimental/sparse

**Comment by matiascr** [comment]
Scipy has a way to check, too: https://github.com/scipy/scipy/blob/fdc32b8bb95d4c5e101c3d1beb321663cba0b85e/scipy/sparse/_base.py

**Comment by polvalente** [comment]
I'm not sure what would be the gain in having a `sparse?` function.
What would be the definition of sparsity used?
Would we add functionality that takes advantage of this definition?

Furthermore, from a memory-usage expectation point of view, I fear that having the concept of sparsity might induce people to assume that if a tensor returns `sparse?(tensor) === true`, it would be stored more efficiently in memory, and that isn't currently the case. This would also depend on the backend.

**Comment by Benjamin-Philip** [comment]
> Furthermore, from a memory-usage expectation point of view, I fear that having the concept of sparsity might induce people to assume that if a tensor returns sparse?(tensor) === true, it would be stored more efficiently in memory, and that isn't currently the case. This would also depend on the backend.

We could just make it clear either in the `moduledoc` or the `doc` that there is no variation in the way we store tensors, sparse or not.

**Comment by josevalim** [comment]
Closing this for ow. We would be interested in a proposal that considers sparse matrices, considerations, feedbacks, and pitfalls. But it is not on our priority list at the moment, so it will depend on external contribution.
