### ISSUE TITLE
EXLA compiled libraries absolute symbolic links

### ISSUE THREAD

**Issue by thiagopromano** [elixir-nx/nx#1061]
Currently, during compilation, EXLA creates symbolic links to the compiled libraries in these lines:

https://github.com/elixir-nx/nx/blob/main/exla/Makefile#L41-L49

The problem is that they are absolute path symlinks, for example:
```
./_build/test/lib/exla/priv:
lib -> /app/deps/exla/cache/xla_extension/lib
libexla.so -> /app/deps/exla/cache/libexla.so
```

This behavior is different from all other symbolic links created by dependencies, where relative paths are used, such as Phoenix:

```
./_build/test/lib/phoenix:
priv -> ../../../../deps/phoenix/priv
```

When the project folder is moved, the absolute symbolic links lose track of the libraries, breaking the build. 

In our case, our build was breaking because we move all the files between the compilation and the tests execution. It took a while to find these special absolute symbolic links. 

I propose making these symlinks relative the same way as the other symlinks so they are consistent on the "non-release" enviroments.

For the releases, they are already copied since https://github.com/elixir-lang/elixir/pull/12011. Making them relative shouldn't affect them.

**Comment by josevalim** [comment]
Please do submit a PR :)

**Comment by josevalim** [comment]
Closing in favor of the PR!
