### ISSUE TITLE
Add compute_uv? to SVD as an option

### ISSUE THREAD

**Issue by msluszniak** [elixir-nx/nx#1080]
Do we want to add an option `:compute_uv?` which will default to `true` and if set to `false` svd will only return the singular values? If so, I could implement this one.

**Comment by josevalim** [comment]
I assume we may not need this because Nx compilation is smart and if you don't use uv, then we won't compute them. :)

**Comment by polvalente** [comment]
The problem with this one would be polymorphic return. 

We could get around that by setting u and v to nan or zero when compute_uv = false, though. Maybe even a template tensor but I'm not sure if that would work. 

There's also concern about the grad for the SVD in this case.

@josevalim WDYT?

**Comment by msluszniak** [comment]
I think that using the current implementation we would still compute this u and v. In JAX, this feature is in TODO.

**Comment by msluszniak** [comment]
How do we avoid of computing u and v when the core SVD function looks like this?

```elixir
  defnp svd_tall_and_square(a, opts \\ []) do
    {_m, n} = Nx.shape(a)
    {u, h} = qdwh(a, opts)
    # ensure H is hermitian
    h = (h + Nx.LinAlg.adjoint(h)) / 2
    {s, v} = Nx.LinAlg.eigh(h, max_iter: opts[:max_iter])
    ...
  end
```

**Comment by josevalim** [comment]
Hrm, you are right. Then it probably deserves to be its own function, so we keep the tuple return. So :+1: for its own function.

**Comment by josevalim** [comment]
@msluszniak if you want to send a PR for a different function that computes only the singular values, it will be welcome. Perhaps we will even call it `singular_values`or `singular_value`. I will close this for now, it is up to you!
