### ISSUE TITLE
Add Fundamental Mathematical Constants

### ISSUE THREAD

**Issue by msluszniak** [elixir-nx/nx#1092]
I think `Nx` should support some of the most important mathematical constants. In `NumPy` there is support for:

* $e$ - base of the natural logarithm
* $\gamma$ - Euler's constant (Euler–Mascheroni constant)
* $\pi$

Those will be completely sufficient in my opinion.

**Comment by josevalim** [comment]
Agreed. We already have a Nx.Constants module. A pull requests there is welcome!
