### ISSUE TITLE
Documentation for LIBTORCH_TARGET is incorrect

### ISSUE THREAD

**Issue by RyoWakabayashi** [elixir-nx/nx#1100]
TorchX README says `LIBTORCH_TARGET` is `cpu`, `cu102` or `cu111`

https://github.com/elixir-nx/nx/blob/main/torchx/README.md

But actually it is one of `cpu`, `cu102`, `cu113` or `cu116`

https://github.com/elixir-nx/nx/blob/5c294265093c6acbaa0e8f6559e297b002cf1460/torchx/mix.exs#L7

**Comment by polvalente** [comment]
@RyoWakabayashi a PR is welcome!
