### ISSUE TITLE
[Question/Bug] How does Nx.stack work?

### ISSUE THREAD

**Issue by a-alhusaini** [elixir-nx/nx#1102]
I have this piece of code

```elixir
Nx.stack([house_value, house_age, median_income])
```

This works as expected. Creating a 3 x n shape.

```
#Nx.Tensor<
  f64[3][16512]
  [
    [2.25e5, 3.382e5, 2.27e5, 500001.0, 2.77e5, 2.631e5, 2.386e5, 2.436e5, 500001.0, 1.466e5, 1.063e5, 6.58e4, 1.35e5, 1.0e5, 1.265e5, 1.458e5, 4.5e4, 1.585e5, 2.593e5, 4.043e5, 1.656e5, 3.96e5, 1.331e5, 1.871e5, 1.225e5, 2.303e5, 1.795e5, 6.58e4, 2.317e5, 9.38e4, 3.651e5, 7.82e4, 1.142e5, 1.417e5, 500001.0, 2.75e5, 1.171e5, 1.192e5, 2.219e5, 3.095e5, 3.081e5, 500001.0, 1.322e5, 6.7e4, 1.594e5, 500001.0, 1.681e5, 2.325e5, 2.152e5, 1.667e5, ...],
    ...
  ]
>
```

However, this piece of code has a different result. I thought they would work the same?

```elixir
partial_tensor = Nx.stack([house_value, house_age], axis: 1)
Nx.stack([partial_tensor, median_income], axis: 1)
```

The result is... strange

```
#Nx.Tensor<
  f64[2][16512]
  [
    [2.25e5, 52.0, 3.382e5, 33.0, 2.27e5, 16.0, 500001.0, 33.0, 2.77e5, 28.0, 2.631e5, 19.0, 2.386e5, 37.0, 2.436e5, 41.0, 500001.0, 52.0, 1.466e5, 33.0, 1.063e5, 16.0, 6.58e4, 31.0, 1.35e5, 34.0, 1.0e5, 31.0, 1.265e5, 4.0, 1.458e5, 32.0, 4.5e4, 15.0, 1.585e5, 5.0, 2.593e5, 17.0, 4.043e5, 36.0, 1.656e5, 38.0, 3.96e5, 52.0, 1.331e5, 30.0, 1.871e5, 35.0, 1.225e5, 26.0, ...],
    ...
  ]
>
```

Why is it a 2 x n shape? I expected a 3 x n shape.

These 2 examples should produce identical output. Yet they don't.

It is probably me missing something obvious...

**Comment by josevalim** [comment]
`stack` will always add a new dimension where the number of elements in the dimension is given by the number of inputs. You may want to use Nx.concatenate/2 instead.

**Comment by a-alhusaini** [comment]
The shape in the 2nd code example is **2** x n. Where is the new dimension added?

**Comment by josevalim** [comment]
@a-alhusaini can you provide then the complete code or a minimal code that reproduces it?

**Comment by polvalente** [comment]
@josevalim It seems that there's something funky going on with mismatching shapes.
We can easily reproduce this with the following code:

```elixir
iex(8)> t = Nx.iota({10})
#Nx.Tensor<
  s64[10]
  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
>
iex(9)> Nx.stack([t, t], axis: 1)
#Nx.Tensor<
  s64[10][2]
  [
    [0, 0],
    [1, 1],
    [2, 2],
    [3, 3],
    [4, 4],
    [5, 5],
    [6, 6],
    [7, 7],
    [8, 8],
    [9, 9]
  ]
>
iex(11)> x = Nx.stack([Nx.stack([t, t], axis: 1), t], axis: 1)
#Nx.Tensor<
  s64[10][2]
  [
    [0, 0],
    [0, 1],
    [1, 2],
    [1, 3],
    [2, 4],
    [2, 5],
    [3, 6],
    [3, 7],
    [4, 8],
    [4, 9]
  ]
>
iex(12)> x.data.
__struct__    state
iex(12)> byte_size(x.data.state)
160
iex(13)> byte_size(t.data.state)
80
```

It's notable that the final "piped" stack doesn't contain the data for 3 times the original data, so it isn't just a case of mismatching output shape. The data changes between the first and second `stack` calls. I haven't checked other backends, though.

**Comment by a-alhusaini** [comment]
Sure, here is my code.

```elixir

defmodule FetchDataSet do
  @download_root "https://raw.githubusercontent.com/ageron/handson-ml2/master/"
  @housing_path Path.join(["ch2", "datasets", "housing"])
  @housing_url @download_root <> "datasets/housing/housing.tgz"

  def run(housing_url \\ @housing_url, housing_path \\ @housing_path) do
    if not File.dir?(housing_path) do
      File.mkdir_p!(housing_path)
    end

    resp = HTTPoison.get!(housing_url)
    tgz_path = Path.join([housing_path, "housing.tgz"])
    File.write!(tgz_path, resp.body)
    :erl_tar.extract(tgz_path, [:compressed, cwd: housing_path])

    IO.puts("Download successful")
  end
end

FetchDataSet.run()

train_split = DataFrame.from_csv!("./ch2/datasets/housing/housing.csv")

house_value = Explorer.Series.to_tensor(train_split["median_house_value"])
house_age = Explorer.Series.to_tensor(train_split["housing_median_age"])
median_income = Explorer.Series.to_tensor(train_split["median_income"])

# This is supposed to be 3 x n.
partial_tensor = Nx.stack([house_value, house_age], axis: 1)
Nx.stack([partial_tensor, median_income])
```

**Comment by polvalente** [comment]
EXLA gives a more reasonable error. I think this all just boils down to `stack` not having the proper check at the Nx level.

```elixir
iex(5)> Nx.stack([Nx.stack([t, t], axis: 1), t], axis: 1)
** (RuntimeError) Cannot concatenate arrays with different ranks: 3 (s64[10,1,2]) vs 2 (s64[10,1]).
    (exla 0.4.1) lib/exla/op.ex:861: EXLA.Op.unwrap!/1
    (exla 0.4.1) lib/exla/op.ex:109: EXLA.Op.get_shape/1
    (exla 0.4.1) lib/exla/builder.ex:23: EXLA.Builder.build/1
    (exla 0.4.1) lib/exla/defn.ex:306: EXLA.Defn.to_root_computation/6
    (exla 0.4.1) lib/exla/defn.ex:409: anonymous fn/10 in EXLA.Defn.compile/7
    (exla 0.4.1) lib/exla/defn/locked_cache.ex:36: EXLA.Defn.LockedCache.run/2
    (stdlib 4.0.1) timer.erl:235: :timer.tc/1
    (exla 0.4.1) lib/exla/defn.ex:398: EXLA.Defn.compile/7
 ```
 
 if we start with 2 `{n}` shaped tensors, stacking on `axis: 1` results in a `{n, 2}` tensor because it creates a new trailing axis (resulting in `{n, 1}`) and then concatenates on it.
 If we try and stack `{n, 2}` and `{n}`, both tensors have a new `1` axis inserted, resulting in the concatenation between `{n, 1, 2}` and `{n, 1}` over the `1` axis, which somehow results in `{n, 2}` in binary backend due to garbage-in/garbage-out.
 
 Since the same issue can be reproduced with `Nx.concatenate([Nx.iota({10, 1, 2}), Nx.iota({10, 1})], axis: 1)`, I think we should add a check in `Nx.concatenate`. Not sure what that check would be

**Comment by a-alhusaini** [comment]
I'd still assume that these should be identical...
```
Nx.stack([tensor1, tensor2, tensor3])
```
 
 and 
 ```
 partial_tensor = Nx.stack([tensor1, tensor2])
 Nx.stack([partial_tensor, tensor3])
 ```
 
 But thats not the case.. Should they be identical? I am pretty new to Nx

**Comment by josevalim** [comment]
@a-alhusaini it is not the case. Each stack call will add a new dimension.

@polvalente we need to at least check the ranks are the same, no?

**Comment by polvalente** [comment]
@josevalim yes, I think we should check that the ranks are the same.

Should we also check that the other axes have the same sizes? Like {m, 2, n} concatenated with {m, 1, n} and {m, 3, n} should yield {m, 6, n} if concatenated over axis:1 but raise due to the size of axis:1 over other axes

**Comment by josevalim** [comment]
@polvalente the more we can check, the better. I guess we should basically delete the axis we are concatenating and make sure the rest is equal.
