### ISSUE TITLE
Nx.Random.choice hangs forever

### ISSUE THREAD

**Issue by seanmor5** [elixir-nx/nx#1105]
I haven't looked deeper into isolating this. But if you look at: https://github.com/elixir-nx/bumblebee/pull/161

And try to run the sampling test, it will hang forever executing `Nx.Random.choice` within `sample_step`

**Comment by josevalim** [comment]
I am investigating. It is a Nx compile-time issue. The call to Nx.Random.choice never returns from compile time.

**Comment by josevalim** [comment]
The issue is that you are getting an exception and we are trying to format it and it is taking too long due to the inspect bug. I really need to rewrite our inspection algorithm. :S

**Comment by seanmor5** [comment]
Impossible, I never write bad code

**Comment by josevalim** [comment]
Tracked by #1013
