### ISSUE TITLE
Passing second argument to Nx.Defn.jit when Torchx and default_backend = [device: :cuda] fails

### ISSUE THREAD

**Issue by meanderingstream** [elixir-nx/nx#1109]
On Slack, I had a conversation about writing notebooks that support multiple backends.  The assertion was made that we already have that capability.  I've found a situation where jit fails.

To support easily switching between backends, I have a cell that has values for EXLA and Torchx.  For Torchx it has:
```
backend = Torchx.Backend
default_opts = [device: :cuda] # Default to gpu (only use if available)
# default_opts = [device: :cpu] # Default to cpu (no advantage if gpu available)
jit_opts = []  # nil doesn't work either

update_fn = Nx.Defn.jit(&LinReg.update/4, jit_opts)  fails
```
** (RuntimeError) Torchx: Could not run 'aten::empty.memory_format' with arguments from the 'CUDA' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'aten::empty.memory_format' is only available for these backends: [Dense, Conjugate, Negative, VmapMode, FuncTorchGradWrapper, MPS, UNKNOWN_TENSOR_TYPE_ID, QuantizedXPU, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, SparseCPU, SparseCUDA, SparseHIP, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, SparseXPU, UNKNOWN_TENSOR_TYPE_ID, SparseVE, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, NestedTensorCUDA, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID

**Comment by josevalim** [comment]
Can you please provide the code for LinReg.update/4? There seems to be one operation there that is not supported and we would need to identify and rewrite it.

**Comment by meanderingstream** [comment]
```
defmodule LinReg do
  import Nx.Defn

  # y = mx + b
  defn init_random_params do
    key = Nx.Random.key(42)
    {m, new_key} = Nx.Random.normal(key, 0.0, 0.1, shape: {1, 1})
    {b, _new_key} = Nx.Random.normal(new_key, 0.0, 0.1, shape: {1})
    {m, b}
  end

  defn predict({m, b}, inp) do
    Nx.dot(inp, m) + b
  end

  # MSE Loss
  defn loss({m, b}, inp, tar) do
    preds = predict({m, b}, inp)
    Nx.mean(Nx.pow(tar - preds, 2))
  end

  defn update({m, b} = params, inp, tar, step) do
    {grad_m, grad_b} = grad(params, &loss(&1, inp, tar))
    {m - grad_m * step, b - grad_b * step}
  end

  def train(params, epochs, lin_fn, jit_opts) do
    data =
      Stream.repeatedly(fn -> for _ <- 1..32, do: :rand.uniform() * 10 end)
      |> Stream.map(fn x -> Enum.zip(x, Enum.map(x, lin_fn)) end)

    # update_fn = EXLA.jit(&LinReg.update/4)
    # update_fn = Device.jit(device, &LinReg.update/4)
    # update_fn = Nx.Defn.jit(&LinReg.update/4)
    update_fn = Nx.Defn.jit(&LinReg.update/4, jit_opts)
    # update_fn = Nx.Defn.jit(&LinReg.update/4, [])

    for _ <- 1..epochs, reduce: params do
      acc ->
        data
        |> Enum.take(200)
        |> Enum.reduce(
          acc,
          fn batch, cur_params ->
            {inp, tar} = Enum.unzip(batch)
            x = Nx.reshape(Nx.tensor(inp), {32, 1})
            y = Nx.reshape(Nx.tensor(tar), {32, 1})
            # update(cur_params, x, y, 0.001)
            update_fn.(cur_params, x, y, 0.001)
          end
        )
    end
  end
end
```

**Comment by polvalente** [comment]
@meanderingstream what CUDA, OS and Libtorch version are you using?

**Comment by polvalente** [comment]
Also, please post the code you're using to call and get the error as well

**Comment by meanderingstream** [comment]
https://github.com/meanderingstream/problem_notebooks/blob/main/03f_multi_backend.livemd

| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0

**Comment by polvalente** [comment]
`nvcc --version` should give the actual CUDA version (my nvidia-smi shows 12.0 as well but nvcc shows 11.*)

**Comment by meanderingstream** [comment]
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Fri_Jan__6_16:45:21_PST_2023
Cuda compilation tools, release 12.0, V12.0.140
Build cuda_12.0.r12.0/compiler.32267302_0

**Comment by polvalente** [comment]
Probably the issue is the incompatible CUDA version. You're specifying CUDA 11.6 for Torchx but using CUDA 12.0.

Not entirely sure how XLA manages to work, but I guess their 11.8 build is better prepared to handle more recent CUDA as well.

You could try to use CUDA Pytorch from Python as well to eliminate this possibility

**Comment by meanderingstream** [comment]
I rolled CUDA back to 
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0

I'm still getting:
** (RuntimeError) Torchx: Could not run 'aten::empty.memory_format' with arguments from the 'CUDA' backend. This could be because the operator doesn't exist for this backend, or was omitted during the se

**Comment by meanderingstream** [comment]
I'm trying to set up a second machine so I can verify the issue more than this current machine.
However, I'm having trouble installing erlang-dev.  I've installed livebook as an escript with asdf.  I had chosen the latest elixir and erlang.  When torchx was installing, via Mix.install, it failed.  I already had build-essential.

sudo apt install erlang-dev results in:
The following packages have unmet dependencies:
 erlang-dev : Depends: erlang-base (= 1:24.2.1+dfsg-1) but 1:25.0.4-1 is to be installed
 
 I asdf uninstalled the 25 versions of erlang and elixir but the error doesn't go away.  Can you provide some clues to what I should try next?  Thanks,

**Comment by josevalim** [comment]
Can you try removing all Erlang from apt-get and rely only on the one from asdf?

**Comment by meanderingstream** [comment]
Always learning.  I had to 
apt list --installed | grep erlang
and then 
sudo apt purge <name>

Independent of the first machine, I went to the Nvidia 11-8-0 download, https://developer.nvidia.com/cuda-11-8-0-download-archive and I guess I ended up with the exact same nvcc version on the second machine.

I still had he same error.  I tried commenting out 


Please hold this for a few days while I work through some things.  I'm getting the error when I hard code to Nx.Defn.jit(&LinReg.update/4) without the second argument.  I have to focus on my day-job at the moment.

**Comment by meanderingstream** [comment]
I'll close for now and open another issue if I can repeat this in a way it is easier for others to repeat.
