### ISSUE TITLE
Add Skewness and Kurtosis

### ISSUE THREAD

**Issue by msluszniak** [elixir-nx/nx#1112]
I could implement those two features.

**Comment by josevalim** [comment]
I am thinking they should rather be in Scholar.Stats? Mirroring Scipy.Stats?

I know we added weighted_mean but I would say that it is much more common than these two. :) WDYT?

**Comment by msluszniak** [comment]
I think that's a really good idea! So I'll implement them in Scholar.Stats and closing for now.
