### ISSUE TITLE
Rename sigils to ~VEC and ~MAT

### ISSUE THREAD

**Issue by josevalim** [elixir-nx/nx#1114]
I sent a proposal for multi-letter uppercase sigils in Elixir. If accepted, we should rename our sigils to the ones above.

**Comment by dannote** [comment]
Can you explain why you don't want to keep the shorter versions? Are they confusing?

**Comment by josevalim** [comment]
Yes, pretty much. And given we are before 1.0 and still early in the adoption process, we can afford to rename without taking a single letter sigil.

**Comment by josevalim** [comment]
Done in 510e68903c46362eedb8f169cb079cf68da0f6c5.
