### ISSUE TITLE
Handling of NaN and infinity

### ISSUE THREAD

**Issue by josevalim** [elixir-nx/nx#119]
Today Nx operations fail if they find a NaN and/or Infinity (although defn behaviour will be compiler independent). Do we need to implement handling of NaN and infinity within Nx? What are the use cases?

**Comment by ondrej-tucek** [comment]
> What_ are the use cases?

In my humble opinion
1. definitely it would be valuable from **numerics aspect**. I mean, there are a plenty of numerical methods and algorithms which compute something with given precision. So if I'd start to calculate some mathematical problem, lets say with float32 precision, I'd also expect that result would be a value with float32 precision or an error message, e.g. `{:ok, 2.71} | {:error, "+Inf"}`.

2. **IoT**, thanks to Nerves project we can read a measured data from many types of sensors or can control devices (e.g. pressure valve, etc.). Each sensor's manufacturer (similar for control device) has own datasheet for given sensor where are written its limitations (e.g. raw binary range, endianness, service life,...) and howto use it. For example, according to datasheet you should convert a measured raw binary data to float32. And if Nx would have an implementation of convert function (binary to float32) as result type (i.e. `{:ok, val} | {:error, msg}`) then we can easily see that there is an issue with sensor, catch the error, send message to user,...


> we would just have to adjust some of the functions for reading/writing scalars to binaries.

I think that's good idea. I haven't look at on the core of Nx so deeply yet, thus I don't know how complicated can be it in your case. In our, it was simple an implementation of IEEE754 for [single](https://github.com/iodevs/ex_ieee754/blob/master/lib/ExIEEE754/single_precision.ex) and [double](https://github.com/iodevs/ex_ieee754/blob/master/lib/ExIEEE754/double_precision.ex) conversion.

**Comment by polvalente** [comment]
Commenting here so we can keep track of this here as well:

@dkuku found a match error in a Neural Net example which turned out to be related to Infinity. Minimal examples which fail like this on both f32 and f64:

```elixir
iex> Nx.tensor([1.0e32]) |> Nx.power(2) |> Nx.add(Nx.tensor([1]))
** (MatchError) no match of right hand side value: <<0, 0, 128, 127>>
    (nx 0.1.0) lib/nx/binary_backend.ex:632: anonymous fn/10 in Nx.BinaryBackend.element_wise_bin_op/4
    (elixir 1.13.0) lib/enum.ex:4136: Enum.reduce_range/5
    (nx 0.1.0) lib/nx/binary_backend.ex:628: Nx.BinaryBackend.element_wise_bin_op/4
```

```elixir
iex(2)> Nx.tensor([1.0e32], type: {:f, 64}) |> Nx.power(9) |> Nx.add(Nx.tensor([1.0e288]))
** (MatchError) no match of right hand side value: <<0, 0, 128, 127>>
    (nx 0.1.0) lib/nx/binary_backend.ex:639: anonymous fn/10 in Nx.BinaryBackend.element_wise_bin_op/4
    (elixir 1.13.0) lib/enum.ex:4136: Enum.reduce_range/5
    (nx 0.1.0) lib/nx/binary_backend.ex:628: Nx.BinaryBackend.element_wise_bin_op/4
```

**Comment by tiagodavi** [comment]
It's similar the error I am facing here:
https://github.com/elixir-nx/nx/issues/614

**Comment by polvalente** [comment]
Support for NaN, negative and positive infinity was added during addition of support for complex numbers. Some outstanding functions persist in #792 and #793, but I think this issue can be closed in favor of the specific ones
