### ISSUE TITLE
Nx.reduce_max returns wrong results for negative infinity

### ISSUE THREAD

**Issue by msluszniak** [elixir-nx/nx#1196]
The following code

```elixir
Nx.broadcast(Nx.Constants.neg_infinity(), {4}) |> Nx.make_diagonal() |> Nx.add(1) |> Nx.reduce_max(axes: [1])
```
returns
```
#Nx.Tensor<
  f32[4]
  [-Inf, -Inf, -Inf, -Inf]
>
```
But it should return
```
#Nx.Tensor<
  f32[4]
  [1.0, 1.0, 1.0, 1.0]
>
```

**Comment by polvalente** [comment]
This is a BinaryBackend bug :)

Probably some comparison is failing because `number < atom === true` in Elixir and non-finites are represented as atoms. Torchx and EXLA return the correct result. I'll send a fix.

**Comment by polvalente** [comment]
argmax/argmin also fall in the same situation, it seems. I'll also fix this in a separate PR
