### ISSUE TITLE
Docker considerations -- CMD vs RUN?

### ISSUE THREAD

**Issue by mlineen** [elixir-nx/nx#1206]
This documentation references changing `RUN path/to/release start` to `RUN sh -c "path/to/release start"`

https://github.com/elixir-nx/nx/blob/952e9bc0b4e2a9b029cf658c4157170e53007be6/exla/lib/exla.ex#L129-L160

But, shouldn't these be `CMD` instead? 

See https://hexdocs.pm/phoenix/releases.html#containers as an example Dockerfile; the last line is `CMD /app/bin/server`

**Comment by josevalim** [comment]
I have no idea. Have you tried any of them? Do any of them work?

**Comment by josevalim** [comment]
@mlineen can you please send a PR to use CMD and mention that you did for k8s? I don't have a lot of expertise in this area, so PRs are welcome!

**Comment by polvalente** [comment]
@mlineen I think using `tini` is a good idea.

I think the correct setup in this case would be something like this.
Especially in the case of a BEAM release, which will have basically as many processes as available system threads,
`tini` will ensure that the system runs under pid 1.

```Dockerfile
# Add Tini
ENV TINI_VERSION v0.19.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini
ENTRYPOINT ["/tini", "--"]

# Run your program under Tini
CMD ["/path/to/release", "start"]
```

**Comment by polvalente** [comment]
For the documentation, perhaps we should first mention just `CMD` and then mention `Tini` as a "good practices" add-on?

**Comment by mlineen** [comment]
I didn't want to be as prescriptive in terms of installing tini in my PR; I'm using `apt-get install tini` myself, and some people might prefer to use the signed binaries, checksum, etc examples instead. Again, happy to have this edited to whatever seems most useful for people.
