### ISSUE TITLE
`Nx.is_tensor/1` for :nan and :infinity

### ISSUE THREAD

**Issue by petrkozorezov** [elixir-nx/nx#1219]
`Nx.is_tensor/1` returns `true` for numbers but not for atoms `:nan`, `:infinity` and `:neg_infinity`.

```
iex(26)> Nx.is_tensor(42.0)
true
iex(27)> Nx.is_tensor(:nan)
false
```

**Comment by josevalim** [comment]
Ah, good find. A PR is welcome!
