### ISSUE TITLE
incorrect Nx.LinAlg.invert behavior?

### ISSUE THREAD

**Issue by naumruso** [elixir-nx/nx#1240]
Hi,

I have a matrix that I need inverted. I'm trying to compute its inverse with Nx.LinAlg.invert/1, but it does not seem that I'm getting the correct result. I'm not sure what exactly is happening here. nx is 0.5.3 running on erlang 26 (macos 13.3).

```
q = Nx.tensor([
      [1.0e-6, 5.0e-7, 5.0e-7, 5.0e-7],
      [5.0e-7, 1.0e-6, 5.0e-7, 5.0e-7],
      [5.0e-7, 5.0e-7, 1.0e-6, 5.0e-7],
      [5.0e-7, 5.0e-7, 5.0e-7, 1.0e-6]
    ], type: :f64)

invq = Nx.LinAlg.invert(q)
Nx.dot(invq, q)
```
output is:
```
#Nx.Tensor<
  f64[4][4]
  [
    [0.5625, -0.1875, -0.0625, 0.0],
    [0.125, 0.625, -0.125, 0.0],
    [0.25, 0.25, 0.75, 0.0],
    [0.5, 0.5, 0.5, 1.0]
  ]
>
```
which is (obviously) not an identity matrix. According to the docs, invert/1 should compute the inverse of a square matrix. Is this a bug or an expected behavior?

Thanks,
NR.

**Comment by polvalente** [comment]
Your matrix is quasi-singular (i.e. determinant is almost zero; 3.125e-25) according to Nx.LinAlg.determinant. So you are running into numerical errors (which are expected due to bad conditioning).

You can get around this by normalizing the matrix beforehand and then rescaling the inverse:

```elixir
iex(8) max_q = Nx.reduce_max(q)
# Here we rely on the fact that inv(cA) = (c ** -1) * inv(A) when c is scalar
iex(9)> inv_q = q |> Nx.divide(max_q) |> Nx.LinAlg.invert() |> Nx.multiply(Nx.divide(1, max_q))
#Nx.Tensor<
  f64[4][4]
  [
    [1.6e6, -400000.0000000002, -399999.9999999999, -4.0e5],
    [-400000.0000000002, 1.6e6, -4.0e5, -399999.99999999994],
    [-400000.00000000006, -4.0e5, 1600000.0000000002, -4.0e5],
    [-4.0e5, -399999.9999999999, -400000.0000000003, 1600000.0000000002]
  ]
>
iex(10)> Nx.dot(q, inv_q)                                                       
#Nx.Tensor<
  f64[4][4]
  [
    [1.0, -1.1102230246251565e-16, 2.7755575615628914e-17, 2.220446049250313e-16],
    [-1.942890293094024e-16, 1.0, 2.7755575615628914e-17, 2.220446049250313e-16],
    [-1.3877787807814457e-16, -2.7755575615628914e-17, 1.0, 2.220446049250313e-16],
    [-1.1102230246251565e-16, 5.551115123125783e-17, -1.6653345369377348e-16, 1.0000000000000002]
  ]
>
```

**Comment by polvalente** [comment]
2 minor adjustments:

1. `|> Nx.multiply(Nx.divide(1, x))` is the same as `Nx.divide(x)`
2. I should have used `max_q = Nx.reduce_max(Nx.abs(q))` for the normalization factor, but for your positive matrix this is not a problem

**Comment by naumruso** [comment]
okay. i didn't check if your algorithm normalized matrices before inverting. apparently not. 

thanks for the help anyway.

**Comment by polvalente** [comment]
For what it's worth, EXLA does normalize automatically. Torchx does suffer from this same problem, so #1241 will fix this problem. I opened a separate issue so that the actual fix is not buried in the comments instead of the issue body.
