### ISSUE TITLE
Problem that an argument of a function defined by `Defn` cannot be passed as the option `n` of `Nx.linespace/3`

### ISSUE THREAD

**Issue by zacky1972** [elixir-nx/nx#1259]
Hi,

I think it will be more useful to be able to write a program code of `Defn` that passes the argument as the option `n` of `Nx.linespace/3` as follows:

```elixir
  defn function(stage) do
    Nx.linspace(0, 1, n: stage + 1)
    |> ...
  end
```

However, it will meet the following error:

```
(Compile Error) Nx.to_number/1 is not allowed inside defn
```

**Comment by polvalente** [comment]
There are 2 ways to fix that:

`deftransform function(n)`

Or

```elixir
defn function(opts \\ []) do
  n = opts[:n]
  ...
end
```

**Comment by polvalente** [comment]
The issue is that defn will treat all arguments that are not default-valued to lists as Nx.Containers, which means that plain numbers will become Nx.Tensors.

deftransform doesn't convert things, but you lose the autoimport for Nx.Defn.Kernel
