### ISSUE TITLE
Nx.Serving stuck at terminating (cannot merge batches with different batch keys)

### ISSUE THREAD

**Issue by SteffenDE** [elixir-nx/nx#1287]
Hi there,

after updating to Nx 0.6 I've encountered a serving that is stuck, i.e. any call to that serving using batched_run never completes.
I've narrowed this down using the erlang observer, seeing that the serving process is stuck in the `terminating` function in line 1216, seemingly waiting for tasks to finish.

I tried logging the reason which did not work and then put it in the process dictionary instead to see it in the observer:

```erlang
{#{message =>
       <<"cannot merge batches with different batch keys: :default and {:sequence_length, 128}">>,
   '__struct__' => 'Elixir.ArgumentError','__exception__' => true},
 [{'Elixir.Nx.Batch','-merge/1-fun-0-',3,[{file,"lib/nx/batch.ex"},{line,79}]},
  {'Elixir.Enum','-reduce/3-lists^foldl/2-0-',3,
                 [{file,"lib/enum.ex"},{line,2510}]},
  {'Elixir.Nx.Batch',merge,1,[{file,"lib/nx/batch.ex"},{line,74}]},
  {'Elixir.Nx.Serving',stack_to_batch_refs,1,
                       [{file,"lib/nx/serving.ex"},{line,1371}]},
  {'Elixir.Nx.Serving',server_maybe_task,1,
                       [{file,"lib/nx/serving.ex"},{line,1279}]},
  {'Elixir.Nx.Serving',handle_info,2,[{file,"lib/nx/serving.ex"},{line,1178}]},
  {gen_server,try_handle_info,3,[{file,"gen_server.erl"},{line,1077}]},
  {gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,1165}]},
  {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,241}]}]}
```

I also inspected the tasks that the serving is waiting for, and they do not actually exist according to the observer. The whole state looks like this (erlang syntax):

```erlang
#{timeout => 50,module => 'Elixir.Nx.Serving.Default',limit => 32,
  module_state =>
      #{0 =>
            #{{sequence_length,128} =>
                  #Fun<Elixir.Bumblebee.Text.TextEmbedding.7.98522632>}},
  tasks =>
      [{#{owner => <0.857.0>,pid => <0.17902.0>,
          mfa => {erlang,apply,2},
          '__struct__' => 'Elixir.Task',
          ref => #Ref<0.0.109699.1301032490.900530177.19826>},
        0,
        [{#Ref<0.0.2289155.1301032490.900268034.194899>,0,10},
         {#Ref<0.0.2289411.1301032490.900530177.19823>,10,10},
         {#Ref<0.0.2289539.1301032490.900268034.194900>,20,10},
         {#Ref<0.0.2289283.1301032490.900268034.194901>,30,2}]}],
  streaming_table => nil,
  out_queue => {[],[]},
  in_queue => {[{sequence_length,128}],[]},
  pending_batches => #{{sequence_length,128} => {[],[]}},
  task_supervisor =>
      'Elixir.MyApp.Serving.TaskSupervisor'}
```

Sadly, I cannot reproduce this in a clean repo, as the app uses Oban Pro to call the serving using a chunked worker. Somehow the default batch key gets in there, despite the serving having a batch key of `{:sequence_length, 128}`.

I create the serving like this:

```elixir
{:ok, model_info} = Bumblebee.load_model({:hf, "sentence-transformers/all-MiniLM-L6-v2"})
{:ok, tokenizer} = Bumblebee.load_tokenizer({:hf, "sentence-transformers/all-MiniLM-L6-v2"})

serving =
  Bumblebee.Text.TextEmbedding.text_embedding(model_info, tokenizer,
    compile: [batch_size: 32, sequence_length: 128],
    defn_options: [compiler: EXLA],
    output_attribute: :hidden_state,
    output_pool: :mean_pooling
  )
```

And start it in the supervision tree `{Nx.Serving, serving: serving, name: MyApp.Serving, batch_timeout: 50}`.

Maybe someone with insights into how the batches are implemented knows how this can happen. I think that these are two separate problems though:

1. the serving seems to wait for tasks to finish that do not actually exist, getting stuck
2. the batch keys get mixed up, leading to the termination in the first place

**Comment by SteffenDE** [comment]
btw: maybe adding a timeout to batched_run would be a good idea? Similar to how a GenServer.call times out.

Then the Oban jobs in my case would not be stuck executing forever, but fail instead.

**Comment by josevalim** [comment]
Hi @SteffenDE, what is your exact Nx version? v0.6.0 or some commit sha?

**Comment by SteffenDE** [comment]
74e46e3e637e6247d3e9f517d5aa2be09e438a07 (the latest commit) since 0.6 does not include the fix for https://github.com/elixir-nx/nx/pull/1283

**Comment by SteffenDE** [comment]
I can confirm that it seems to work fine with https://github.com/elixir-nx/nx/commit/61c367a73fa676d5e2d337561304aaab5d8e916d. Not sure if that fixes the serving getting stuck on terminate though.

**Comment by josevalim** [comment]
@SteffenDE yeah, I am trying to understand how/why it is getting stuck on terminate. The server does have a shutdown timeout but that is only used from the supervisor, not from internal crashes. In any other scenario it would not exceed 30 seconds. So I may add a timeout to shutdown anyway.

**Comment by josevalim** [comment]
Ok, I understand how it happened. We got the message the task was completed, then we tried to spawn a new task but it failed, causing terminate to be invoked. But we did not update the state to remove the task that was just completed, so we would wait for it forever. This has also been fixed in main. I will release a new version this upcoming week. :)

**Comment by josevalim** [comment]
Also, keep in mind that we do have a shutdown limit for server (specified in its parent supervisor), but it is not invoked for internal crashes. So it was really the combination of two bugs that made this happen. :)
