### ISSUE TITLE
Support passing a list of tensors in Nx.tensor/2

### ISSUE THREAD

**Issue by jadengis** [elixir-nx/nx#1288]
# Problem
Currently, `Nx.tensor/2` supports the following two methods of building a new tensor
```elixir
Nx.tensor([[1, 2, 3], [4, 5, 6]])
```
and
```elixir
existing_tensor = Nx.tensor([1, 2, 3])

# new tensor with potentially different opts
Nx.tensor(existing_tenstor, opts)
```
However, passing in a list of existing tensors is not supported:
```elixir
t1 = Nx.tensor([1, 2, 3])
t2 = Nx.tensor([4, 5, 6])

# This throws an error in `infer_type/1`.
Nx.tensor([t1, t2], opts)
```
# Solution
It would be really convenient if the `Nx.tensor/2` supported passing a list of tensors to initialize a new tensor.

Current work around is to do something like this
```elixir
t1 = Nx.tensor([1, 2, 3])
t2 = Nx.tensor([4, 5, 6])

[t1, t2]
|> Enum.map(&Nx.to_list/1)
|> Nx.tensor(opts)
```
But there probably is a much better way.

# Use Case
Some libraries e.g. Scholar, have APIs that are expecting a 2-D list of coordinates. I have existing 1-D tensors that I am pulling from a database and trying to use them as a list of coordinates for fitting methods.

**Comment by polvalente** [comment]
Hi! For that specific use case you should look into Nx.stack or Nx.concatenate. transpose, new_axis and reshape might also be of use.

**Comment by polvalente** [comment]
For what it's worth, I went to try and improve the error message, but it already mentions concatenate and stack, at least if we pass `opts = []`. Did you get a different message, @jadengis?

**Comment by jadengis** [comment]
@polvalente  I was getting a message like `"invalid value given to Nx.tensor/1, got: #{inspect(value)}"`, but I am on 0.5.3. I see now that the message is improved for 0.6.0. I'll try out stack. Thanks!
