### ISSUE TITLE
Support more operations in EXLA over MLIR

### ISSUE THREAD

**Issue by polvalente** [elixir-nx/nx#1295]
#1247 added support for MLIR compilation to EXLA

The following functions still have to be supported for full coverage:

- [x] window_reduce

## Require complex numbers

- [x] conj
- [x] complex
- [x] fft
- [x] ifft
- [x] imag
- [x] real

## Require HLO->MHLO conversion

- [ ] eigh
- [ ] cholesky
- [ ] qr

## Done

- [x] abs
- [x] acos
- [x] acosh
- [x] add
- [x] asin
- [x] asinh
- [x] atan
- [x] atan2
- [x] atanh
- [x] bitwise_and
- [x] bitwise_not
- [x] bitwise_or
- [x] bitwise_xor
- [x] cbrt
- [x] ceil
- [x] constant_from_binary
- [x] constant_r0
- [x] convert_element_type
- [x] cos
- [x] cosh
- [x] div
- [x] eq_total_order
- [x] equal
- [x] erf
- [x] erf_inv
- [x] erfc
- [x] exp
- [x] expm1
- [x] floor
- [x] get_shape_op
- [x] get_tuple_element
- [x] greater
- [x] greater_equal
- [x] iota
- [x] is_finite
- [x] is_infinity
- [x] is_nan
- [x] less
- [x] less_equal
- [x] log
- [x] log1p
- [x] max
- [x] min
- [x] mul
- [x] ne_total_order
- [x] neg
- [x] not_equal
- [x] parameter
- [x] pow
- [x] rem
- [x] round
- [x] rsqrt
- [x] shift_left
- [x] shift_right_arithmetic
- [x] shift_right_logical
- [x] sigmoid
- [x] sign
- [x] sin
- [x] sinh
- [x] sqrt
- [x] sub
- [x] tanh
- [x] tuple
- [x] bitcast_convert_type
- [x] broadcast_in_dim
- [x] clamp
- [x] clz
- [x] concatenate
- [x] dot
- [x] dot_general
- [x] dynamic_slice
- [x] optimization_barrier
- [x] pad
- [x] population_count
- [x] reshape
- [x] reverse
- [x] select
- [x] slice
- [x] transpose
- [x] map
- [x] reduce
- [x] variadic_reduce
- [x] conv_general_dilated
- [x] create_token
- [x] dynamic_update_slice
- [x] gather
- [x] scatter
- [x] select_and_scatter
- [x] sort
- [x] top_k
- [x] triangular_solve
- [x] variadic_sort
- [x] infeed
- [x] outfeed
- [x] conditional_if
- [x] call
- [x] while_loop

**Comment by wtedw** [comment]
Is this required for full Apple Silicon support?

**Comment by polvalente** [comment]
> Is this required for full Apple Silicon support?

It's a requirement, but not sufficient. The fact that the Jax/XLA metal plugin is closed source means that we can't lock into the older version of OpenXLA that would be needed for Metal support, because it would mean depending on something we have zero control over, while potentially keeping bugfixes, optimizations and features out of our codebase.

**Comment by wtedw** [comment]
Gotcha, thanks 👍

**Comment by atomkirk** [comment]
Thank you for doing this!!!

**Comment by polvalente** [comment]
closing this in favor of #1392
