### ISSUE TITLE
Automatic double quotes in environment variables preventing windows installation of EXLA

### ISSUE THREAD

**Issue by tricoire-timour** [elixir-nx/nx#1305]
# Description of the issue
As a Windows user, I have an issue where, when I try to install EXLA, even after setting my `XLA_BUILD` and `MAKE` environment variables, and adding the path to nmake to my `Path` variable, I get the following error message:
```elixir
iex(1)> Mix.install([{:exla, "~> 0.6.0"}])
==> xla
Compiling 2 files (.ex)
Generated xla app
could not compile dependency :xla, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile xla --force", update it with "mix deps.update xla" or clean it with "mix deps.clean xla"
** (Mix.Error) ""C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64\nmake.exe"" not found in the path. If you have set the MAKE environment variable, please make sure it is correct.

    (mix 1.15.0) lib/mix.ex:577: Mix.raise/2
    (elixir_make 0.7.7) lib/elixir_make/compiler.ex:115: ElixirMake.Compiler.cmd/5
    (elixir_make 0.7.7) lib/elixir_make/compiler.ex:92: ElixirMake.Compiler.make/2
    (elixir_make 0.7.7) lib/elixir_make/compiler.ex:53: ElixirMake.Compiler.compile/1
    (mix 1.15.0) lib/mix/task.ex:447: anonymous fn/3 in Mix.Task.run_task/5
    (mix 1.15.0) lib/mix/tasks/compile.all.ex:124: Mix.Tasks.Compile.All.run_compiler/2
    (mix 1.15.0) lib/mix/tasks/compile.all.ex:104: Mix.Tasks.Compile.All.compile/4
    iex:1: (file)
```

# Where the error comes from
I tracked the error down from ElixirMake.Compiler.cmd/5 into the erlang source, where `os:verify_executable/1` calls `file:read_file_info/1` and cannot find nmake. I figured out that this issue was due to the fact that windows adds double quotes on the outside of environment variables that contain spaces, which are retained when elixir fetches the variable, as seen in the code:
```elixir
iex(1)> System.fetch_env!("MAKE")
"\"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\Hostx64\\x64\\nmake.exe\""
iex(2)> System.fetch_env!("MAKE") |> :file.read_file_info()
{:error, :enoent}
iex(3)> System.fetch_env!("MAKE") |> String.replace("\"", "") |> :file.read_file_info()
{:ok,
 {:file_info, 108992, :regular, :read_write, {{2023, 9, 5}, {15, 19, 21}},
  {{2023, 8, 30}, {9, 3, 24}}, {{2023, 8, 30}, {9, 3, 24}}, 33279, 1, 3, 0, 0,
  0, 0}}
```  

# Fixes?
I have not been able to find a fix on the windows side, to prevent the addition of the quotes either side, and either way I think there are other windows users who would like to use EXLA and find themselves stuck on the same problem. As such, I propose adding some code that checks if MAKE is wrapped in quotes and if so, removes them. 

I'm reporting this error to EXLA because it's the top level of the issue, and I'm not sure where a fix should be implemented and what it would look like; while the best case would probably be instructions in the error message on how to change the `MAKE` environment variable to prevent the bug, I can't find anything that might work online. It would also be possible to change ElixirMake, but I beileve the change would be quite intrusive, and obviously changing System.find_executable/1 goes all the way down to the language itself.

**Comment by josevalim** [comment]
Can you inspect the MAKE env var on Windows outside of Elixir? It looks like the env var is indeed wrong. What did you use to install nmake? Can you reinstall it? Or change it manually? Here is a sample article: https://www.computerhope.com/issues/ch000549.htm

**Comment by tricoire-timour** [comment]
I installed it using Visual Studio Installer, but it somehow failed to modify my environment variables (even after severall re-installations), so I added them in myself using a procedure quite like the one in the article-- however, just modifying `PATH` does not work, and I get an error about the `MAKE` env var, which I have also set manually. This is the one with the quotes around.
Inspecting my `MAKE` env var in cmd looks quite normal:
```cmd
echo %MAKE%
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64\nmake.exe
```

**Comment by josevalim** [comment]
If System.fetch_env! comes with quotes, then the issue is happening either in the Erlang VM or in the C level. Can you please try this:

    set "MAKE=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64\nmake.exe"

And then running Elixir's System.fetch_env?

**Comment by tricoire-timour** [comment]
This is exactly what I found was going on, and accordingly, the problem goes away after doing that:
```elixir
iex(1)> System.fetch_env("MAKE")
{:ok,
 "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\Hostx64\\x64\\nmake.exe"}
```
This also works when opening a new command line shell, and even after restarting. Running `Mix.install([{:exla, "~> 0.6.0"}])` still does not work, but the provided error message is different (`Could not compile with "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64\nmake.exe" (exit status: 2).`). Either way, the current issue is solved. I expect reinstalling c++ build tools might solve my problems.

**Comment by josevalim** [comment]
Yes, so whatever tool is setting the MAKE is adding the quotes at some point but not really our doing. :( Thanks!
