### ISSUE TITLE
Nx.Random.randint does not work with full interval

### ISSUE THREAD

**Issue by polvalente** [elixir-nx/nx#1309]
The following code snippets fail with similar errors:

```elixir
Nx.Random.randint(Nx.Random.key(52), 0, 2**8, shape: {2, 7}, type: :u8)

Nx.Random.randint(Nx.Random.key(52), 0, 2**32, shape: {2, 7}, type: :u32)
```

I believe that the fix would be to allow `nil` as the upper limit for the interval, making it effectively a closed interval on the maximum possible value.

**Comment by josevalim** [comment]
Instead of nil, we should use atoms, such as :min_finite and :max_finite. Otherwise it sounds good to me. Note you can also use values from Nx.Constants.

**Comment by polvalente** [comment]
> Shouldn’t it be closed for consistency with Elixir itself?

Could be too. I'm not sure why it's open. Probably easier to implement.

Let's refactor/breaking change it into closed intervals? I believe other functions might need changing too.

Although maybe the consistency here is wirh :rand/:random.

**Comment by josevalim** [comment]
Let’s not break the API. So we should introduce a new function. Although I think we should rename anyway because it is obvious it is rand from the module it is in. I am open to suggestions on the name!

**Comment by josevalim** [comment]
randint in numpy is exclusive on the higher end, so it probably makes sense to be consistent. I would go ahead and close this for now. If you really want to include that last value, you can do arithmetic operations or we can add another function in the future (or support the atoms as mentioned).
