### ISSUE TITLE
Add Nx.correlation

### ISSUE THREAD

**Issue by msluszniak** [elixir-nx/nx#1310]
As mentioned in #1289 if we want to deprecate the functionalities from `Scholar.Covariance` we should also support correlation. I can add this one.

**Comment by josevalim** [comment]
I would rename `Scholar.Covariance.correlation_matrix` to `Scholar.Stats.correlation` instead. WDYT?

**Comment by msluszniak** [comment]
It is an option. But personally, I would find the fact that covariance is in `Nx` and correlation in `Scholar` a little bit confusing.  They differ only in that Pearson correlation is covariance divided by a multiple of standard deviations of both variables. In Python ecosystem, they are both available in `Scipy`.

**Comment by josevalim** [comment]
I understand but Nx is already very large and we only added correlation because it was used by Random. So let's rename Scholar.Covariance.correlation_matrix to Scholar.Stats.correlation instead.  :) Thanks!
