### ISSUE TITLE
2D FFTs

### ISSUE THREAD

**Issue by josevalim** [elixir-nx/nx#1323]

**Comment by polvalente** [comment]
Looking into this. We can provide this as an optional callback in terms of FFT!

Although Torchx and EXLA will probably have their own, we can skip the binary backend implementation (aside from supporting axis in FFT) using:

`FFT2(X, axes: [ax1, ax2], lengths: [l1, l2]) === FFT(FFT(X, axis: ax2, length: l2), axis: ax1, length: l1)`

**Comment by seanmor5** [comment]
I am pretty sure the JAX 2D FFT is just using pocket FFT or cuFFT

**Comment by polvalente** [comment]
Yes, libtorch also probably has its implementation. I'm adding it as an optional callback nevertheless. Helps with grad and binary backend :)

**Comment by GJBoth** [comment]
Sorry to reopen this thread but I can't find `fft2` and `ifft2` in 0.6.4 release? This release happened after Oct 1 first, so not sure what's going on?

**Comment by polvalente** [comment]
v0.6 was released before the inclusion of fft2/ifft2, and v0.6.x are patches, which will generally include only backported fixes to already existing features.

You can either pull Nx from github main, or extract the optional implementation into a custom defn. Something like:

```elixir
defn fft2(tensor, opts \\ []) do
  [ax1, ax2] = opts[:axes]
  [l1, l2] = opts[:lengths]
  eps = opts[:eps]
  
  tensor
  |> fft(axis: ax2, length: l2, eps: eps)
  |> fft(axis: ax1, length: l1, eps: eps)
end
```

And likewise for `ifft2` (just replace `fft` with `ifft` above)

**Comment by GJBoth** [comment]
Thanks! Unfortunately `axis` argument to fft also seems to be included in the `fft2` MR, so that's not an option. Whats the alternative? Vectorise and transpose?

**Comment by polvalente** [comment]
Ah, you're right! By default fft will work on the last axis. So you could transpose the two target axes into the last dimensions, apply fft, transpose to swap the last 2 axes, apply fft again, and then do the transpose to restore axis ordering.

Pulling from GitHub is definitely preferable, if possible!
