### ISSUE TITLE
Default value for 0 division

### ISSUE THREAD

**Issue by salah-walid** [elixir-nx/nx#1342]
Using an element-wise Nx.divide in case of a 0 divider it would be nice to have a default value instead of a a raised error.
```elixir
Nx.divide(Nx.tensor([1, 2, 3]), Nx.tensor([1, 0, 3]))
```

If there is a workaround to avoid indices on the divider side it would also work

**Comment by polvalente** [comment]
You can either use Nx.select to replace zero values, or add an epsilon to the divisor. There is no reasonable default value we could set to a zero division, so this is best left to the user.
