### ISSUE TITLE
Enum.zip equivalent in Nx, or a way to map through multiple tensors at the same time

### ISSUE THREAD

**Issue by salah-walid** [elixir-nx/nx#1344]
A function like `Nx.zip(Nx.tensor([1,2]), Nx.tensor(3,4))` that would give a response like `Nx.tensor([[1,3], [2,4]])`

**Comment by seanmor5** [comment]
Can you elaborate on what you need this for? Usually it's a bad idea to to manually iterate through a tensor like this (we have a map function that could do this). There are typically better ways to achieve the same thing

**Comment by salah-walid** [comment]
Hi @seanmor5, thank you for the reply.

What i am looking for is a way to zip two tensors similar to [Enum.zip](https://hexdocs.pm/elixir/1.15.0/Enum.html#zip/2) but using tensors
If not possible use [Nx.map](https://hexdocs.pm/nx/Nx.html#map/3) to go through two or more different tensors at the same this and construct another tensor accordingly

**Comment by seanmor5** [comment]
Yeah I understand the request :) just curious what the use case is! Many operations are already elementwise and achieve what you want without needing to manually zip

**Comment by salah-walid** [comment]
I have two tensors of xs and ys constructed this way
```elixir
xs = Nx.iota({height, width}, axis: 1)
yy = Nx.iota({height, width}, axis: 0)
```

I want to zip these two values in order to use them with `Nx.indexed_put` as indices

**Comment by polvalente** [comment]
These indices look a lot like you could achieve the same result by reshaping and/or transposing your values tensor.

Either that, or if you're inserting a tensor into a larger one, look into put_slice

**Comment by josevalim** [comment]
Yes, zipping is not supported on purpose because individual traversal is often undesired. You can either express it using functions that operate on the whole tensor or use a while loop inside `defn`.
