### ISSUE TITLE
Load balancing for distributed Nx.Serving

### ISSUE THREAD

**Issue by mntns** [elixir-nx/nx#1346]
We're planning to run a `Nx.Serving` distributed over a heterogenous cluster that contains mainly CPU-based nodes and would like to route batches preferentially to GPU nodes (using EXLA's CUDA client).

As far as I can tell there is no way to achieve that with the current distribution mechanism, is that correct? The randomized load balancing performs weighted scheduling based on the partition count, but there doesn't seem to be a way to assign weights based on e.g. the machine type (statically) or have dynamic resource-based scheduling.

**Comment by josevalim** [comment]
Yes, there is no static nor dynamic resource-based scheduling. We could allow weights to be assigned, that would be relatively easy, but dynamic routing is trickier on a distributed system. The best I can think of is to fallback to CPU if there is no GPU.

**Comment by josevalim** [comment]
Yes, there is no static nor dynamic resource-based scheduling. We could allow weights to be assigned, that would be relatively easy, but dynamic routing is trickier on a distributed system. The best I can think of is to fallback to CPU if there is no GPU.

**Comment by mntns** [comment]
Thanks for the quick response! I opened a PR that adds simple weights to that effect.

**Comment by josevalim** [comment]
Closing in favor of the PR :)
