### ISSUE TITLE
Matrix not rendered properly in the docs

### ISSUE THREAD

**Issue by gustawlippa** [elixir-nx/nx#1352]
Hi!
The matrix in the file [nx/guides/tensor-aggregation-101.livemd](https://github.com/elixir-nx/nx/blob/v0.6.2/nx/guides/tensor-aggregation-101.livemd) is not rendered properly on hexdocs: https://hexdocs.pm/nx/tensor-aggregation-101.html

![image](https://github.com/elixir-nx/nx/assets/34194983/43a08f9d-1001-433a-a945-5d8ddd7357b9)

Although it works for example in GitHub (I assume same goes for Livebook):
![image](https://github.com/elixir-nx/nx/assets/34194983/d4223a39-75f4-4d79-b86b-be1a4822c335)

There are also some issues with displaying other mathematical data (this line is very long for example):
![image](https://github.com/elixir-nx/nx/assets/34194983/d0547a11-9b1a-464a-9d95-af0025c6868c)

**Comment by josevalim** [comment]
@ndrean, would you be able to take a look? Thank you!

**Comment by ndrean** [comment]
oh, indeed! I didn't looked at the Hexdocs. Time to dive into Hexdocs,  Earmark and probably [Mathjax](https://www.mathjax.org/).

**Comment by josevalim** [comment]
You can run `MIX_ENV=docs mix docs` (or just `mix docs`?) in the `nx` subfolder and you should be able to see results locally. :)

**Comment by josevalim** [comment]
You can also find the configuration on `nx/mix.exs`.

**Comment by jonatanklosko** [comment]
This is the same as https://github.com/elixir-lang/ex_doc/issues/1571.

In this specific example this manifests in two ways:

* `_` pairs being expanded to markdown italic
* `\\` is escaped backslash and gets converted to `\`

**Comment by ndrean** [comment]
Maybe a naive quick thought: Earmark produces an HTML string, doesn't it?  If we just ask Earmark to leave whatever is between $ signs, and embed MathJax in the rendered document (like adding a <script src=cdn mathjax...>), couldn't it render math? I also saw a [MathJax.typeset](https://docs.mathjax.org/en/latest/advanced/typeset.html)

**Comment by jonatanklosko** [comment]
@ndrean we don't want Earmark to inject the script, that should be up to the user. But yeah, the proper solution is to make Earmark aware of $ and $$, so their contents are not interpreted as Markdown :)

**Comment by ndrean** [comment]
@jonatanklosko ah, I see you already inject Katex, somehow used the "mix": [defp before_closing_body_tag(:html)](https://github.com/elixir-nx/nx/blob/94037abeabd7d3668a0b27d0669768b25d38be8f/nx/mix.exs#L120C6-L120C6)

I don't understand/know the interactions between ex_docs, earmark, so I believe you have a better position to open an issue to earmark, if this is the potential response?

**Comment by josevalim** [comment]
We don't have another option to handle this that doesn't require changing Earmark? Make we can indent with four spaces and remove the wrapping pre tag accordingly?

**Comment by jonatanklosko** [comment]
@josevalim we could support alternative syntax (like GitLab, https://github.com/elixir-lang/ex_doc/issues/1571#issuecomment-1121064714), but that creates more friction for people to use it. IIRC we were leaning towards `$` and `$$` support in Earmark, because GitHub added support for it.

**Comment by josevalim** [comment]
So request on Earmark it is. We will most likely have to contribute it. What do we do with this guide meanwhile? Can we avoid using `_` or `\\`? Or should we keep it on GitHub and remove it from the docs?

**Comment by polvalente** [comment]
> So request on Earmark it is. We will most likely have to contribute it. What do we do with this guide meanwhile? Can we avoid using `_` or `\\`? Or should we keep it on GitHub and remove it from the docs?

`\\` is used for linebreaks, so I think it's rather unavoidable. `_` could maybe be substituted by `^` if we changed subscripts to superscripts

**Comment by ndrean** [comment]
When you look at the Nx guide - for example, <https://hexdocs.pm/nx/intro-to-nx.html#broadcasts>- you see that Latex is parsed correctly with $$ and \begin. The problem starts when you have nested commands (\begin{matrix} \begin{matrix}...)., so it might not be straightforward.

I would remove this one from the hexdocs for the moment, just keep the Livebook and a link to the Github.

**Comment by josevalim** [comment]
Done for now. The core issue is currently trackled on ExDoc. Thanks!
