### ISSUE TITLE
EXLA does not consider the device on EXLA.Backend operations

### ISSUE THREAD

**Issue by josevalim** [elixir-nx/nx#1357]
The bug is here: https://github.com/elixir-nx/nx/blob/main/exla/lib/exla/backend.ex#L322

_Originally posted by @josevalim in https://github.com/elixir-nx/xla/issues/58#issuecomment-1802327668_

**Comment by polvalente** [comment]
I wonder if Nx should have some kind of device abstraction in the API itself. It could be useful for serving distribution, and Torchx also has the same problem throughout
