### ISSUE TITLE
`top_k` doesn't behave properly with :neg_infinity

### ISSUE THREAD

**Issue by krstopro** [elixir-nx/nx#1365]
Running the following code
```
tensor = Nx.tensor([1, 2, :neg_infinity])
Nx.top_k(tensor, k: 2)
```
gives
```
{#Nx.Tensor<
   f32[2]
   [-Inf, 2.0]
 >,
 #Nx.Tensor<
   s64[2]
   [2, 1]
 >}
```

**Comment by krstopro** [comment]
The reason is probably that `Nx.sort` doesn't work with `:neg_infinity`.
```
> Nx.sort(tensor)
#Nx.Tensor<
  f32[3]
  [1.0, 2.0, -Inf]
>
```
Is this intended?

**Comment by krstopro** [comment]
Probably not, as it works with `:infinity`.
```
tensor = Nx.tensor([2, :infinity, 1])
Nx.sort(tensor)
#Nx.Tensor<
  f32[3]
  [1.0, 2.0, Inf]
>
```

**Comment by polvalente** [comment]
Just to be sure, which version of Nx is this?

Have you checked EXLA too? This probably is a BinaryBackend-only bug

**Comment by krstopro** [comment]
> Just to be sure, which version of Nx is this?
> 
> Have you checked EXLA too? This probably is a BinaryBackend-only bug

Could be the case. Having a look immediately.

**Comment by krstopro** [comment]
@polvalente You are correct, this doesn't happen with EXLA. As for the version, I just pulled from main.

**Comment by polvalente** [comment]
This is probably an easy fix on sort, where we need to account for infinities and nan, which by default compare to greater than numbers because they are atoms under the hood

**Comment by josevalim** [comment]
I am working on this.
