### ISSUE TITLE
Nx.LinAlg.solve/2 with Nx.BinaryBackend returns tensor with wrong state

### ISSUE THREAD

**Issue by Aetherus** [elixir-nx/nx#1427]
`Nx.LinAlg.solve(a, b)` with `Nx.BinaryBackend` returns tensor with wrong state when `b` has more columns than rows.

For example,

```elixir
a = Nx.tensor([
  [1, 1],
  [1, 2]
], type: :f64)

b = Nx.tensor([
  [2, 2, 2],
  [3, 3, 3]
], type: :f64)

x = Nx.LinAlg.solve(a, b)

Nx.shape(x)  # returns {2, 3} as expected

byte_size(x.data.state)  # expected: 48, actual: 32
```

I was trying to spot the issue, but it seems the issue is inside the function `Nx.BinaryBackend.Matrix.ts/8`, which I don't know what it's doing.

`EXLA.Backend` has no such issue.

**Comment by josevalim** [comment]
Which Nx version? Did you try main? Is it using the default Nx backend or EXLA/Torchx?

**Comment by Aetherus** [comment]
The version I'm using is 0.6.4

**Comment by Aetherus** [comment]
I tried using the main branch in livebook, but I can't install it. The error is

```
** (Mix.Error) App nx lists itself as a dependency
    (mix 1.15.7) lib/mix.ex:577: Mix.raise/2
    (elixir 1.15.7) lib/enum.ex:984: Enum."-each/2-lists^foreach/1-0-"/2
    (mix 1.15.7) lib/mix/dep/converger.ex:18: Mix.Dep.Converger.topological_sort/1
    (mix 1.15.7) lib/mix/dep/converger.ex:91: Mix.Dep.Converger.converge/4
    (mix 1.15.7) lib/mix/dep/fetcher.ex:16: Mix.Dep.Fetcher.all/3
    (mix 1.15.7) lib/mix/tasks/deps.get.ex:34: Mix.Tasks.Deps.Get.run/1
    (mix 1.15.7) lib/mix/task.ex:455: anonymous fn/3 in Mix.Task.run_task/5
```

**Comment by Aetherus** [comment]
> Is it using the default Nx backend or EXLA/Torchx?

It's using the `Nx.BinaryBackend`.

**Comment by josevalim** [comment]
Pass `githubi: "elixir-nx/nx", sparse: "nx"` when using Nx as a git dep. :)

**Comment by Aetherus** [comment]
@josevalim Thank you for your suggestion. I tried the main branch, and this issue is still there.
