### ISSUE TITLE
Expand docs for the :axes option in Nx.gather/3

### ISSUE THREAD

**Issue by Benjamin-Philip** [elixir-nx/nx#1443]
The documentation for the `:axes`  option in`Nx.gather/3` can do with some clarification:

- All the examples pertain to collecting subsets. The docs do not explain if and how you can collect scalars.
- The list "nature" of `:axes` is not explained. All the examples have only a single axis in the list. What is the difference between `axes: [0, 1]` and `axes: [1]`?
- The description "The :axes option controls which dimensions the indexes point to" can be cryptic to someone new to the library
- (optional, potentially too verbose) An example of "leading axes" can be helpful to someone new.

**Comment by josevalim** [comment]
PRs welcome!
