### ISSUE TITLE
HexDocs shows Nx 0.9 docs w/ empty sidebar and w/o version selector

### ISSUE THREAD

**Issue by jyc** [elixir-nx/nx#1540]
Hello! Thanks again for making Nx, I am finding it very useful.

I'm not sure whether this is the right place to submit the bug, but I noticed that if I go to:

- https://hexdocs.pm/nx/Nx.html or
- https://hexdocs.pm/nx/0.9.0/Nx.html

I no longer get a sidebar or version selector. Search also appears not to work. Weirdly, the 0.8.0 docs still work (discussed later).

It looks like this:

<img width="1239" alt="image" src="https://github.com/user-attachments/assets/58995bf7-0197-4ee4-905d-5d6978c24c9f">

I thought this might be a general ExDoc issue, but e.g. Elixir documentation still looks fine: https://hexdocs.pm/elixir/1.17.2/Kernel.html

This seems to be the same on my home network & cellular network & w/ different DNS settings.

Like I mentioned there's no version selector for the Nx docs. But I manually changed the URL to get the Nx 0.8.0 docs, which look perfectly fine! The 0.8.0 docs have a sidebar & version selector and search works: https://hexdocs.pm/nx/0.8.0/search.html?q=grad

<img width="1241" alt="image" src="https://github.com/user-attachments/assets/7df5a094-bb96-47cb-a642-a6a1682eccce">

I briefly tried to debug but nothing obvious stood out. I saw this issue, but it doesn't seem to be related; I don't see mermaid being loaded in the network console. https://github.com/elixir-lang/ex_doc/issues/1941

It's not blocking me because I can just manually go to the 0.8.0 docs but I figured I should report it. Let me know if I can help any more! If you point me to where the sidebar is loaded (it doesn't look like it's in `make/ex_doc.exs`) I'd even be happy to debug a little, although I can't guarantee I'll have enough time to fix it. I figured I'd post in case the fix is obvious to you guys.

**Comment by polvalente** [comment]
I've republished the docs and it seems to be working correctly now!

**Comment by jyc** [comment]
Thanks!!
