### ISSUE TITLE
Make weighted shape a property of binary tensor

### ISSUE THREAD

**Issue by seanmor5** [elixir-nx/nx#206]
cc @elbow-jason and the discussion on views/in-place operations

While we can't necessarily manipulate the underlying memory of the binary from Elixir, our main abstraction `weighted_shape` can be manipulated in clever ways to reduce the amount of copying between operations. Currently, `weighted_shape` is used alongside some other helper methods in almost all of our implementations to indicate how to traverse the binary along any given axis. As an example, the transpose implementation is simply:

* Get the weighted shape from the binary
* Permute the weighted shape
* Traverse binary according to weighted shape

We could make this operation more efficient by making `weighted_shape` a property of the Binary tensor that's calculated on tensor creation and then make the transpose operation basically a meta operation that just works on weighted shape. That means something like:

```elixir
tensor
|> Nx.transpose()
|> Nx.transpose()
|> Nx.transpose()
|> Nx.transpose()
```

Is actually only ever manipulating the binary once according to the permutation after the final transpose! Similar ideas can be used to optimize some of our other operations as well. For example, a slice isn't really a new binary, it's just a binary with a sliced weighted shape.

Major changes that need to take place for this to go into effect:

* Add `weighted_shape` metadata to BinaryTensor
* Calculate `weighted_shape` on tensor creation
* Ensure every method traverses the binary according to it's weighted shape
* Add a traversal to inspect

This is somewhat related to [PyTorch Views](https://pytorch.org/docs/stable/tensor_view.html). Main problems with this approach are that it may end up being more expensive with element-wise binary operations.

**Comment by josevalim** [comment]
I will be closing this for now. The BinaryBackend is not intended to focus on performance and, if we were to rewrite it, I would also like to rewrite only once we have a blas-level like bindings, so we can also get performance at the lower level.
