### ISSUE TITLE
Support updates with put_in and update_in

### ISSUE THREAD

**Issue by josevalim** [elixir-nx/nx#229]
This is so we can have a more complete implementation of the Access protocol for Tensors

**Comment by polvalente** [comment]
@josevalim It seems that #817 would enable this issue through `indexed_set`. WDYT?

**Comment by josevalim** [comment]
get_in uses slices, which I think the put_slice is already enough to implement this. :)

**Comment by josevalim** [comment]
Reopening this because the way of updating is quite painful. We need to roll your own version of Access for now.

**Comment by josevalim** [comment]
Closing as we will relax indexed_add and indexed_put instead.
