### ISSUE TITLE
Windows BEAM missing some math functions in Nx.shared

### ISSUE THREAD

**Issue by jj1bdx** [elixir-nx/nx#239]
Windows BEAM does not have the following OTP math module functions: asinh, acosh, atanh, erf, and erfc.
This lack of functions causes installation failure of Nx on Windows BEAM.
Corresponding source of Nx:
https://github.com/elixir-nx/nx/blob/560ec29ce38a583fedacfe21c0c74aa7bfa4d7dc/nx/lib/nx/shared.ex#L137-L166

See maint-23 Branch of Erlang/OTP:

* https://github.com/erlang/otp/blob/maint-23/erts/emulator/beam/erl_math.c#L146-L153
* https://github.com/erlang/otp/blob/maint-23/erts/emulator/sys/win32/erl_win_sys.h#L74-L82

There might be many ways to work around with this, but I guess it's up to the Nx devs.

BTW kudos to the Nx and Exla development! 👍

**Comment by seanmor5** [comment]
@jj1bdx Thanks for pointing this out! I usually test on Windows but I missed it in this case. All of these functions can be implemented/approximated in terms of existing functions in Nx. We'll more than likely just have to check for OS and fallback to those implementations.

**Comment by jj1bdx** [comment]
@seanmor5 Yes, I agree that implementing these functions in Nx would be a good workaround.

**Comment by jj1bdx** [comment]
Another long-term approach that comes up in my mind is to enable asinh/acosh/atanh/erf/erfc functions in the math module of Erlang/OTP. These five functions have been available since C11 and C++11. It's 2021 already, and [Erlang building doc for Windows](http://erlang.org/doc/installation_guide/INSTALL-WIN32.html#tools-you-need-and-their-environment) suggests Visual Studio 2019 to build the BEAM, which does include these functions in the math library.

**Comment by elbow-jason** [comment]
@jj1bdx Would that mean that these definitions themselves should be conditional based on the compiler version? Is that info available during preprocessing?

If so, that might be a good contribution to Erlang itself.

```c
#define NO_ASINH
#define NO_ACOSH
#define NO_ATANH
#define NO_ERF
#define NO_ERFC
```

**Comment by jj1bdx** [comment]
@elbow-jason Exactly on the removal of the `NO_*` definitions.
