### ISSUE TITLE
EXLA: Bazel 3.1.0 (exact match) semes to be required

### ISSUE THREAD

**Issue by jamilbk** [elixir-nx/nx#252]
Installing bazel `3.7.2` with `asdf install bazel 3.7.2` and then running `mix deps.compile exla` fails with:

```
ERROR: The project you're trying to build requires Bazel 3.1.0 (specified in /home/jamil/.cache/exla/tf-6af836f407f546cf2f9ab3b5fcb7a8285bda5c96/erts-11.1.7/.bazelversion), but it wasn't found in /home/jamil/.asdf/installs/bazel/3.7.2/lib/bazel/bin.
```

Presumably this is because of [`.bazelversion` in the tensorflow tree](https://github.com/tensorflow/tensorflow/blob/6af836f407f546cf2f9ab3b5fcb7a8285bda5c96/.bazelversion).

Installing bazel 3.1.0 via asdf fixes the issue.

**Comment by josevalim** [comment]
It is curious because it runs on v3.7.0 for me but I will date the docs to say v3.1.0 exclusively. Thanks!
