### ISSUE TITLE
Import default math function into `defn`'s scope 

### ISSUE THREAD

**Issue by elcritch** [elixir-nx/nx#267]
## Proposal 

Change `defn` to import the `Nx` namespace by default, or alternatively a smaller more tailored set of functions and operators. 

In addition it'd be useful to include constants like \pi and \e and to include overloaded arithmetic operators for `+`, `-`, etc. 

Discussing this earlier would probably be better than later. Though it's nice that it wouldn't be too difficult for a third party library to provide a custom `defn` (or `defnx` or some such) that could this. :-) 

## Background 

In Python it's common to do `import numpy as np` but I believe that's primarily because of Python's language design. Doing numerical programming with NumPy often results in a dozen lines of imports in every single file. 

Julia (and MATLAB) both import a wide selection of mathematical functions without needing to prefix them. In [Julia this includes](https://docs.julialang.org/en/v1/base/math/#Mathematical-Functions) functions like `cos`, `sin`, `minimum`, `sum`, etc. It's useful in languages oriented for numerical programming. 

## Examples 

As an example this would change these examples from: 

```elixir
    defn distance(p, x, y, w), do: Stats.norm(p, x |> Nx.subtract(y) |> Nx.dot(w)) 
    defn sum_of_products(x, y), do: Nx.dot(x, y) |> Nx.to_scalar()
    defn mu(mx, kfx, alphaf), do: mx |> Nx.add(kfx |> Nx.dot(alphaf)) 
    defn gpe(x, w), do: Nx.sum(x |> Nx.dot(w)) / Nx.sum(w)  
    defn stats(x, mean_x, y, mean_y, divisor), do: Nx.sum((x |> Nx.subtract(mean_x)) |> Nx.dot(y |> Nx.subtract(mean_y) |> Nx.transpose())) / divisor
```

To this:

```elixir
    defn distance(p, x, y, w), do: Stats.norm(p, (x - y) |> dot(w)) 
    defn sum_of_products(x, y), do: x |> dot(y) |> to_scalar()
    defn mu(mx, kfx, alphaf), do: mx + (kfx |> dot(alphaf))
    defn gpe(x, w), do: sum(x |> dot(w)) / sum(w)  
    defn stats(x, mean_x, y, mean_y, divisor), do: (sum(x - mean_x) |> dot(transpose(y - mean_y)) / divisor
```

Or with a dot operator as well:

```elixir
    defn distance(p, x, y, w), do: Stats.norm(p, (x - y) <*> w) 
    defn sum_of_products(x, y), do: x <*> y |> to_scalar()
    defn mu(mx, kfx, alphaf), do: mx + kfx <*> alphaf
    defn gpe(x, w), do: sum(x <*> w) / sum(w)  
    defn stats(x, mean_x, y, mean_y, divisor), do: sum(x - mean_x) <*> transpose(y - mean_y) / divisor
```

**Comment by seanmor5** [comment]
I'm in favor of the addition of constants, off the top of my head probably: `e`, `pi`, `inf`, `negative_inf`, and maybe `nan`.

With regards to always importing the Nx namespace, my only concern would be ambiguity, but because of the restricted nature of `defn` that's not really much of a problem here. I think then for me it's just weighing the ergonomics. I like the `Nx` prefix but that's probably because it's so common place in Python e.g.

`import numpy as np`
`import tensorflow as tf`
`import torch.nn.functional as F`

As you pointed out, that could just be a consequence of Python and not actually desirable. If everything was imported by default we could still prefix but the reverse is not true (I think?). 

On this topic, and this is totally bikeshedding, but I would like to see something like:

`use Nx`

over:

`import Nx.Defn`

**Comment by elbow-jason** [comment]
I tend to shy away from "naked" imports. In the case of `Nx.` it would shorten each of these call sites by 3 letters, which is good for typing. But it drastically negatively affects code clarity. 

When I see a call to `sum` I have 5 considerations to resolve:

1) Does the module I am in have a `sum/1` defined?
2) Nx has a `sum/1`?
3) Does the scope I am in have a `sum/1` imported from somewhere other than Nx?
4) Does the scope I am in have a macro that could inject or import a `sum/1`?
5) Does the scope I am in `import Nx`?

Additionally, now that I am importing I should must avoid naming any of my functions the same names as any imported functions and, while I am at it, I should also not name variables the same names as imported functions just for clarity and maintainability.

When I see `Nx.sum` I have 2 considerations to resolve:

1) In the scope I am in is there an `alias OtherModule, as: Nx`
2) In the scope I am in is there a macro that is aliasing Nx or defining an Nx module inline?

From experience, it is much easier to program in a language when the "Where is this coming from?" question is answered quickly and simply.

For this reason, library developers and maintainers should be extra cautious about what imports they encourage become "naked".

Right now, the Nx lib has 2 (that I know of) accepted conventional imports `defn` and `defnp`.

I would resist expanding this convention to include more functions without a very good reason.

**Comment by elcritch** [comment]
@elbow-jason For general purpose programming I’d agree with you. Specifically for numerical coding though I believe there are a few considerations that make it different. 

> In the case of `Nx.` it would shorten each of these call sites by 3 letters, which is good for typing. But it drastically negatively affects code clarity.

The typing saved is handy but the real benefit is legibility when dealing with complicated mathematical expressions. Adding those three letters for each math function inside `defn` blocks means a significant amount of extra clutter. The final `defn stats` example is almost a half as short, and much clearer than the original. This can save your bacon when writing tricky expressions. 

This is taken from real numerical code I wrote and I’ve already noticed a few points of redundancy and unnecessary operations by using a more ‘math like’ notation. 

My take is that implementing mathematical algorithms is already complicated enough that keeping the syntax as close as reasonable to the mathematical notation form really does help!

> Right now, the Nx lib has 2 (that I know of) accepted conventional imports defn and defnp. 

To clarify, my proposal here is to _only_ do the naked import only inside the scope of of a `defn` or `defnp`. The idea is that in the context of a `defn` I’d prefer to assume everything in this scope is math related. Hopefully this encourages keeping the math functions as focused as possible! Ideally you wouldn’t be writing general purpose code inside a defn block. 

The semantics of operators like `*` are already different in most cases where you’re using tensors and matrices. I believe importing common math/tensor operations inside a `defn` block helps reinforce that “something different is happening here” which is a good thing in this context. 

I’m not sure if `defn` already overrides `*` and other arithmetic operators but its a logical boundary to redefine them. Using `|> Nx.add` instead of `+` is not only more verbose, but also changes the precedence of the expression which requires different groupings than the mathematical notation. In net this usually means more parentheses. 

> When I see Nx.sum I have 2 considerations to resolve: 

That’s true and for normal code I appreciate that as well. Knowing exactly what modules you’re calling a function from helps, especially in a dynamically typed language. But in the context of a `defn` I prefer to focus on figuring out why someone is taking a `sum(mx)`, and figuring out the rank of the tensors involved, the resulting rank and dimensions, and what it means wrt to the algorithm. 

Prefixing with `Nx.` doesn’t really further those specific goals and clutters up the symbol `sum` which relates to a mathematical notion with implied meanings. Julia takes this approach of focusing on a broad set of mathematical function “interfaces” and IMHO really benefits from it. It doesn’t shorten names but it also allows the names to become a broader “interface” that can (and should be) be extended. 

I believe auto-importing a general set of common mathematical functions in  `defn` context introduces this concept into Elixir and turns Nx into even more of a “platform”.

**Comment by josevalim** [comment]
I don't want to mix those for now because the kernel contains functions that are not available outside of `defn`. Mixing those will make it very confusing what you can actually call on defn vs elsewhere (IEx, scripts, etc). We also don't know how large the numerical kernel will grow over the next months.

We named the project Nx exactly so we don't need aliases and keep things short. I will be glad to revisit this in maybe a year for now but I think the premature importing of Nx can be harmful in the long term.
