### ISSUE TITLE
Inverse trig gradient test fails depending on seed

### ISSUE THREAD

**Issue by maxastyler** [elixir-nx/nx#270]
On certain seeds (for example: 453568, 643645) the test `test inverse trig family computes gradient of inverse trig functions` in `Nx.Defn.GradTest` fails. 

This is because `check_grads!` fails on values close to ±0.9... 

The test could be made to always check these bounds, so as to always fail, or have the random bounds reduced so it doesn't encounter this error.

**Comment by josevalim** [comment]
I have pushed a fix just now. I have also decoupled the eps from the steps, so that should give us more fine grained control. Thanks!
