### ISSUE TITLE
Nx.pad is incorrectly documented?

### ISSUE THREAD

**Issue by turion** [elixir-nx/nx#278]
It says:

> A padding  configuration is a list of tuples consisting of  `{pad_width_low, pad_width_high}` for each dimension  in the input tensor.

But all the examples give triples (e.g. `{0,0,1}`).

**Comment by seanmor5** [comment]
Yes that's a typo, padding configurations are supposed to be:

`{pad_width_edge_low, pad_width_edge_high, pad_width_interior}`

I'll push a fix

**Comment by seanmor5** [comment]
See: https://github.com/elixir-nx/nx/commit/2b94263cb59503867fd164290f40c9c272727322
