### ISSUE TITLE
Nx.random_uniform/2 raises in BinaryBackend for non-float types 

### ISSUE THREAD

**Issue by elbow-jason** [elixir-nx/nx#282]
When the code path reaches [these lines inside Nx.BinaryBackend.random_uniform/3](https://github.com/elixir-nx/nx/blob/4acedf922b490f29972158f98f68bc8577b2d281/nx/lib/nx/binary_backend.ex#L28-L29
) with the default range of `0.0, 1.0` from `Nx.random_uniform/2`, the calls `:rand.uniform(max - min)` are passed a float. The [docs for `:rand.uniform/1`]() say that it only accepts positive integers.

There are a few ways to fix this:

  + raise when int types are passed to `Nx.random_uniform/2`
  
  + use different defaults for int types in `Nx.random_uniform/2`
  
  + cast the `min - max` in `Nx.BinaryBackend.random_uniform/3` to int e.g. `(min - max) |> Float.round |> trunc`

This would be a good place to start for a new contributor.

The error:

```elixir
iex(14)> Nx.random_uniform({2, 4, 2}, type: {:s, 32}) 
** (FunctionClauseError) no function clause matching in :rand.uniform_s/2    
    
    The following arguments were given to :rand.uniform_s/2:
    
        # 1
        1.0
    
        # 2
        {%{
           bits: 58,
           jump: #Function<3.47293030/1 in :rand."-fun.exsplus_jump/1-">,
           next: #Function<0.47293030/1 in :rand."-fun.exsss_next/1-">,
           type: :exsss,
           uniform: #Function<1.47293030/1 in :rand."-fun.exsss_uniform/1-">,
           uniform_n: #Function<2.47293030/2 in :rand."-fun.exsss_uniform/2-">
         }, [197936017285128206 | 88863623788616986]}
    
    (stdlib 3.13.2) rand.erl:326: :rand.uniform_s/2
    (stdlib 3.13.2) rand.erl:299: :rand.uniform/1
    (nx 0.1.0-dev) lib/nx/binary_backend.ex:28: anonymous fn/2 in Nx.BinaryBackend.random_uniform/3
    (nx 0.1.0-dev) lib/nx/binary_backend.ex:33: anonymous fn/4 in Nx.BinaryBackend.random_uniform/3
    (elixir 1.11.2) lib/enum.ex:3449: Enum.reduce_range_inc/4
    (nx 0.1.0-dev) lib/nx/binary_backend.ex:33: Nx.BinaryBackend.random_uniform/3
```

**Comment by josevalim** [comment]
For floats, the best approach is probably to call :rand.uniform() with no argument and then do the scaling afterwards:

    :rand.uniform * (max - min) + min

A new regression test should be added to test/nx_test.exs. :)

**Comment by xire28** [comment]
New contributor here, will prepare a MR

**Comment by xire28** [comment]
It only generates zeros when Nx.random_uniform/1 is used with non-float types. Is it a correct behavior ?

**Comment by xire28** [comment]
Because it only generates zeros when Nx.random_uniform/2 is used with non-float types, I think solution 1 is the best one.
Updating MR

**Comment by xire28** [comment]
Ended up moving the "raise" to the main method if types are incompatible:
- Float tensor + float or int range -> OK
- Int tensor + Float range -> raise

Added the check for random_normal too for consistency, currently it raises "argument error" with no message when used with non-float tensor.

Waiting for feedback
