### ISSUE TITLE
Nx.Cholesky/1 raises ArithmeticError on odd dimensions symmetric square matrix

### ISSUE THREAD

**Issue by xire28** [elixir-nx/nx#288]
Reproduction code:
```elixir
t1 = Nx.iota({5, 5})
t2 = Nx.add(t1, Nx.transpose(t1))
Nx.cholesky(t2)
```

Stacktrace:
```elixir
** (ArithmeticError) bad argument in arithmetic expression
     code: Nx.cholesky(t2)
     stacktrace:
       (nx 0.1.0-dev) lib/nx/binary_backend.ex:992: anonymous fn/8 in Nx.BinaryBackend.cholesky/2
       (elixir 1.11.3) lib/enum.ex:3461: Enum.reduce_range_inc/4
       (nx 0.1.0-dev) lib/nx/binary_backend.ex:948: anonymous fn/8 in Nx.BinaryBackend.cholesky/2
       (elixir 1.11.3) lib/enum.ex:3461: Enum.reduce_range_inc/4
       (nx 0.1.0-dev) lib/nx/binary_backend.ex:945: Nx.BinaryBackend.cholesky/2
       test/nx_test.exs:1127: (test)
```

Error line:
```elixir
value = 1.0 / read!(diag, 0) * (read!(x, 0) - tmp_sum)
```

`read!(diag, 0)` returns `0` in this case, which results in `(ArithmeticError) bad argument in arithmetic expression`

No tests are present in nx for `Nx.cholesky/1` (only in exla), I think it could be a good opportunity to improve the coverage at the same time.

**Comment by josevalim** [comment]
Thanks for the report! Our basic tests are done via doctests. But as we tests different scenarios we will improve them via tests. 

And to be clear, what would you expect as a result?

**Comment by xire28** [comment]
Forgot about the doctest coverage.

Closing the issue, will reopen only after finding a good enough proposition on how it should behave.
Thanks

**Comment by josevalim** [comment]
For completeness, we don't handle infinity/nans yet, this is being tackled on #119.
