### ISSUE TITLE
AOT cross compilation

### ISSUE THREAD

**Issue by josevalim** [elixir-nx/nx#291]
Today header/object file emitted by EXLA can be cross-compiled but I assume our `bazel build` call wraps the precompiled EXLA artifact in NIFs is not currently cross-compiled.

@seanmor5, do you believe it would be difficult to ask Bazel to cross compile at this step as well?

**Comment by seanmor5** [comment]
I think we can, I'll dig into the documentation!

**Comment by josevalim** [comment]
We have added `bazel_flags` and `bazel_env` to allow people to customize the bazel call.
