### ISSUE TITLE
Failed backend build for Mac M1 chip

### ISSUE THREAD

**Issue by lenileiro** [elixir-nx/nx#312]
I am receiving errors when trying to compile both backends.

- EXLA backend

`
[warn]  The on_load function for module Elixir.EXLA.NIF returned:
{:error,
 {:load_failed,
  'Failed to load NIF library: \'dlopen(/Users/user/Desktop/research/ml/_build/dev/lib/exla/priv/libexla.so, 2): no suitable image found.  Did find:\n\t/Users/user/Desktop/research/ml/_build/dev/lib/exla/priv/libexla.so: mach-o, but wrong architecture\n\t/Users/user/Desktop/research/ml/_build/dev/lib/exla/priv/libexla.so: stat() failed with errno=35\''}}
`

- Torchx backend

`
Compiling: c_src/torchx.cpp
ld: warning: ignoring file /Users/user/Downloads/libtorch/lib//libtorch.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
[warn] The on_load function for module Elixir.Torchx.NIF returned:
{:error,
 {:load_failed,
  'Failed to load NIF library: \'dlopen(/Users/user/Desktop/research/ml/_build/dev/lib/torchx/priv/torchx.so, 2): Symbol not found: __ZN3c1019UndefinedTensorImpl10_singletonE\n  Referenced from: /Users/user/Desktop/research/ml/_build/dev/lib/torchx/priv/torchx.so\n  Expected in: flat namespace\n in /Users/user/Desktop/research/ml/_build/dev/lib/torchx/priv/torchx.so\''}}`

**Comment by wojtekmach** [comment]
@lenileiro see #217 for EXLA.

**Comment by drozzy** [comment]
Same issue here with M1, with exla not compiling.
