### ISSUE TITLE
Create a working version of the Makefile for windows compilation

### ISSUE THREAD

**Issue by josevalim** [elixir-nx/nx#314]

**Comment by polvalente** [comment]
I'm trying to setup Elixir on windows to validate this issue

**Comment by josevalim** [comment]
Yes, usually a Makefile.win is necessary. We have one for EXLA too. :)

**Comment by josevalim** [comment]
Basic support has been added thanks to @howard0su! We need to explore mechanisms so mangling $PATH is not necessary.

**Comment by howard0su** [comment]
we can close this now. it is fixed.
