### ISSUE TITLE
Investigate PyTorch and Vulkan

### ISSUE THREAD

**Issue by fire** [elixir-nx/nx#323]
Vulkan compute is exciting is because all of AMD, Intel, Samsung, Arm, Broadcom, Nvidia, Qualcomm, Imagination Tech, Apple (through Vulkan to metal) have a way to run compute. OpenCL is dead.

https://pytorch.org/tutorials/prototype/vulkan_workflow.html

For Linux:

```bash
cd PYTORCH_ROOT
USE_VULKAN=1 USE_VULKAN_SHADERC_RUNTIME=1 USE_VULKAN_WRAPPER=0 python setup.py
install
```

**Comment by versilov** [comment]
Investigation will be possible when we support device selection during tensor creation. Which should happen this week.

**Comment by fire** [comment]
I'm able to get back on this in May.

Let's write a description of the current state of this.

**Comment by versilov** [comment]
Nice!

Device selection is ready, just not in the main branch yet.

**Comment by fire** [comment]
Can you tell me what has happened since? Wanted to get back into this.

**Comment by josevalim** [comment]
Torchx development has stalled for now, so we will close this until it resumes. Thanks!
