### ISSUE TITLE
Add defn code reference to the stacktrace

### ISSUE THREAD

**Issue by versilov** [elixir-nx/nx#326]
defn code is hard to debug, because stack trace lacks reference to the line inside defn function, which initiated the error. And there is no mention of initial function call, that resulted in the error also.

E. g. in the code below there is no reference to the call of `Nx.mean/1`, which actually caused the error:

```
== Compilation error in file examples/mnist_native.exs ==
** (ArgumentError) Torchx does not support unsigned 64 bit integer 
    (torchx 0.1.0-dev) lib/torchx/backend.ex:57: Torchx.Backend.torch_type/2
    (nx 0.1.0-dev) lib/nx/defn/evaluator.ex:64: Nx.Defn.Evaluator.eval/3
    (elixir 1.11.2) lib/enum.ex:1521: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
```

At least we need to add explicit function call line to the stack trace.
At max we should add reference to the file and line of defn code, where this call occured.

**Comment by versilov** [comment]
Actual function call is made here through `eval/3`:

https://github.com/elixir-nx/nx/blob/83e22924044d71ebb0ad5d3e04e94072ad91986f/nx/lib/nx/defn/evaluator.ex#L64

**Comment by josevalim** [comment]
Yes, this is a bit complicated because the expression is first built and then evaluated. So we would need to add a bunch of metadata nodes to control file/line. We will see what comes out of this. :)
