### ISSUE TITLE
Add support for strings

### ISSUE THREAD

**Issue by ivan-rivera** [elixir-nx/nx#335]
Please correct me if I'm wrong here (I'm quite new to the Elixir community), but from what I understand, Nx does not support strings. On the other hand, its Python equivalent, [Numpy](https://numpy.org/) does support strings which makes it a versatile tool for handling most data structures. Having string support would allow us to build higher-level abstractions like [Pandas](https://pandas.pydata.org/) data frames on top of Nx.

I'd love to hear what you guys think about it!

**Comment by josevalim** [comment]
Hi @ivan-rivera, I recommend to track issue #301, as that means we will support strings somehow, even if as a binary of offsets. But our support will only be limited - at least for now. I am also not sure if a Pandas for Elixir would necessarily build on top of Nx. Progress happening in other areas, such as Arrow, may prefer to tackle those problems as two distinct things.
