### ISSUE TITLE
Returns the indices after sorting a tensor

### ISSUE THREAD

**Issue by carlosfrodrigues** [elixir-nx/nx#342]
Hi everybody,
I am trying to implement a function that receives a tensor and returns the indices of each value after the tensor has been sorted. Something exactly like the argsort  function from Numpy (https://numpy.org/doc/stable/reference/generated/numpy.argsort.html).
I even called @polvalente to help me but we ran out of ideas.

Anyone has any idea how this can be implemented using Nx?

**Comment by seanmor5** [comment]
This is not possible with the current API as far as I can tell. We would need to add support for something similar to:

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/xla/client/xla_builder.h#L2367

That returns a tuple and then you can sort with an `iota`.

**Comment by polvalente** [comment]
@seanmor5 do you think this is something that could be implemented easily given what we already have?
As far as the BinaryBackend goes I reckon it's not that much of a hassle to sort two or more corresponding tensors given the a sort on the first one, but I'm not sure about EXLA or Torchx

**Comment by elbow-jason** [comment]
This is easily doable with the branch I've been working on for BinaryBackend: #322

**Comment by josevalim** [comment]
> @seanmor5 do you think this is something that could be implemented easily given what we already have?

Yes! We already accept a similar shape to sort on the `reduce` functions, so we just need to copy it and support it on XLA. The argsort can be implemented based on sort, something like:

    binary_as_a_list
    |> Enum.with_index()
    |> Enum.sort()
    |> Enum.map(&elem(&1, 1))

I would suggest to start with the XLA one. :)
