### ISSUE TITLE
Keyword lists should raise on non-existing

### ISSUE THREAD

**Issue by seanmor5** [elixir-nx/nx#347]
This:

```elixir
defn my_function(x, opts \\ []) do
  opts = keyword!(opts, [epsilon: 1.0e-5])
  x + opts[:not_a_key]
end
```

Will produce an error message like:

```
** (FunctionClauseError) no function clause matching in Nx.Type.sort/2    
    
    The following arguments were given to Nx.Type.sort/2:
    
        # 1
        {:f, 32}
    
        # 2
        nil
    
    Attempted function clauses (showing 1 out of 1):
    
        defp sort({left_type, _} = left, {right_type, _} = right)
```

In a complex expression, it's easy to make this mistake, and not immediately clear from the error message what the actual issue is

**Comment by josevalim** [comment]
We do raise for unknown keys! Maybe there is something else at play here?

**Comment by seanmor5** [comment]
We do raise on unknown keys that are passed to `opts`, but I don't think we raise when trying to access a key that doesn't exist

**Comment by seanmor5** [comment]
I just realized this probably wouldn't be possible at the `defn` level because it depends on the `Access` behaviour. I'm confused though why we get this error message and not an issue about trying to convert `nil` to a tensor?

**Comment by josevalim** [comment]
Can you provide a complete example? keyword! in the example should fail if opts has a key that is not in the given list.

**Comment by seanmor5** [comment]
@josevalim Sorry I was not as clear :) `keyword!` does fail if the user provides a bad option. So you are right this will raise:

```elixir
defn my_func(test, opts \\ []) do
  opts = keyword!(opts, [epsilon: 1.0e-5])
  x + opts[:epsilon]
end
```

```
iex> my_func(test, not_a_key: 1.0) # this will raise
```

But this will not raise until later (because `Access` will return `nil`):

```elixir
defn my_func(test, opts \\ []) do
  opts = keyword!(opts, [epsilon: 1.0e-5])
  x + opts[:not_a_key]
end
```

```
iex> my_func(test, epsilon: 1.0e-5)
```

But the issue is not actually keyword related. The cryptic error message comes from the fact that we call `binary_type` here: https://github.com/elixir-nx/nx/blob/main/nx/lib/nx.ex#L2427

So rather than the error message indicating that you tried to use `nil` as a tensor, you get the type stuff, but not calling `binary_type` there promotes scalar types.

**Comment by josevalim** [comment]
I see! I think the best fix for now is to never call binary_type before we call tensor!.

For the main issue, if we want to warn for missing keywords, then we need to know type information, and that would be a job for the Elixir compiler.
