### ISSUE TITLE
torchx compile error

### ISSUE THREAD

**Issue by narrowtux** [elixir-nx/nx#350]
Since I can't build tensorflow on my machine, I wanted to try Nx with torch. 

I have downloaded `libtorch-cxx11-abi-shared-with-deps-1.8.0+cu111.zip` from https://pytorch.org/
and extracted it into `/usr/share`. 

Then I ran `mix deps.compile` and ran into this error:

```
tux@DESKTOP-PVMVMO6:~/projects/personal/nx_try$ LIBTORCH_DIR=/usr/share/libtorch mix deps.compile
==> torchx
Compiling: c_src/torchx.cpp
In file included from /usr/share/libtorch/include/ATen/Parallel.h:140:0,
                 from /usr/share/libtorch/include/torch/csrc/api/include/torch/utils.h:3,
                 from /usr/share/libtorch/include/torch/csrc/api/include/torch/nn/cloneable.h:5,
                 from /usr/share/libtorch/include/torch/csrc/api/include/torch/nn.h:3,
                 from /usr/share/libtorch/include/torch/csrc/api/include/torch/all.h:13,
                 from /usr/share/libtorch/include/torch/csrc/api/include/torch/torch.h:3,
                 from c_src/torchx.cpp:1:
/usr/share/libtorch/include/ATen/ParallelOpenMP.h:83:0: warning: ignoring #pragma omp parallel [-Wunknown-pragmas]
 #pragma omp parallel for if ((end - begin) >= grain_size)

In file included from c_src/torchx.cpp:4:0:
c_src/nx_nif_utils.hpp: In function ‘int nx::nif::get(ErlNifEnv*, ERL_NIF_TERM, int64_t*)’:
c_src/nx_nif_utils.hpp:93:9: error: redefinition of ‘int nx::nif::get(ErlNifEnv*, ERL_NIF_TERM, int64_t*)’
     int get(ErlNifEnv *env, ERL_NIF_TERM term, int64_t *var)
         ^~~
c_src/nx_nif_utils.hpp:88:9: note: ‘int nx::nif::get(ErlNifEnv*, ERL_NIF_TERM, long int*)’ previously defined here
     int get(ErlNifEnv *env, ERL_NIF_TERM term, long *var)
         ^~~
Makefile:36: recipe for target '/home/tux/projects/personal/nx_try/_build/dev/lib/torchx/priv/torchx.so' failed
make: *** [/home/tux/projects/personal/nx_try/_build/dev/lib/torchx/priv/torchx.so] Error 1
```

## Environment

**Elixir**
```
Erlang/OTP 23 [erts-11.1.7] [source] [64-bit] [smp:20:20] [ds:20:20:10] [async-threads:1]

Elixir 1.11.3 (compiled with Erlang/OTP 21)
```

**Ubuntu** ...
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic
```

... running in WSL 2 on **Windows 10** Version `20H2` build 19042.746

**Comment by narrowtux** [comment]
When I comment out the offending definition in torchx/c_src/nx_nif_utils.hpp:93 , I get another error:

```
Compiling 3 files (.ex)

14:04:40.909 [warn]  The on_load function for module Elixir.Torchx.NIF returned:
{:error,
 {:load_failed,
  'Failed to load NIF library: \'/home/tux/projects/personal/nx_try/_build/dev/lib/torchx/priv/torchx.so: undefined symbol: _ZTVN5torch8autograd12AutogradMetaE\''}}
```

**Comment by seanmor5** [comment]
Your compiler is treating `long` and `int64_t` as the same type. There's some platform dependent behavior with 64-bit integers as far as I'm aware. This is how it's handled in `EXLA`:

https://github.com/elixir-nx/nx/blob/main/exla/c_src/exla/exla_nif_util.h#L16

So the fix would be to try and standardize to one 64-bit type.

**Comment by narrowtux** [comment]
What do you think about that missing symbol error? Is my libtorch version too new?

**Comment by seanmor5** [comment]
I suspect libtorch is failing to dynamically link something that's not in your path. I can't speak definitively, but you might find success doing something like:

```
export LD_LIBRARY_PATH=/path/to/libtorch/lib:$LD_LIBRARY_PATH
```

**Comment by narrowtux** [comment]
Sadly, I'm getting the same error with this

**Comment by seanmor5** [comment]
Does it work if you use the CPU only version of libtorch? Can you `echo $LD_LIBRARY_PATH` and see what it looks like?

**Comment by narrowtux** [comment]
LD_LIBRARY_PATH was empty before I set it. I shall try the CPU only version, will report back

**Comment by narrowtux** [comment]
CPU only version returns this error when compiling: 

```
15:29:39.781 [warn]  The on_load function for module Elixir.Torchx.NIF returned:
{:error,
 {:load_failed,
  'Failed to load NIF library: \'/home/tux/projects/personal/nx_try/_build/dev/lib/torchx/priv/torchx.so: undefined symbol: _ZN2at6divideERKNS_6TensorES2_NSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE\''}}
```

**Comment by narrowtux** [comment]
Also different error when I get the cxx11 abi version: 

```
15:30:51.649 [warn]  The on_load function for module Elixir.Torchx.NIF returned:
{:error,
 {:load_failed,
  'Failed to load NIF library: \'/home/tux/projects/personal/nx_try/_build/dev/lib/torchx/priv/torchx.so: undefined symbol: _ZTVN5torch8autograd12AutogradMetaE\''}}
```

**Comment by josevalim** [comment]
I see some tips here: https://stackoverflow.com/questions/42451310/the-procedure-entry-point-znst7-cxx1112basic-stringicst11char-traitsicesaiceec

Can you please play with the makefile and the calls to gcc? Maybe you need a more recent gcc version too.

**Comment by narrowtux** [comment]
Thanks for googling it for me 😅 First, I tried defining the CXX env variable to /usr/bin/g++, but I still get the same error. Now I'm trying to upgrade my ubuntu to 20.04.

**Comment by narrowtux** [comment]
solved! Compiling with `clang++` did the trick. 

```bash
export LIBTORCH_DIR=/usr/share/libtorch
export CXX=/usr/bin/clang++
mix deps.compile
```

**Comment by narrowtux** [comment]
This also works in Ubuntu 18.04

**Comment by josevalim** [comment]
Hooray! :tada:
