### ISSUE TITLE
Compilation fails when running `iex -S mix` in exla directory

### ISSUE THREAD

**Issue by AlexJuca** [elixir-nx/nx#353]
ajax0xd9 in ~/Projects/opensource/nx on main> iex -S mix
Erlang/OTP 23 [erts-11.1.5] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe] [dtrace]

mkdir -p /Users/ajax0xd9/.cache/exla/tf-6af836f407f546cf2f9ab3b5fcb7a8285bda5c96/erts-11.1.5
cd /Users/ajax0xd9/.cache/exla/tf-6af836f407f546cf2f9ab3b5fcb7a8285bda5c96/erts-11.1.5 && \
        git init && \
        git remote add origin https://github.com/tensorflow/tensorflow.git && \
        git fetch --depth 1 origin 6af836f407f546cf2f9ab3b5fcb7a8285bda5c96 && \
        git checkout FETCH_HEAD
Initialized empty Git repository in /Users/ajax0xd9/.cache/exla/tf-6af836f407f546cf2f9ab3b5fcb7a8285bda5c96/erts-11.1.5/.git/
From https://github.com/tensorflow/tensorflow
 * branch              6af836f407f546cf2f9ab3b5fcb7a8285bda5c96 -> FETCH_HEAD
Note: switching to 'FETCH_HEAD'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 6af836f4 [TF:TRT] Adds ResultAnalyzer to analyze timing and numerical results of model testing.
cd /Users/ajax0xd9/.cache/exla/tf-6af836f407f546cf2f9ab3b5fcb7a8285bda5c96/erts-11.1.5 && \
        sed -e '/register_toolchains("@local_config_python\/\/:py_toolchain")/ s/^#*/#/' -i.backup WORKSPACE && \
        sed -e '/load("\/\/third_party\/py:python_configure.bzl", "python_configure")/ s/^#*/#/' -i.backup tensorflow/workspace.bzl && \
        sed -e '/native.register_toolchains("@local_execution_config_python\/\/:py_toolchain")/ s/^#*/#/' -i.backup tensorflow/workspace.bzl && \
        sed -e '/python_configure(name = "local_config_python")/ s/^#*/#/' -i.backup tensorflow/workspace.bzl
cd /Users/ajax0xd9/.cache/exla/tf-6af836f407f546cf2f9ab3b5fcb7a8285bda5c96/erts-11.1.5 && \
        bazel build --define "framework_shared_object=false" -c dbg  //tensorflow/compiler/xla/exla:libexla.so
Starting local Bazel server and connecting to it...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=0 --terminal_columns=80
INFO: Reading rc options for 'build' from /Users/ajax0xd9/.cache/exla/tf-6af836f407f546cf2f9ab3b5fcb7a8285bda5c96/erts-11.1.5/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /Users/ajax0xd9/.cache/exla/tf-6af836f407f546cf2f9ab3b5fcb7a8285bda5c96/erts-11.1.5/.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --define=tensorflow_enable_mlir_generated_gpu_kernels=0 --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_config --config=short_logs --config=v2
INFO: Found applicable config definition build:short_logs in file /Users/ajax0xd9/.cache/exla/tf-6af836f407f546cf2f9ab3b5fcb7a8285bda5c96/erts-11.1.5/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /Users/ajax0xd9/.cache/exla/tf-6af836f407f546cf2f9ab3b5fcb7a8285bda5c96/erts-11.1.5/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:macos in file /Users/ajax0xd9/.cache/exla/tf-6af836f407f546cf2f9ab3b5fcb7a8285bda5c96/erts-11.1.5/.bazelrc: --copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --define=PROTOBUF_INCLUDE_PATH=$(PREFIX)/include --cxxopt=-std=c++14 --host_cxxopt=-std=c++14
Loading: 
Loading: 0 packages loaded
Loading: 0 packages loaded
Analyzing: target //tensorflow/compiler/xla/exla:libexla.so (1 packages loaded, 0 targets configured)
Analyzing: target //tensorflow/compiler/xla/exla:libexla.so (15 packages loaded, 14 targets configured)
Analyzing: target //tensorflow/compiler/xla/exla:libexla.so (32 packages loaded, 140 targets configured)
Analyzing: target //tensorflow/compiler/xla/exla:libexla.so (48 packages loaded, 157 targets configured)
Analyzing: target //tensorflow/compiler/xla/exla:libexla.so (76 packages loaded, 628 targets configured)
Analyzing: target //tensorflow/compiler/xla/exla:libexla.so (85 packages loaded, 745 targets configured)
Analyzing: target //tensorflow/compiler/xla/exla:libexla.so (97 packages loaded, 1746 targets configured)
Analyzing: target //tensorflow/compiler/xla/exla:libexla.so (108 packages loaded, 4918 targets configured)
Analyzing: target //tensorflow/compiler/xla/exla:libexla.so (121 packages loaded, 7440 targets configured)
Analyzing: target //tensorflow/compiler/xla/exla:libexla.so (142 packages loaded, 9524 targets configured)
Analyzing: target //tensorflow/compiler/xla/exla:libexla.so (163 packages loaded, 15363 targets configured)
Analyzing: target //tensorflow/compiler/xla/exla:libexla.so (206 packages loaded, 18879 targets configured)
INFO: Analyzed target //tensorflow/compiler/xla/exla:libexla.so (214 packages loaded, 19906 targets configured).
INFO: Found 1 target...
INFO: Deleting stale sandbox base /private/var/tmp/_bazel_ajax0xd9/5aedecc54ac8a5cb3574ed1e3a4c614c/sandbox
[1 / 1,629] [Prepa] Creating runfiles tree bazel-out/darwin-dbg/bin/tensorflow/compiler/xla/exla/libexla.so.runfiles
[29 / 1,952] Executing genrule @llvm-project//llvm:llvm_config_gen; 1s local ... (4 actions, 3 running)
[98 / 3,461] Creating runfiles tree bazel-out/host/bin/tensorflow/cc/ops/list_ops_gen_cc.runfiles [for host]; 0s local ... (4 actions, 2 running)
[144 / 3,939] Compiling external/com_google_protobuf/src/google/protobuf/compiler/main.cc [for host]; 3s local ... (4 actions running)
[145 / 3,939] Compiling external/com_google_protobuf/src/google/protobuf/compiler/cpp/cpp_map_field.cc [for host]; 8s local ... (4 actions running)
ERROR: /private/var/tmp/_bazel_ajax0xd9/5aedecc54ac8a5cb3574ed1e3a4c614c/external/com_google_protobuf/BUILD:301:1: C++ compilation of rule '@com_google_protobuf//:protoc_lib' failed (Exit 1)
external/com_google_protobuf/src/google/protobuf/compiler/cpp/cpp_message.cc:1695:39: error: no member named 'kInlinedType' in 'google::protobuf::internal::FieldMetadata'
      type = internal::FieldMetadata::kInlinedType;
             ~~~~~~~~~~~~~~~~~~~~~~~~~^
external/com_google_protobuf/src/google/protobuf/compiler/cpp/cpp_message.cc:2167:41: error: no member named 'TYPE_STRING_INLINED' in namespace 'google::protobuf::internal'; did you mean 'TYPE_STRING_CORD'?
            processing_type = internal::TYPE_STRING_INLINED;
                              ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
                                        TYPE_STRING_CORD
/usr/local/include/google/protobuf/generated_message_table_driven.h:72:3: note: 'TYPE_STRING_CORD' declared here
  TYPE_STRING_CORD = 19,
  ^
external/com_google_protobuf/src/google/protobuf/compiler/cpp/cpp_message.cc:2182:41: error: no member named 'TYPE_BYTES_INLINED' in namespace 'google::protobuf::internal'; did you mean 'TYPE_BYTES_CORD'?
            processing_type = internal::TYPE_BYTES_INLINED;
                              ~~~~~~~~~~^~~~~~~~~~~~~~~~~~
                                        TYPE_BYTES_CORD
/usr/local/include/google/protobuf/generated_message_table_driven.h:74:3: note: 'TYPE_BYTES_CORD' declared here
  TYPE_BYTES_CORD = 21,
  ^
3 errors generated.
Target //tensorflow/compiler/xla/exla:libexla.so failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /Users/ajax0xd9/.cache/exla/tf-6af836f407f546cf2f9ab3b5fcb7a8285bda5c96/erts-11.1.5/tensorflow/compiler/xla/exla/BUILD:82:1 C++ compilation of rule '@com_google_protobuf//:protoc_lib' failed (Exit 1)
INFO: Elapsed time: 40.857s, Critical Path: 9.35s
INFO: 20 processes: 20 local.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
make: *** [Makefile:32: all] Error 1
** (Mix) Could not compile with "make" (exit status: 2).
You need to have gcc and make installed. Try running the
commands "gcc --version" and / or "make --version". If these programs
are not installed, you will be prompted to install them.

# Environment
Elixir
Erlang/OTP 23 [erts-11.1.5] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.11.2 (compiled with Erlang/OTP 23)

macOs Big Sur 11.2.1

**Comment by AlexJuca** [comment]
Also running mix deps.compile does nothing. It seems that the command just exits immediately after invocation.

**Comment by josevalim** [comment]
@AlexJuca is that the new Macs (M1) or old ones? In any case, the issue is on compiling tensorflow, so there isn't much we can do to help. Check the FAQ in EXLA's README or otherwise search for the error on Google/Tensorflow repos. :)

**Comment by AlexJuca** [comment]
@josevalim Alrighty.
