### ISSUE TITLE
Sigils for tensors

### ISSUE THREAD

**Issue by dannote** [elixir-nx/nx#358]
Some time ago, I decided to implement a simple library for operations on tensors, and I found that curly braces and commas are too verbose, especially in tests, for instance:

```elixir
assert Nx.tensor([
  [1.0, -1.0, 4.0],
  [1.0, 4.0, -2.0],
  [1.0, 4.0, 2.0],
  [0.0, 0.0, 0.0]
]) == q
```

So I came up with this simple macro:

```elixir
defmacro sigil_m({:<<>>, _meta, [string]}, _) do
  string
  |> split_numbers()
  |> Nx.tensor()
end

def split_numbers(string) do
  for row <- String.split(string, "\n", trim: true) do
    row
    |> String.split(" ", trim: true)
    |> Enum.map(&Code.eval_string(&1) |> elem(0))
  end
end
```

Now you can write instead:

```elixir
~m(1.0 -1.0  4.0
   1.0  4.0 -2.0
   1.0  4.0  2.0
   0.0  0.0  0.0)
```
We can make it even better by adding a modifier for transposing tensors:

```elixir
defmacro sigil_m({:<<>>, _meta, [string]}, [?t]) do
  string
  |> split_numbers()
  |> Nx.tensor()
  |> Nx.transpose()
end

iex(1)> assert ~m(-1 2 3)t == ~m(-1
...(1)>                           2
...(1)>                           3)
true
```

If you like the idea, I can create a PR.

**Comment by josevalim** [comment]
I actually like this idea, even if restricted for matrices, I can see how it is useful. I would love to hear other people's thoughts.

We should probably go only with `~M` though, especially if we don't support interpolation.

**Comment by seanmor5** [comment]
+1 to what @josevalim said. I would also be interested to see what other modifiers besides transpose could be added to extend this specifically for matrices. E.g. determinants, inverses, etc.

cc @polvalente for his thoughts and LinAlg expertise

**Comment by polvalente** [comment]
Sigils are a great idea! The things I currently miss the most for translating math formulas into Nx code in a "less programatic/more descriptive" way are basically the ones @seanmor5 cited:
  - Matrix exponent notation (e.g. `A^2 === dot(A, A)`, `A^-1 === inverse(A)`, `A^-2 === inverse(dot(A, A))`);
  - Conjugate tensor (this will be **really** helpful when we support complex numbers/expressions;
  - Transpose and [Hermitian Transpose (aka Conjugate Transpose)](https://en.wikipedia.org/wiki/Conjugate_transpose); and
  - Determinants (which actually is a feature we are still missing in Nx, although I haven't found the need for it yet);

--- 
That being said, some food for thought: 
From what I know sigils operate on the given string and as such we wouldn't be able to use them for non-literal tensors. Would it be too unconventional for an empty sigil to return a function that could be applied to a dynamically defined value? I'm thinking about something along the lines of

```elixir
# Assuming ~M[] is the sigil for constructing tensors, and we have the c option for conjugate and t for transpose like below
~M[1+i 2 3]ct == ~M[
                                    1-i
                                    2
                                    3
                                   ]
```

Now, assuming that @josevalim doesn't ban me from using Elixir ever again for suggesting this, I can see something like the following happening:
```elixir                                   
f = ~M[]ct # equivalent to fn t -> t |> Nx.conjugate() |> Nx.transpose() end
A = Nx.tensor(...)
~M[]ct.(A) # equivalent to A |> Nx.conjugate() |> Nx.transpose()
```

I tested and this is actually a possibility, and I'll leave the suggestion just so it isn't just ommited, but after looking at this for more than 5 seconds I can see it isn't my brightest idea 😅 

PS: Can sigils be macros? If so, would something like `~M[A]ct === A |> Nx.transpose() |> Nx.conjugate()` actually be feasible?

**Comment by josevalim** [comment]
> PS: Can sigils be macros? If so, would something like ~M[a]ct === a |> Nx.transpose() |> Nx.conjugate() actually be feasible?

They can be macros but the above would require them to parse Elixir source code, which may be fine. Another option is to allow interpolation:

    ~m[#{a}]ct === a |> Nx.transpose() |> Nx.conjugate()

But that looks too noisy.

**Comment by dannote** [comment]
Sorry, it was supposed to be:

```elixir
defmacro sigil_M({:<<>>, _meta, [string]}, [?t]) do
  string
  |> split_numbers()
  |> Nx.tensor()
  |> Nx.transpose()
  |> Macro.escape()
end

defmacro sigil_M({:<<>>, _meta, [string]}, _) do
  string
  |> split_numbers()
  |> Nx.tensor()
  |> Macro.escape()
end
```

**Comment by polvalente** [comment]
> > PS: Can sigils be macros? If so, would something like ~M[a]ct === a |> Nx.transpose() |> Nx.conjugate() actually be feasible?
> 
> They can be macros but the above would require them to parse Elixir source code, which may be fine. Another option is to allow interpolation:
> 
> ```
> ~m[#{a}]ct === a |> Nx.transpose() |> Nx.conjugate()
> ```
> 
> But that looks too noisy.

Yes, and too implicit. Most of this second part of my comment was just curiosity on how far sigils could go regarding this. Still, I feel that for complex numbers this might prove useful somehow
