### ISSUE TITLE
is_tensor guard

### ISSUE THREAD

**Issue by dannote** [elixir-nx/nx#359]
It might be useful to have this shortcut:

```elixir
defguard is_tensor(value) when is_struct(value, Nx.Tensor)
```

**Comment by josevalim** [comment]
For now I would prefer to go with pattern matching on %Nx.Tensor{} and, if that is not possible, fallback to is_struct. I don't see have the guard to be very useful beyond that. :) Elixir doesn't support is_xyz variants for its structs either. Thanks!
