### ISSUE TITLE
Discussion: binary comparison operators as special-forms/macros?

### ISSUE THREAD

**Issue by seancribbs** [elixir-nx/nx#361]
There already exist in `Nx.Defn.Kernel` a majority of basic arithmetic operators that are shorthand for functions in the `Nx` module. However, binary comparison operators must be called on `Nx` inside numerical functions:

Operator | Function
------------ | -------------
`==` | `Nx.equal/2`
`!=` | `Nx.not_equal/2`
`<` | `Nx.less/2`
`>` | `Nx.greater/2`
`<=` | `Nx.less_equal/2`
`>=` | `Nx.greater_equal/2`

As a motivating example, consider a Nx2 tensor representing a bounding box, where the first row is the minimum point and the second row is the maximum point. If we define a numerical function that determines whether any given point is inside the bounding box, the current way would require something like the following:

```elixir
  defn inside?(bounds, point) do
    Nx.all?(Nx.greater_equal(point, bounds[0]) and Nx.less_equal(point, bounds[1]))
  end
```

Note that binary `and` expands to/is an alias for `Nx.logical_and/2`. If we had binary comparison operators:

```elixir
  defn inside?(bounds, point) do
    Nx.all?(point >= bounds[0] and point <= bounds[1])
  end
```

### Issues to discuss

* How should booleans (`true`, `false` atoms) behave? Should they be disallowed inside numerical functions? Should they expand to the scalar `1` and `0` tensors? 
* How should comparisons behave inside `if` and `cond` expressions? Should `Nx.all?` or `Nx.any?` be required?
* Does introducing more operators have more value than highlighting the difference between numerical functions and regular Elixir functions?
* Would this introduce too much burden (in implementation, maintenance, performance) on the compilation / evaluation parts of Nx?

See also the [Twitter thread](https://twitter.com/seancribbs/status/1376346097153667079) that started this discussion.

**Comment by seanmor5** [comment]
> How should booleans (true, false atoms) behave? Should they be disallowed inside numerical functions? Should they expand to the scalar 1 and 0 tensors?

I have been using a `to_predicate` macro that looks something like:

```elixir
defmacro to_predicate(value) do
  quote do
    Nx.Defn.Kernel.transform(unquote(value), fn arg -> if arg, do: 1, else: 0 end)
  end
end
```

to accept any regular Elixir value (like true/false) inside if statements. It should be noted that any branching that uses regular Elixir terms isn't really branching at runtime but instead at expression compile time. So usage of `to_predicate` with different values results in compilation of completely different programs when a function is invoked with different parameters. But it is nice to have the extra sugar to write code that looks closer to regular Elixir code.

> How should comparisons behave inside if and cond expressions? Should Nx.all? or Nx.any? be required?

I am in favor of adding binary comparisons as element-wise operations. And then whatever error message comes assosciated with `if`/`cond` getting passed something other than a scalar, it should mention usage of `Nx.all?` and `Nx.any?`.

> Would this introduce too much burden (in implemetnation, maintenance, performance) on the compilation / evaluation parts of Nx?

I think this is a concern with respect to the first question and including `true` / `false` style if-else that gets resolved to a scalar tensor. I think there are cases where you'd have excessive recompilations which would result in some bad performance, but I haven't benchmarked. I'm actually not sure if we include any mechanism that tracks the number of compilations / recompilations taking place, but we probably should - for profiling.

**Comment by josevalim** [comment]
> I am in favor of adding binary comparisons as element-wise operations. And then whatever error message comes assosciated with if/cond getting passed something other than a scalar, it should mention usage of Nx.all? and Nx.any?.

Ah, the error message can be a good route, since I was torn between defaulting to Nx.all? or Nx.any?.

So what do you think about:

1. Make sure `and` and `or` raise a clear error message if any of the arguments are booleans (check will be Nx.Defn.Kernel)
2. Make sure `if`/`cond` raise a clear error message if any of the arguments are booleans (check will be Nx.Defn.Expr)
3. Make sure `if`/`cond` raise a clear error message if any of the arguments are non-scalars pointing to Nx.all? or Nx.any?  (check will be Nx.Defn.Expr)
4. Add comparison operators

@seancribbs thoughts?

**Comment by josevalim** [comment]
If you want to send a PR, it would be *very* welcome! :) Otherwise someone else will tackle it. :)
