### ISSUE TITLE
Add wrapping options in `Nx.to_batched_list`

### ISSUE THREAD

**Issue by seanmor5** [elixir-nx/nx#374]
In real datasets, it's common that your preferred batch size is not a multiple of the size of your dataset. In these cases it's useful to either:

1) Repeat the first n values until a complete batch is made
2) Truncate the last n values

I believe we should add an option similar to [Enum.chunk_every](https://hexdocs.pm/elixir/Enum.html#chunk_every/4) which determines what to do with the leftover values.

**Comment by josevalim** [comment]
From the EXLA perspective, we likely want to repeat. Otherwise a different batch means compiling a different executable. :)

**Comment by seanmor5** [comment]
Oh sorry, I meant we discard the last n values that don't make an even batch size, that way all batches are the same size
