### ISSUE TITLE
Create a Nx.max/1 to compute the maximal value of a tensor

### ISSUE THREAD

**Issue by rnwatanabe** [elixir-nx/nx#384]
Currently,  exists only a Nx.max/2, that computes the maximal value between the equivalent positions of two tensors.

A Nx.max/1 method would be useful to compute the maximal value of a single tensor.

A workaround is:

t[Nx.to_flat_list(Nx.argmax(t))]

Where t is  the tensor variable.

**Comment by seanmor5** [comment]
There is `Nx.reduce_max/2` that works as you've described:

```elixir
Nx.reduce_max(Nx.tensor([1, 2, 3])
```
