### ISSUE TITLE
Argsort results in segmentation fault given tensor of the same values

### ISSUE THREAD

**Issue by jonatanklosko** [elixir-nx/nx#393]
Given a tensor of repeated value (e.g. 100 zeros) `argsort` results in segfault when compiled with EXLA.

**Reproduction**

```elixir
defmodule N do
  import Nx.Defn

  @default_defn_compiler EXLA

  defn argsort(t), do: Nx.argsort(t)
end

x = Nx.broadcast(0.0, {100})
N.argsort(x)
```

**Debug output**

```
(gdb) bt
#0  0x00007f28824e500f in _Function_0.92076480_1_in_N._-fun.__defn_argsort___1-__--to_operator_4-fun-2--325.3 ()
#1  0x00007f27d83cad7c in void std::__introsort_loop<long long*, long, __gnu_cxx::__ops::_Iter_comp_iter<__xla_cpu_runtime_KeyValueSort::{lambda(long long, long long)#1}> >(long long*, __gnu_cxx::__ops::_Iter_comp_iter<__xla_cpu_runtime_KeyValueSort::{lambda(long long, long long)#1}>, long, __gnu_cxx::__ops::_Iter_comp_iter<__xla_cpu_runtime_KeyValueSort::{lambda(long long, long long)#1}>) ()
   from /home/jonatanklosko/.cache/mix/installs/elixir-1.13.0-dev-erts-12.0/89a051d0b2809c2accd8052dc9cc8a62/_build/dev/lib/exla/priv/libexla.so
#2  0x00007f27d83cc5bd in __xla_cpu_runtime_KeyValueSort ()
   from /home/jonatanklosko/.cache/mix/installs/elixir-1.13.0-dev-erts-12.0/89a051d0b2809c2accd8052dc9cc8a62/_build/dev/lib/exla/priv/libexla.so
#3  0x00007f28824e52cb in _Function_0.92076480_1_in_N._-fun.__defn_argsort___1-__.12 ()
#4  0x00007f27d80a3f22 in xla::cpu::CpuExecutable::ExecuteComputeFunction(xla::ExecutableRunOptions const*, absl::lts_2020_02_25::Span<xla::MaybeOwningDeviceMemory const>, xla::HloExecutionProfile*) ()
   from /home/jonatanklosko/.cache/mix/installs/elixir-1.13.0-dev-erts-12.0/89a051d0b2809c2accd8052dc9cc8a62/_build/dev/lib/exla/priv/libexla.so
#5  0x00007f27d80a4be1 in xla::cpu::CpuExecutable::ExecuteAsyncOnStream(xla::ServiceExecutableRunOptions const*, std::vector<xla::ExecutionInput, std::allocator<xla::ExecutionInput> >, xla::HloExecutionProfile*)::AsyncRunTask::operator()() ()
   from /home/jonatanklosko/.cache/mix/installs/elixir-1.13.0-dev-erts-12.0/89a051d0b2809c2accd8052dc9cc8a62/_build/dev/lib/exla/priv/libexla.so
#6  0x00007f27dca5b7a6 in stream_executor::host::HostStream::WorkLoop() ()
   from /home/jonatanklosko/.cache/mix/installs/elixir-1.13.0-dev-erts-12.0/89a051d0b2809c2accd8052dc9cc8a62/_build/dev/lib/exla/priv/libexla.so
#7  0x00007f27dcbda2ef in tensorflow::(anonymous namespace)::PThread::ThreadFn(void*) ()
   from /home/jonatanklosko/.cache/mix/installs/elixir-1.13.0-dev-erts-12.0/89a051d0b2809c2accd8052dc9cc8a62/_build/dev/lib/exla/priv/libexla.so
#8  0x00007f2882433609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#9  0x00007f2882002293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Observations**

* The issue is not specific to `0`, but rather to tensors of a single unique value
  * Actually it's even the case if some values are the same, for example:\
    `Nx.concatenate([Nx.broadcast(0.0, {10}), Nx.broadcast(1.0, {10})])`
* The issue doesn't affect small tensors (e.g. `{10}`)
* The issue is dimension agnostic (happens for `{20, 20, 20, 20, 20}`, does not happen for `{10, 10, 10, 10, 10}`)

I tried reproducing the issue with Jax with no luck (with`jaxlib` both latest and an older one around the same version of XLA that EXLA uses).

Maybe not related to this issue, but for the smaller tensors for which `argsort` works, the returned indices are descending, while in Jax they are ascending.

**Comment by josevalim** [comment]
> Maybe not related to this issue, but for the smaller tensors for which argsort works, the returned indices are descending, while in Jax they are ascending.

What do you mean by this? Do we have different defaults for the :comparator function?

**Comment by jonatanklosko** [comment]
> What do you mean by this? Do we have different defaults for the :comparator function?

Not even that. For tensor of 10 zeros EXLA produces:

```
#Nx.Tensor<
  s64[10]
  [9, 8, 7, 6, 5, 4, 3, 2, 1, 0]
>
```

Without EXLA the indices are ascending though.

For higher dimensions it's even more weird (10x10 zeros):

```
#Nx.Tensor<
  s64[10][10]
  [
    [9, 0, 9, 0, 9, 0, 9, 0, 9, 0],
    [8, 1, 8, 1, 8, 1, 8, 1, 8, 1],
    [7, 2, 7, 2, 7, 2, 7, 2, 7, 2],
    [6, 3, 6, 3, 6, 3, 6, 3, 6, 3],
    [5, 4, 5, 4, 5, 4, 5, 4, 5, 4],
    ...
  ]
>
```

The columns are sorted desc, asc, desc, asc, ...

This is logically correct, but this behavior is different from Jax if I didn't miss anything, so it is weird.

**Comment by josevalim** [comment]
Ah, the sorting is not stable. I will see if we can do something about it.
-- 


*José Valimhttps://dashbit.co/ <https://dashbit.co/>*

**Comment by jonatanklosko** [comment]
Ah, so perhaps Jax does some tricks to make it stable. For the record, the instability is not a problem in my case, just thought I could be somehow related, but since it's expected feel free to ignore.
