### ISSUE TITLE
Support dynamic slicing in access behaviour

### ISSUE THREAD

**Issue by seanmor5** [elixir-nx/nx#402]
In #400 we added support for basic dynamic slicing and dynamic updates via `slice` and `put_slice`. We need to adjust the access behaviour to support dynamic slicing and dynamic updates as well. For example:

```elixir
a = Nx.tensor([1, 2, 3])
a[Nx.tensor(1)]
```

Does not currently work.

**Comment by josevalim** [comment]
This is on master. :) For put_in and update_in, we have #229.
