### ISSUE TITLE
Function Nx.LinAlg.lu does not work properly

### ISSUE THREAD

**Issue by msluszniak** [elixir-nx/nx#409]
function call
```elixir
Nx.LinAlg.lu(Nx.tensor([[0, 1, 3], [0, -1, -2], [1, 1, 2]]))
```

gives PLU decomposition as given below

```elixir
{#Nx.Tensor<
   s64[3][3]
   [
     [0, 0, 1],
     [0, 1, 0],
     [1, 0, 0]
   ]
>, #Nx.Tensor<
   f32[3][3]
   [
     [1.0, 0.0, 0.0],
     [0.0, 1.0, 0.0],
     [0.0, 0.0, 1.0]
   ]
>, #Nx.Tensor<
   f32[3][3]
   [
     [1.0, 1.0, 2.0],
     [0.0, -1.0, -2.0],
     [0.0, 0.0, 3.0]
   ]
>}
```

But the product of those matrices has different determinant than original matrix (3 instead of 1).

**Comment by seanmor5** [comment]
cc @polvalente

**Comment by polvalente** [comment]
I'll take a look into this as soon as I can. Somehow the second element in the first row of the multiplication result is returning as 0 instead of 1:
```
[[ 0,  0,  3],
 [ 0, -1, -2],
 [ 1,  1,  2]]
```

This seems like an off-by-one error, but could be something else

**Comment by josevalim** [comment]
Yeah, the `p |> Nx.dot(l) |> Nx.dot(u)` is not holding on this case either. :)
