### ISSUE TITLE
Infer dimension in reshape

### ISSUE THREAD

**Issue by seanmor5** [elixir-nx/nx#411]
NumPy allows a dimension of a reshape to specified as -1 to indicate the size of the dimension will be inferred based on other dimensions. This is useful in cases where you know the size of some dimensions (e.g. feature dimensions), but don't know the size of other dimensions (e.g. number of examples in a dataset).

Adding this is trivial in Nx, and I think it's a big convenience especially in cases where maybe you're working with a batch size that changes and hard coding the batch size in your script can lead to broken code down the line.

**Comment by josevalim** [comment]
+1! We also have the option of using an atom and be more explicit about it. Thoughts?

**Comment by seanmor5** [comment]
I think using an atom is probably better, in Axon I went with `nil` to represent a "fill in the blank" but I'm open to other options as well

**Comment by josevalim** [comment]
Yeah, I think they are distinct though. Nil in Axon makes sense, because the information is absent, but here it is “computed”. Does it make sense?

**Comment by seanmor5** [comment]
@josevalim Yes that makes sense. Do you like any of these?

```elixir
Nx.reshape(t, {:infer, 3, 28, 28})
Nx.reshape(t, {:auto, 3, 28, 28})
Nx.reshape(t, {:fill, 3, 28, 28})
```

I personally like `:auto`

**Comment by josevalim** [comment]
Good call, Any of those works for me :)
