### ISSUE TITLE
Allow as_type to convert from float to integer

### ISSUE THREAD

**Issue by seanmor5** [elixir-nx/nx#419]
I think our current implementation is too restrictive. I have an implementation that ends up with `f32` tensors:

```
rows = Nx.tensor([0.45, 0.52, 0.7])
```

And I need to use them to index:

```
indices = Nx.floor(rows) |> Nx.as_type({:s, 64})
```

But because of the restriction the current implementation is impossible

**Comment by josevalim** [comment]
@seanmor5 the goal is to use Nx.round/ceil/floor/truncate for those cases. Would that be possible for you?

**Comment by seanmor5** [comment]
@josevalim My issue is that round/ceil/floor all still return `f32` and slicing checks to make sure there is an integer start index:

```
idx = Nx.tensor(1.2) |> Nx.floor()
Nx.slice(Nx.tensor([1, 2, 3]), [idx], [1])
```

```
** (ArgumentError) index must be integer type, got {:f, 32} for axis 0
    (nx 0.1.0-dev) lib/nx.ex:8021: anonymous fn/2 in Nx.to_indices/1
    (elixir 1.12.1) lib/enum.ex:3417: anonymous fn/3 in Enum.with_index/2
    (elixir 1.12.1) lib/enum.ex:1675: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir 1.12.1) lib/enum.ex:3417: Enum.with_index/2
    (nx 0.1.0-dev) lib/nx.ex:7306: Nx.slice/4
```

**Comment by josevalim** [comment]
I see!

I think we can support conversion between floats and integers, and we will document that it truncates. That's what numpy does it seems:

    np.array([1, 2, 2.2, 2.5, 2.8]).astype("int")
