### ISSUE TITLE
Performance decline with EXLA Client

### ISSUE THREAD

**Issue by seanmor5** [elixir-nx/nx#432]
There is a noticeable performance decline with the new EXLA Client when training neural networks in Axon on CPU and GPU. I am confident the culprit is: https://github.com/elixir-nx/nx/blob/main/exla/c_src/exla/exla_client.cc#L14-L28

Specifically the Relayout (which I've only encountered as necessary on TPU, but there are checks we can do to see if it's necessary on all platforms) and the additional memcpy. This can be refactored for some pretty significant performance increases. I think some good benchmarks in the future to identify these issues might be some neural network inference workloads. Measuring training time is a good heuristic, but I don't see it as being as concrete. I'm not sure though if the inference workloads should be included in this repository because they'd be much more easily written in Axon

**Comment by josevalim** [comment]
With `Mix.install/2`, we can have something like:

```elixir
Mix.install([
  {:axon, ...},
  {:nx, path: "../../nx", override: true},
  {:exla, path: "../exla"}
])
```

inside the bench directory and build an Axon model but keep it locally.
