### ISSUE TITLE
Q: Looking to hear how you interface with XLA

### ISSUE THREAD

**Issue by joelberkeley** [elixir-nx/nx#438]
I'm writing a [probabilistic modelling toolbox](https://github.com/joelberkeley/spidr) in Idris. I intend to use XLA for the backend, and see that you've done similar in exla. I'm very interested to hear how you went about that, and what your experience was of doing that, if anyone has the time.

**Comment by josevalim** [comment]
There is a XLA mailing list which may be a better discussion point: https://groups.google.com/g/xla-dev  Our initial attempt was mostly around getting a minimal example working in C/C++, and then we slowly started adding APIs around the minimal example so we could start doing things more programmatically. Perhaps going back to the commit history gives a good overview of that. :)

**Comment by josevalim** [comment]
Btw, we don't use a FFI-like lib, we need to write explicit wrappers in C and export them using a VM-specific API. Looking at Python may be a better example if you need to go the FFI route.

The other thing that we learned is that, once you need to manage multiple devices and so on, it is better to wrap around PJRT (which is meant to be Python specific but still general enough) than building your own abstractions for managing devices, streams, and so on. :)

**Comment by joelberkeley** [comment]
thanks. Could you say what you mean by "export them using a VM-specific API"?

However I do it, I may use the C wrappers you've written since I intended to do that anyway. With the wrappers, can I ask if you chose to keep the C API close to the XLA API or the Elixir API?

**Comment by josevalim** [comment]
Right, our APIs are very specific to Elixir/Erlang, so I don't think they are useful. The PJRT stuff inside XLA itself is the most generic language stuff I can think of that you should build upon of.
