### ISSUE TITLE
EXLA not compiling on ARM64 (Jetson Nano) due to bug introduced in Tensorflow for AArch64

### ISSUE THREAD

**Issue by vegabook** [elixir-nx/nx#441]
EXLA is not compiling on the Jetson Nano (Aarch64, Ubuntu 18.04) because of the following issue: 

<img width="915" alt="Untitled" src="https://user-images.githubusercontent.com/3780883/130481626-b483b0da-a294-4594-b758-1338a1cf191c.png">

Namely: _AArch64GenO0PreLegalizeGICombiner.inc: No such file or directory_

This is appears to be documented on [this Tensorflow github issue](https://github.com/tensorflow/tensorflow/issues/49136).

So it looks like this error was introduced for Aarch 64 on 9 May or so but was fixed 20 May. Can EXLA move to the new commit that resolves this Tensorflow issue please, or could you let us know how to do that ourselves? Thanks.

**Comment by josevalim** [comment]
@vegabook you can change it using this env var: https://github.com/elixir-nx/nx/blob/main/exla/Makefile#L18

Although we should keep this open until we update the bundled Tensorflow. :)

**Comment by vegabook** [comment]
@josevalim Okay great have exported that env and recompiling now. Takes 12 hours on a Jetson Nano (massive swapping) so will let you know how it went tomorrow ;-)

**Comment by zacky1972** [comment]
I also tried to build EXLA on Jetson AGX Xavier; I met the same issue to this: https://github.com/tensorflow/tensorflow/issues/49136

So, I revised `deps/xla/Makefile` like here

```
# TODO: Should this instead be a stable version source?
# e.g. instead use wget to download tagged releases
TENSORFLOW_GIT_REV ?= 919f693420e35d00c8d0a42100837ae3718f7927
This is the version 2.6.0 of TensorFlow.

**Comment by zacky1972** [comment]
Complete! Thank you.
