### ISSUE TITLE
EXLA SVD dimensions mismatch when first dimension larger than second

### ISSUE THREAD

**Issue by dognotdog** [elixir-nx/nx#444]
Doing an SVD through the EXLA backend, like so:
```elixir
defmodule MyModule do
  import Nx.Defn
  @defn_compiler EXLA
  defn svd(m, opts \\ []) do
    Nx.LinAlg.svd(m, opts)
  end
end

exla_tensor = signal_tensor  |> Nx.backend_transfer(EXLA.DeviceBackend)
{u, s, v} = MyModule.svd(exla_tensor, eps: 1.0e-9)
```

generates the following error when the first dimension is smaller than the second (in this case for a `1023x1431` matrix):
```
** (RuntimeError) internal bug! Nx.Defn expected a tensor with shape {1431} but got {1023}
    (exla 0.1.0-dev) lib/exla/defn.ex:1085: EXLA.Defn.each_buffer_to_nx/2
    (elixir 1.12.1) lib/enum.ex:1675: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir 1.12.1) lib/enum.ex:1675: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (exla 0.1.0-dev) lib/exla/defn.ex:1061: EXLA.Defn.each_buffer_to_nx/2
    (exla 0.1.0-dev) lib/exla/defn.ex:1056: EXLA.Defn.buffer_to_nx/2
```

Transposing the matrix makes the error go away, and it is generated at the end of the calculations, presumably when the output buffers are being asssembled.

I believe this was with master at https://github.com/elixir-nx/nx/commit/65c05bd2cef5317316348f200e3dfa5f7a18d56b

**Comment by seanmor5** [comment]
I'm guessing our shape rule here is wrong: https://github.com/elixir-nx/nx/blob/main/nx/lib/nx/shape.ex#L1439

@polvalente Can you look into this?

**Comment by polvalente** [comment]
Looking into it. IIRC the BinaryBackend algorithm doesn't like one of "tall and narrow" or "small and wide" matrices.
I'll see if EXLA works fine with all three cases (tall, wide and square). If it does, I'll just let BinaryBackend raise on it and refactor the shape rule :)

**Comment by dognotdog** [comment]
@polvalente not being an expert, I guess that normally, the SVD takes a lot longer on one kind of matrix as the other, as the smallest dimensions should be the "primary" since that's how many singularities you'll get anyway, and doing it the wrong way up just makes the computation a lot longer for the same results, as you'll be shuffling around zeros.

What I ended up doing is creating a wrapper that transposes the input to be right side up for the SVD, and afterwards the output to be the same as the input, but I don't know if that is problematic or not depending on the backend.

**Comment by polvalente** [comment]
> @polvalente not being an expert, I guess that normally, the SVD takes a lot longer on one kind of matrix as the other, as the smallest dimensions should be the "primary" since that's how many singularities you'll get anyway, and doing it the wrong way up just makes the computation a lot longer for the same results, as you'll be shuffling around zeros.
> 
> What I ended up doing is creating a wrapper that transposes the input to be right side up for the SVD, and afterwards the output to be the same as the input, but I don't know if that is problematic or not depending on the backend. 

@dognotdog the problem you ran into originally was a limitation of the BinaryBackend which I accidentally imposed on all backends when implementing. Basically the BinaryBackend code doesn't work yet with wide matrices, but EXLA seemed to work fine, at least in unit tests.

Taking too long for wide matrices is probably due to the same reason BinaryBackend doesn't work -- after calculations, we need to complete the V_transposed matrix with linearly independent  vectors, so that might take long. But this is just a guess based on what I ran into while implementing it.
