### ISSUE TITLE
EXLA protobuf build error after 432bc74

### ISSUE THREAD

**Issue by dognotdog** [elixir-nx/nx#465]
After, and possibly related to commit 432bc74, new error occurs trying to build EXLA through `Mix.install()`, after cleaning `mix_cache()` path. Possibly also related to change in pre-built XLA binary, but that's hard to tell as previous install of `EXLA` did not use the pre-built archive.

Local version of protobuf is `3.17.3` through `brew`.

```
...
==> xla
Compiling 2 files (.ex)
Generated xla app

20:02:10.264 [info]  Found a matching archive (xla_extension-x86_64-darwin-cpu.tar.gz), going to download it

20:02:18.564 [info]  Successfully downloaded the XLA archive
==> exla
Unpacking ~/Library/Caches/mix/installs/elixir-1.12.1-erts-12.0.2/752edd15e8d719841a204fff943b0ae9/deps/xla/cache/download/xla_extension-x86_64-darwin-cpu.tar.gz into ~/Library/Caches/mix/installs/elixir-1.12.1-erts-12.0.2/752edd15e8d719841a204fff943b0ae9/deps/exla/exla/cache
mkdir -p ~/Library/Caches/mix/installs/elixir-1.12.1-erts-12.0.2/752edd15e8d719841a204fff943b0ae9/_build/prod/lib/exla/priv
ln -sf ~/Library/Caches/mix/installs/elixir-1.12.1-erts-12.0.2/752edd15e8d719841a204fff943b0ae9/deps/exla/exla/cache/xla_extension/lib ~/Library/Caches/mix/installs/elixir-1.12.1-erts-12.0.2/752edd15e8d719841a204fff943b0ae9/_build/prod/lib/exla/priv/lib
c++ -fPIC -I/usr/local/Cellar/erlang/24.0.2/lib/erlang/erts-12.0.2/include -isystem cache/xla_extension/include -O3 -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wno-comment -shared -std=c++14 c_src/exla/exla.cc c_src/exla/exla_nif_util.cc c_src/exla/exla_client.cc -o ~/Library/Caches/mix/installs/elixir-1.12.1-erts-12.0.2/752edd15e8d719841a204fff943b0ae9/_build/prod/lib/exla/priv/libexla.so -L~/Library/Caches/mix/installs/elixir-1.12.1-erts-12.0.2/752edd15e8d719841a204fff943b0ae9/_build/prod/lib/exla/priv/lib -lxla_extension -flat_namespace -undefined suppress
In file included from c_src/exla/exla.cc:3:
In file included from c_src/exla/exla_nif_util.h:12:
cache/xla_extension/include/tensorflow/compiler/xla/xla_data.pb.h:17:2: error: This file was generated by an older version of protoc which is
#error This file was generated by an older version of protoc which is
 ^
cache/xla_extension/include/tensorflow/compiler/xla/xla_data.pb.h:18:2: error: incompatible with your Protocol Buffer headers. Please
#error incompatible with your Protocol Buffer headers. Please
 ^
cache/xla_extension/include/tensorflow/compiler/xla/xla_data.pb.h:19:2: error: regenerate this file with a newer version of protoc.
#error regenerate this file with a newer version of protoc.
 ^
...
```

Trying to build with `XLA_BUILD=true` instead to force a local build, we'll see how that goes in a few hours!

**Comment by polvalente** [comment]
@dognotdog try checking if there's a stray libexla.so in your `/priv` dir. If so, erase it. Also, nuke `_build` and `deps`

**Comment by dognotdog** [comment]
> @dognotdog try checking if there's a stray libexla.so in your `/priv` dir. If so, erase it. Also, nuke `_build` and `deps`

I nuked all of `Mix.Utils.mix_cache`, and it was from livebook (no residuals in the livebook cwd) so it was a completely clean build as far as I can tell.

**Comment by josevalim** [comment]
@dognotdog do you have protoc available locally? If so, which version it is?

**Comment by josevalim** [comment]
Also, can you please paste the contents of "cache/xla_extension/include/tensorflow/compiler/xla/xla_data.pb.h"?

**Comment by dognotdog** [comment]
So the `XLA_BUILD=true` failed with the same protobuf errors, eventually. 

Local version of protobuf is `3.17.3` through `brew` as far as I can see.

deps/exla/exla/cache/xla_extension/include/tensorflow/compiler/xla/xla_data.pb.h is here:
https://gist.github.com/dognotdog/770ac990a3c86de84483e308743a8422

**Comment by seanmor5** [comment]
This is strange as `PROTOBUF_VERSION` should be defined in `google/protobuf/port_def.inc` which should be packaged and included in the XLA tarball. I ran into this error myself a few times and I think it was because my existing installation of the protobuf headers was conflicting with those packaged inside the tarball. Can you try something like what's described here: https://stackoverflow.com/questions/19852199/view-default-include-path-of-c-headers-in-mac-os-x-by-gcc-v

To list your include paths and see if you may have multiple versions of `port_def.inc` present. You can also try to nuke your protobuf compiler install completely and build without it present to see if it fixes the issue. AFAIK protoc is no longer necessary to build Nx/EXLA.

**Comment by dognotdog** [comment]
@seanmor5 good catch! `brew unlink protobuf`, eg. removing protobuf from the path, solved that problem!

**Comment by josevalim** [comment]
AMAZING. I will add a note to the README.
