### ISSUE TITLE
torchx: libtorch 1.8 now required, but only 1.9 binaries available for Mac

### ISSUE THREAD

**Issue by dognotdog** [elixir-nx/nx#468]
See
https://github.com/elixir-nx/nx/commit/432bc74839f6237abefb02a4135c0dd852f95c7e#r56752301

the official libtorch site does not provide 1.8 `LTS` builds for Mac, currently only `stable` with 1.9, and the above changes causes the build to thus stop working. 

Is libtorch 1.9 problematic for torchx?

**Comment by josevalim** [comment]
@dognotdog I have removed the check since our plan is to download it for you but keep in mind torchx is not in a usable state at the moment, it is very limited. :)
