### ISSUE TITLE
Nx.LinAlg, Nx.BinaryBackend.triangular_solve B-argument shape mismatch

### ISSUE THREAD

**Issue by dognotdog** [elixir-nx/nx#473]
In `Nx.BinaryBackend.triangular_solve`, and `Nx.BinaryBackend.Matrix.ts` the shape checks seem out of whack.

It seems like the valid dimensions for A should be `{n,n}`, and B should be `{n,m}`, including `m = 1` or `{n}` for one-dimensional tensors.

The shape check in ~`Nx.BinaryBackend.triangular_solve`~`Nx.LinAlg.triangular_solve` does not reflect this, and even when fixing that, it seems like `Nx.BinaryBackend.Matrix.ts` makes assumptions about B being one-dimensional, not even accepting `{n,1}` tensors.

To check I'm not completely off my rocker, using the `EXLA` backend seems to work in [this test](https://gist.github.com/dognotdog/01e6e2a38efbdef06d9a545f04618b63), with the results of the attempted regression matching the inputs, but just doing it with the `BinaryBackend` runs into shape mismatch related errors.

My naive attempt at fixing it has not been successful, as it hasn't been immediately obvious in `do_ts` how to make it do the right thing for `{n,m}` B arguments. 

EDIT: see 4628f5a74d9d8846738acf19c560b0f65dd45bfe to make snippet work with EXLA, without this fix neither backend works!

**Comment by polvalente** [comment]
@dognotdog I can work on this :)

The actual implementation for `triangular_solve` ended up being a little more convoluted than it should be. Perhaps this is an opportunity to refactor it.

**Comment by polvalente** [comment]
@dognotdog If there are still any issues with the functionality, let us know! I believe you can still comment here on the issue even after it's closed

**Comment by dognotdog** [comment]
@polvalente thanks, I've not gotten around to setting everything up to run on BinaryBackend instead of EXLA, but I'll comment when I get to it!
