### ISSUE TITLE
Add cumulative reduction functions

### ISSUE THREAD

**Issue by seanmor5** [elixir-nx/nx#485]
This discussion came up in the Elixir slack. I think we should add cumulative reductions to the Nx API, namely:

- [ ] cumsum
- [ ] cumprod
- [ ] cummin
- [ ] cummax

Most backends will have a more specific, optimized implementation than what we can write with the current API. We can implement them in XLA using `reduce_window` - this will not work in Torchx obviously.

**Comment by polvalente** [comment]
@seanmor5 perhaps we could have `cumulative(tensor, opts)`, in which one of the opts is an atom for the operation. This way all main operations could be defined over time without the need to have a compile-time check/conversion like we have for Nx.map

**Comment by jonatanklosko** [comment]
Just in case someone is already desperate for cumulative sum on 1d tensor, here's what I did :)

<details>
  <summary>Code</summary>

```elixir
@doc """
Returns the cumulative sum of elements in the given
1-dimensional tensor.

## Examples
    
    iex> MeowNx.Utils.cumulative_sum(Nx.tensor([1, 2, 3, 4]))
    #Nx.Tensor<
      s64[4]
      [1, 3, 6, 10]
    >
"""
defn cumulative_sum(t) do
  {n} = Nx.shape(t)
  Nx.dot(lower_triangular(n), t)
end

defnp lower_triangular(n) do
  Nx.less_equal(
    Nx.iota({n, n}, axis: 1),
    Nx.iota({n, n}, axis: 0)
  )
end
```

</details>

**Comment by josevalim** [comment]
@polvalente I am not a big fan of the atom approach because it is worse in terms of API discovery, backend callbacks, etc. And if we add new atoms, it is hard to express that at compile time at the moment (due to the lack of types).

**Comment by josevalim** [comment]
This is the code according to @seanmor5:

```elixir
defn cumsum(tensor, opts \\ []) do
  axis = opts[:axis]
  n = elem(Nx.shape(val), axis)
  padding_config =
    for i <- 0..(Nx.rank(val) - 1) do
      if i == axis, do: {n - 1, 0}, else: {0, 0}
    end
  strides = List.duplicate(1, Nx.rank(val))
  window_shape =
    List.duplicate(1, Nx.rank(val))
    |> List.to_tuple()
    |> put_elem(axis, n)
  Nx.window_sum(val, window_shape, strides: strides, padding: padding_config)
end
```

**Comment by jonatanklosko** [comment]
Having optional callbacks, we could have those as optional and use the respective `window_*` operations for the default implementation?

A working version of `cumsum` [here](https://github.com/jonatanklosko/meow/blob/bb13f929861fcc97dbd375564102a470f2d7c684/lib/meow/utils.ex#L90-L138).

**Comment by josevalim** [comment]
I don't think we need optional callbacks in this case because it still boils down to a single operation.

**Comment by josevalim** [comment]
In any case, pull request for those operations would be very welcome!

**Comment by jonatanklosko** [comment]
I was referring to this:

> Most backends will have a more specific, optimized implementation than what we can write with the current API.

But we can always add the optional callbacks to the backend later.

**Comment by josevalim** [comment]
Right, I am thinking that may not be the case. We will have to benchmark to be sure. :) But yeah, they can come later!
