### ISSUE TITLE
Support hardware acceleration on Apple Silicon

### ISSUE THREAD

**Issue by dannote** [elixir-nx/nx#490]
As I mentioned earlier (elixir-nx/xla#8), Apple claimes that TensorFlow now supports hardware acceleration on M1 via PluggableDevice.

The benchmarks [look impressive](https://blog.tensorflow.org/2020/11/accelerating-tensorflow-performance-on-mac.html) so it would be great to add this option to EXLA:

![MacBook Pro 1](https://user-images.githubusercontent.com/2206583/134935867-2365be42-26d2-47e1-ba5d-b1369689a49f.png)

Here is my plan:

- Extract pre-built TensorFlow plugin (`libmetal_plugin.dylib`) from Python [package](https://pypi.org/project/tensorflow-metal/) provided by Apple (it's built for 2.5 but the ABI should be stable)
- Load PluggableDevice library via NIF
- Build `StreamExecutor` for Metal platform

So far I [have managed](https://github.com/dannote/nx/commit/9b9800a346211ef4bb6020d4ceb3ca2925d9507b) to load and initialize Apple's TensorFlow plugin:

```
Compiling 15 files (.ex)
Generated exla app
Init Plugin
Init Graph Optimizer
Init Kernel
library: ['/physical_device:GPU:0', '/physical_device:CPU:0']
```

(The GPU is recognized correctly, but I'm currently stuck at `could not find registered compiler for platform METAL -- check target linkage`)

What's your opinion on it?

**Comment by josevalim** [comment]
This would be awesome to have supported. For now, don't worry about the APIs and stuff, focus on making it work and then we can discuss the proper endpoints later. :) About the error, I am not sure what could be the root cause though. Who is raising that? Is it Tensorflow? Btw, we are all on the #machiinelearning channel of the Erlang Ecosystem Foundation Slack. You can create [a free account here](https://erlef.org/) and once you do so, you can request a Slack link. It is totally optional though. :)

**Comment by dannote** [comment]
>  For now, don't worry about the APIs and stuff, focus on making it work and then we can discuss the proper endpoints later.

Okay, great!

> Who is raising that? Is it Tensorflow?

Yes, the error is raised [here](https://github.com/tensorflow/tensorflow/blob/ea2a15b0466cbb96a311bc1511561943eb929517/tensorflow/compiler/xla/service/compiler.cc#L112). I'll try to figure out the cause myself, though would be glad to know if someone has experienced something like that.

> we are all on the #machiinelearning channel of the Erlang Ecosystem Foundation Slack

Then see you soon :)

**Comment by josevalim** [comment]
@dannote what does `EXLA.Client.get_supported_platforms` return for you?

**Comment by dannote** [comment]
It returns:

```elixir
{:ok, %{'Host' => 8, 'Interpreter' => 1}}
```

But when I tried to initialize client with `EXLA.NIF.get_gpu_client/2`, it said:
```
** (RuntimeError) Could not find registered platform with name: "cuda". Available platform names are: Interpreter Host METAL
```

**Comment by seanmor5** [comment]
Unfortunately I don't think this is going to be possible. You'll notice `get_supported_platforms` doesn't list `METAL` as a supported platform, but it's listed as an available Stream Executor platform. This is because XLA only lists platforms with a [supported XLA compiler](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/xla/service/platform_util.cc#L72). 

It is possible to write a [new XLA backend](https://www.tensorflow.org/xla/developing_new_backend), but I'm not sure exactly how feasible that is with what API's Apple exposes. One option is to open an issue/discussion in JAX to see if there are any plans or projects which use XLA to target the M1 GPU.

**Comment by seanmor5** [comment]
If the M1 already has a supported LLVM backend, then it shouldn't be too difficult to get a trivial example up and running. If not, I think the process moving forward would be much more difficult

**Comment by dannote** [comment]
@seanmor5 Thank you for your reply!

[This dump](https://gist.github.com/dannote/552a2a9ba4eeaa07bca33925c5a00d07) might give you a clue what is Metal plugin capable of (`nm -gU libmetal_plugin.dylib | grep metal_plugin`).

> One option is to open an issue/discussion in JAX to see if there are any plans or projects which use XLA to target the M1 GPU.

Good idea, I'll do that.

I think Apple will update this plugin after the Monterey release, so we'll see.

**Comment by dannote** [comment]
@josevalim Sorry for the offtopic, but I signed up at [erlef.org](https://erlef.org/slack-invite/erlanger) and didn't find that channel. Is `erlanger.slack.com` the right server?

**Comment by josevalim** [comment]
Go here: https://erlef.org/members/profile and then go to "Erlef Slack invite". It is not erlanger.slack.com. :)

**Comment by josevalim** [comment]
@dannote if you open up an issue somewhere in Jax, please drop it here so we can follow the discussion. Thank you!

**Comment by zacky1972** [comment]
I have an M1 Mac, so I'd like to contribute this issue! 
What should I do, firstly?

**Comment by josevalim** [comment]
This apparently has been addressed.

**Comment by chaychoong** [comment]
> This apparently has been addressed.

Hey @josevalim, I'm wondering if this means that hardware acceleration on M1 is technically possible by setting an `XLA_TARGET`? I tried looking for clues outside of this thread but I'm a little stuck.

**Comment by josevalim** [comment]
I probably misspoke. The best way to summarize it is: it has to be addressed upstream. Until that happens, there is not much for us to do. Afaik, that has not happened yet.

**Comment by nutheory** [comment]
Has anyone seen this yet? ... https://developer.apple.com/metal/jax/

**Comment by josevalim** [comment]
Yes, we plan to explore integrating with it sooner than later. :)

**Comment by dannote** [comment]
@nutheory yes, I've seen the issue was closed and going to take a closer look soon

**Comment by lostbean** [comment]
@dannote @josevalim is there any updates on this front? I'm willing to invest some time to push this through if more hands are needed.
