### ISSUE TITLE
Add missing implementations in Torchx.Backend

### ISSUE THREAD

**Issue by polvalente** [elixir-nx/nx#504]
There are some missing operations in Torchx.Backend. For some of the following there are suggestions on where to look in the Libtorch API. It is best to look for the function in the [C++ API](https://pytorch.org/cppdocs/api/library_root.html) and then to see how it works in the [Python docs](https://pytorch.org/docs/stable/index.html).

- [x] window_scatter_min
- [x] window_scatter_max
- [x] window_sum
- [x] window_product
- [x] window_min
- [x] window_max
- [x] triangular_solve (torch::triangular_solve)
- [x] svd (torch::linalg::svd)
- [x] sort (torch::sort)
- [x] solve (torch::solve)
- [x] select (torch::select)
- [x] reduce_min
- [x] reduce_max
- [x] reverse
- [x] put_slice
- [x] product (torch::prod)
- [x] population_count
- [x] pad
- [x] lu (torch::_lu_with_info + torch::lu_unpack)
- [x] indexed_add (torch::scatter_add)
- [x] count_leading_zeros
- [x] conv (torch::conv1d/2d and 3d)
- [x] clip (torch::clip)
- [x] cbrt
- [x] bitcast
- [x] backend_copy
- [x] any? (torch::any)

**Comment by seanmor5** [comment]
@polvalente Just dropping in to point out that `Nx.conv` parity will be a bit more in depth than just `torch::convolution` since LibTorch provides a separate implementation for each type of conv (1d, 2d, 3d).

**Comment by stefkohub** [comment]
If I start adding the convolutional layer, which are the functions I will need to integrate? I cannot find torch::convolution but torch::conv1d, 2d and 3d here:
[https://pytorch.org/cppdocs/api/unabridged_api.html?highlight=torch%20convolution](https://pytorch.org/cppdocs/api/unabridged_api.html?highlight=torch%20convolution)

Thank you.

**Comment by polvalente** [comment]
> If I start adding the convolutional layer, which are the functions I will need to integrate? I cannot find torch::convolution but torch::conv1d, 2d and 3d here:
> [https://pytorch.org/cppdocs/api/unabridged_api.html?highlight=torch%20convolution](https://pytorch.org/cppdocs/api/unabridged_api.html?highlight=torch%20convolution)
> 
> Thank you.

Edited the issue accordingly!
