### ISSUE TITLE
Add default_compiler functions in Nx.Defn and relevant application config

### ISSUE THREAD

**Issue by josevalim** [elixir-nx/nx#506]
The only question is if and how it should interact with `Nx.Defn.default_compiler`. Should we remove the module configuration? Should we keep them distinct?

**Comment by polvalente** [comment]
Perhaps we could have `use Nx.Defn, kw_args`, which would enable us to have global defaults which could be overriden in certain places if needed.

**Comment by josevalim** [comment]
I am thinking we should just remove @defn_compiler and focus on Nx.Defn.default_compiler instead (and the relevant Nx.Defn.jit options). /cc @seanmor5

**Comment by seanmor5** [comment]
I agree, in Axon I have found myself using `Nx.Defn.jit` more often then the module attributes. And in Livebook the `Nx.Defn.default_compiler` makes more sense as well
