### ISSUE TITLE
Add Nx.diag implementation

### ISSUE THREAD

**Issue by polvalente** [elixir-nx/nx#517]
This function should mimic [numpy diag](https://numpy.org/doc/stable/reference/generated/numpy.diag.html), returning the diagonal from a 2D tensor, or building a 2D diagonal tensor from a 1D tensor

**Comment by polvalente** [comment]
I would add this as Nx.diag to make it pair up with Nx.eye (instead of diagonal and identity).

They fall in similar use cases of "let's build a tensor" so I think it's fine to add it to Nx instead of Nx.LinAlg

**Comment by josevalim** [comment]
@Benjamin-Philip yes, please go ahead exploring those ideas. We can discuss the API as we move forward. :)
