### ISSUE TITLE
Proposal: Nx.length

### ISSUE THREAD

**Issue by Benjamin-Philip** [elixir-nx/nx#538]
I propose we write a function to calculate the length (the number of elements) of a tensor.

**Comment by polvalente** [comment]
Nx.size does that: https://github.com/elixir-nx/nx/blob/bda8827d54c533f960616f812eae6b2561df1901/nx/lib/nx.ex#L2470

Thanks for the proposal, though!

**Comment by Benjamin-Philip** [comment]
@polvalente  I think you misunderstood... (or I did a poor job of explaining) 

See for example:

```elixir
iex(5)> Nx.iota {3, 3}          
#Nx.Tensor<
  s64[3][3]
  [
    [0, 1, 2],
    [3, 4, 5],
    [6, 7, 8]
  ]
>
```

Here the length of the tensor is 3 because the number of elements in the first dimension is 3.

If I do Nx.size:

```elixir
iex(7)> Nx.iota({3, 3}) |> Nx.size 
9
iex(8)> Nx.size {3, 3}
9
```

I get 9 which is the total number of values in the tensor including all
the nested tensors.

Granted, what I am suggesting is purely a convenience function for

```elixir
tensor
|> Nx.shape
|> elem(0)
```

but I think it might come quite handy.

Re-opening in case this is worth adding to Nx.

**Comment by seanmor5** [comment]
Rather than length maybe this could be `axis_size` or something similar. NumPy also has `alen` which returns the first axis length

**Comment by polvalente** [comment]
> @polvalente  I think you misunderstood... (or I did a poor job of explaining) 
> 
> See for example:
> 
> ```elixir
> iex(5)> Nx.iota {3, 3}          
> #Nx.Tensor<
>   s64[3][3]
>   [
>     [0, 1, 2],
>     [3, 4, 5],
>     [6, 7, 8]
>   ]
> >
> ```
> 
> Here the length of the tensor is 3 because the number of elements in the first dimension is 3.
> 
> If I do Nx.size:
> 
> ```elixir
> iex(7)> Nx.iota({3, 3}) |> Nx.size 
> 9
> iex(8)> Nx.size {3, 3}
> 9
> ```
> 
> I get 9 which is the total number of values in the tensor including all
> the nested tensors.
> 
> Granted, what I am suggesting is purely a convenience function for
> 
> ```elixir
> tensor
> |> Nx.shape
> |> elem(0)
> ```
> 
> but I think it might come quite handy.
> 
> Please reopen in case this is worth adding to Nx.

@Benjamin-Philip thanks for the added example. I'm not sure if we should add this (or even if there already is a function for this, I'd have to look through).

I've reopened the issue for further discussion

**Comment by Benjamin-Philip** [comment]
> Rather than length maybe this could be axis_size or something similar. NumPy also has alen which returns the first axis length

That sounds like a good idea. Might be less ambiguous.

**Comment by josevalim** [comment]
Yeah, I am 👎 . elem/2 and pattern matching are existing ways of getting this information.

increasing the api has a cost in terms of traversability and added vocabulary and the cost here does not seem to be worth it. :)

**Comment by polvalente** [comment]
Perhaps there could be an argument for the desired axis. By default it would be the first one, but perhaps there are use cases for getting an inner axis' size

**Comment by Benjamin-Philip** [comment]
> Yeah, I am 👎 . elem/2 and pattern matching are existing ways of getting this information.
> 
> increasing the api has a cost in terms of traversability and added vocabulary and the cost here does not seem to be worth it. :)

Yeah, I see what you mean.

It's hard to keep the api concise but convenient at the same time.

So, should we close this or are we going add this as an option to Nx.size?

**Comment by josevalim** [comment]
Let’s go ahead and close this unless there is a clear use case this is necessary. :)
