### ISSUE TITLE
Generalize and split Nx.diag in two

### ISSUE THREAD

**Issue by josevalim** [elixir-nx/nx#542]
The current `Nx.diag/2` is a great starting point but, if we want to support vectorization, such as vmap, we need to allow extra a diagonal from any `rank >= 1`  tensor and build diagonal matrices from any `rank > 1` tensor.

We may not need to generalize immediately but we should probably split sooner than later. The big question is what we should call these operations. Given we are increasing and decreasing the rank, my suggestion would be to call it `gather_diagonal` (to go from a matrix to a vector) and `scatter_diagonal` (to go from a vector to a matrix).

Thoughts @polvalente and @seanmor5?

**Comment by polvalente** [comment]
@josevalim I think that `gather` and `scatter` are good prefixes, although I might be biased because I already have the mental image of what a `gather` and what a `scatter` is.

As we had discussed, `to_diagonal` and `from_diagonal` could be confusing.
WDYT about `build_diagonal` and `extract_diagonal` for `scatter` and `gather` respectively? build/extract seem more layman's terms than scatter/gather

**Comment by josevalim** [comment]
Here are other suggestions:

  * `as_diagonal` - Returns a vector as a diagonal matrix
  * `take_diagonal` - Takes the diagonal of a matrix

I think those should not be ambiguous. Thoughts?

**Comment by seanmor5** [comment]
Just a quick question: if we we're to implement batching on only primitives like with gradients, how would the diag implementation look (assuming we changed some of the shape logic to support batched dims)?

I think I am still +1 on generalizing/splitting the diagonal operation and differentiating between taking a diagonal from an input or creating a diagonal matrix/tensor. +1 for `as_diagonal` and `take_diagonal`.

**Comment by polvalente** [comment]
@seanmor5 I'm not sure if I quite follow the first part of the question

From what I was thinking, `take_diagonal` would receive a tensor (for simplicity, square in the inner dims) in the shape {..., N, N} and yield a tensor {..., N}. The grad would be akin to the grad for `gather`, in which the grads corresponding to each element would be positioned in the corresponding indices.

And for `as_diagonal`, it would be akin to `scatter-add`, in which the resulting {..., N, N} tensor's grad would be zero except for the diagonal elements.

Ideally, `take_diagonal` could be implemented in terms of `gather` and `as_diagonal`, in terms of `scatter_add`.

---

As for naming, I'm comfortable with `take_diagonal` and `as_diagonal`

**Comment by seanmor5** [comment]
Sorry, what I meant to say was I am failing to see how diag wouldn't work (with some minor shape check changes) with batching rules. We would implement batch rules for multiply, take, etc. and then not have to worry about the batch rule for this.

I am still in favor of the proposed split functionality

**Comment by polvalente** [comment]
> Sorry, what I meant to say was I am failing to see how diag wouldn't work (with some minor shape check changes) with batching rules. We would implement batch rules for multiply, take, etc. and then not have to worry about the batch rule for this.
> 
> I am still in favor of the proposed split functionality 

Oh, right! Yeah, I think we're on the same page regarding this then!

**Comment by Benjamin-Philip** [comment]
How about `extract_diagonal` and `construct_diagonal`?

**Comment by josevalim** [comment]
What about `make_diagonal` and `take_diagonal`? To read as "make a diagonal matrix from a vector" and "take a vector from a diagonal matrix".

**Comment by polvalente** [comment]
@Benjamin-Philip we though about those, but we wanted to use some prefixes which were already used somewhere in the API if possible.

@josevalim `make_diagonal` seems better than `take_diagonal`. I don't think that there'll be any confusion with "diagonalize matrix", especially since we're not in the Nx.LinAlg namespace

**Comment by josevalim** [comment]
I meant make_diagonal and take_diagonal, as opposites. The fact you took them as the same make me think it is not a good name then :D

**Comment by polvalente** [comment]
> I meant make_diagonal and take_diagonal, as opposites. The fact you took them as the same make me think it is not a good name then :D

@josevalim I mistyped! I mean better than `as_diagonal`! There wasn't any confusion in my part other than  mistyping haha

**Comment by Benjamin-Philip** [comment]
`make_diagonal` seems good to me.

**Comment by josevalim** [comment]
@Benjamin-Philip would you like to send a PR to split them apart them? Then we would also love to accept a PR to generalize them. :)

**Comment by Benjamin-Philip** [comment]
Cool. Working on it..

**Comment by Benjamin-Philip** [comment]
@josevalim, @polvalente, @seanmor5 , Are there any plans of supporting an offset for make_diagonal?

**Comment by josevalim** [comment]
@Benjamin-Philip we can support it too, it is your call. :)

**Comment by Benjamin-Philip** [comment]
Ok, I plan to support it.

**Comment by Benjamin-Philip** [comment]
@josevalim, don't we also have to generalize the 2 functions? My PR only split diag into 2.

**Comment by josevalim** [comment]
We can generalize it in the future whenever needed!--


*José Valimhttps://dashbit.co/ <https://dashbit.co/>*
