### ISSUE TITLE
Add option to persist tensors to disk

### ISSUE THREAD

**Issue by josevalim** [elixir-nx/nx#550]
Currently we can use :erlang.term_to_binary/binary_to_term to do bulk of the work. The only issue is endianness. So we would also need to store the endianness and if the endianness differ, we traverse the tensors remapping them.

**Comment by seanmor5** [comment]
As a very simple option we can do something like:

```elixir
def save(tensor, opts \\ []) do
  term = {System.endianness(), tensor}
  ...term to binary and write to file...
end

def load(file, opts \\ []) do
  binary = ...load file...
  {endianness, tensor} = :erlang.binary_to_term(binary)
end
```

I think it would also be nice to have conveniences for serializing multiple tensors, containers (especially for model parameters in Axon), maybe adding the ability to compress files (with gzip or something else), and making it easy to stream a file which contains multiple tensors. 

Any thoughts?

**Comment by josevalim** [comment]
Exactly. term_to_binary already compresses and the new Nx.Container makes it easy to serialize containers. So it is mostly a matter of implementing this. The only downside of using `term_to_binary` is that it is Erlang VM specific but I guess if someone needs other types of serialization, they can pick something else. :)

**Comment by polvalente** [comment]
I think we should add a header line which contains at least the version for the storage format. For now we can only think of storing the endianess, but perhaps in the future something else might come up.

Either that, or we can store a map instead of a tuple, and then we can always have `version` and `data` keys, i. Which version is either a string or an integer, and data is the term_to_binary-encoded data

**Comment by josevalim** [comment]
`{1, endianess, data_structure}` is my vote.

**Comment by polvalente** [comment]
> `{1, endianess, data_structure}` is my vote.

@josevalim How would we decode it if we need any more metadata in the future?

Would we pattern match on longer tuples + hard matching the version?

**Comment by josevalim** [comment]
I usually do `elem(tuple, 0)` but keeping a map would be clearer, yeah.

**Comment by polvalente** [comment]
> I usually do `elem(tuple, 0)` but keeping a map would be clearer, yeah.

`elem` sounds fine to me. We just need to document the storage format somewhere. So storing a tuple sounds ok :)

**Comment by fluffynukeit** [comment]
Hi.  I'm new to the Elixir ecosystem.  I'm interested in Nx not for its machine learning potential, but just its fast numerics akin to Numpy.  I am dealing with experimental data, and such data often takes the form of a time series.  For time series data, there are lots of compression techniques that are demonstrably better than dictionary-based compression.  [Here is a good article detailing some.](https://blog.timescale.com/blog/time-series-compression-algorithms-explained/)  An excerpt:

> We have found this type-specific compression quite powerful: In addition to higher compressibility, some of the techniques like XOR-based compression and Delta-of-delta can be up to 40x faster than LZ-based compression during decoding, leading to faster queries.

So I hope that whatever form Nx serialization takes that the built-in compression scheme in `term_to_binary` can be avoided or disabled entirely.  It looks to me that #574 achieves this by passing `opts` to `term_to_binary`, which can ensure that compression is disabled.

However, when studying `term_to_binary` to see how it worked, I did come across this warning in the [docs](https://www.erlang.org/doc/man/erlang.html#term_to_binary-2):

> Option deterministic (introduced in OTP 24.1) can be used to ensure that within the same major release of Erlang/OTP, the same encoded representation is returned for the same term. **There is still no guarantee that the encoded representation remains the same between major releases of Erlang/OTP.**

My argument given the above is that `term_to_binary` cannot be a viable disk serialization format for Nx or any other library if there is no guarantee that it is compatible between major releases of OTP.  An org simply cannot take on the risk that upgrading their version of Elixir will render all their saved data incompatible.

**Comment by josevalim** [comment]
Hi @fluffynukeit!

> My argument given the above is that term_to_binary cannot be a viable disk serialization format for Nx or any other library if there is no guarantee that it is compatible between major releases of OTP. 

To clarify, they are not saying it is incompatible. They are saying it is not guaranteed to be the same. For example, they may change comprehension algorithms, find a more efficient representation to encode some data structure, etc. As an example, the minor version 0, which is 13+ years old at this point, is still supported!

**Comment by josevalim** [comment]
I think the question we need to answer is: is `term_to_binary` good enough for a simple persistence? Either way whatever we pick shouldn't exclude us from having other more efficient persistence modes from libraries or elsewhere.
