### ISSUE TITLE
Add defn hooks

### ISSUE THREAD

**Issue by josevalim** [elixir-nx/nx#556]
This is a proposal for adding hooks to defn. Hooks allow custom
functions to run with values from the device.

In order to explain this functionality, please read the docs for the
upcoming `hook/3` function below:

---

    def hook(tensor_expression, name, function)

Defines a hook.

Hooks are a mechanism to execute an anonymous function for
side-effects with runtime tensor values.

Let's see an example:

    defmodule Hooks do
      import Nx.Defn

      defn add_and_mult(a, b) do
        add = hook(a + b, fn tensor -> IO.inspect({:add, tensor}) end)
        mult = hook(a * b, fn tensor -> IO.inspect({:mult, tensor}) end)
        {add, mult}
      end
    end

The `defn` above defines two hooks, one is called with the
value of `a + b` and another with `a * b`. Once you invoke
the function above, you should see this printed:

    Hooks.add_and_mult(2, 3)
    {:add, #Nx.Tensor<
       s64
       5
    >}
    {:mult, #Nx.Tensor<
       s64
       6
    >}

In other words, the `hook` function accepts a tensor
expression as argument and it will invoke a custom
function with a tensor value at runtime. `hook` returns
the result of the given expression.

Note **you must return the result of the `hook` call**.
For example, the code below won't inspect the `:add`
tuple, because the hook is not returned from `defn`:

    defn add_and_mult(a, b) do
      _add = hook(a + b, fn tensor -> IO.inspect({:add, tensor}) end)
      mult = hook(a * b, fn tensor -> IO.inspect({:mult, tensor}) end)
      mult
    end

We will learn how to hook into a value that is not part
of the result in the "Hooks and tokens" section.

## Named hooks

It is possible to give names to the hooks. This allows them
to be defined or overridden by calling `Nx.Defn.jit/3` or
`Nx.Defn.stream/3`. Let's see an example:

    defmodule Hooks do
      import Nx.Defn

      defn add_and_mult(a, b) do
        add = hook(a + b, :hooks_add)
        mult = hook(a * b, :hooks_mult)
        {add, mult}
      end
    end

Now you can pass the hook as argument as follows:
    
    hooks = %{
      hooks_add: fn tensor ->
        IO.inspect {:add, tensor}
      end
    }

    args = [Nx.tensor(2), Nx.tensor(3)]
    Nx.Defn.jit(&Hooks.add_and_mult/2, args, hooks: hooks)

> **Important!** We recommend to prefix your hook names
> by the name of your library and the custom function,
> to avoid conflicts.

If a named hook is not given, compilers can optimize
that away and not transfer the tensor from the device
in the first place.

You can also mix named hooks with callbacks:

    defn add_and_mult(a, b) do
      add = hook(a + b, :hooks_add, fn tensor -> IO.inspect({:add, tensor}) end)
      mult = hook(a * b, :hooks_mult, fn tensor -> IO.inspect({:mult, tensor}) end)
      {add, mult}
    end

If a hook with the same name is given to `Nx.Defn.jit/3`
or `Nx.Defn.stream/3`, then it will override the default
callback.

## Hooks and tokens

So far, we have always return the result of the `hook`
call. However, what happens if the values we want to
hook are not part of the return value, such as below?

    defn add_and_mult(a, b) do
      _add = hook(a + b, :hooks_add, &IO.inspect({:add, &1}))
      mult = hook(a * b, :hooks_mult, &IO.inspect({:mult, &1}))
      mult
    end

In such cases, you must use tokens. Tokens are used to
create an ordering over hooks, ensuring hooks execute
in a certain order:

    defn add_and_mult(a, b) do
      token = create_token()
      {token, _add} = hook_token(token, a + b, :hooks_add, &IO.inspect({:add, &1}))
      {token, mult} = hook_token(token, a * b, :hooks_mult, &IO.inspect({:mult, &1}))
      attach_token(token, mult)
    end    

The example above creates a token and uses `hook_token/4`
to create hooks attached to said token. By using a token,
we guarantee that those hooks will be invoked in the given
order. Then, at the end of the function, we attach the token
(and the hooks associated with it) to the result `mult`.

Note you must attach the token at the end, otherwise the hooks
will be lost. In fact, the `hook/3` function is implemented like
this:

    def hook(tensor_expr, name, function) do
      {token, result} = hook_token(create_token(), tensor_expr, name, function)
      attach_token(token, result)
    end

**Comment by seanmor5** [comment]
I like this proposal, and I can't see any limitations just yet with respect to how PyTorch does hooks and how Jax does host callbacks. To be clear, the signature of a hook is `(tensor_or_container) :: (tensor_or_container)` correct? So hooks can edit an intermediate runtime value?

**Comment by josevalim** [comment]
Yes, it can be a container!

**Comment by josevalim** [comment]
@seanmor5 does PyTorch and JAX handle the case where no-one hooks into the hook and therefore they avoid sending the data in the first place? Because I think that's a pretty neat optimization :)

**Comment by polvalente** [comment]
I also like this proposal. One thing that's not entirely clear to me is how hooks would work across devices (i.e. working with something that's on the GPU).

Since I'm more familiar with Torchx as of lately, I'm gonna use it as an example, even though we don't compile it.

In Torchx we have `{device, ref}` tuples as the data for the Tensor. So the hook would receive the tensor with the respective backend configured (i.e. `%Nx.Tensor{data: {:cuda, #Ref<...>}}`), instead of transferring the data from the GPU to the CPU immediately. Is this the right line of thought?

**Comment by josevalim** [comment]
yes! For torchx we will just immediately receive the tensor as we evaluate it.

**Comment by josevalim** [comment]
Closing in favor of PR.
