### ISSUE TITLE
Higher level applications of Nx as examples

### ISSUE THREAD

**Issue by polvalente** [elixir-nx/nx#561]
This issue aims to concentrate the discussion o whether we should add livebooks with some higher level examples (for instance, [K-means](https://gist.github.com/polvalente/32c642c6a47fc75d65a381ea7a09f19b) -- disclaimer: the implementation does not yield the expected results, although it mostly works) to the Nx repo, or if we should start thinking about a higher level library for these applications. 

If we choose to add examples, which examples should we add?

**Comment by tiagodavi** [comment]
Playing a little bit with Nx Library (trying to predict the number of pizzas based on the number of reservations)
https://github.com/tiagodavi/NxLinearRegression

**Comment by tiagodavi** [comment]
We could have a samples folder with approved examples maybe?

**Comment by googya** [comment]
> 

I am implementing a similar case, learned a lot from your code, thanks

**Comment by googya** [comment]
> Playing a little bit with Nx Library (trying to predict the number of pizzas based on the number of reservations) https://github.com/tiagodavi/NxLinearRegression

I am implementing a similar case, learned a lot from your code, thanks

**Comment by josevalim** [comment]
Closing this for now!
