### ISSUE TITLE
enabling to_scalar for 1-element tensors?

### ISSUE THREAD

**Issue by dognotdog** [elixir-nx/nx#565]
Right now, `Nx.to_scalar/1` only works for zero-dimensional tensors. As it is a convenience function, would there be any downsides to allowing it to work on any 1-element tensor of arbitrary dimensions?

At least in my use case, it'd save some additional boilerplate where I know I'm left with a single element, and want to use it in regular elixir, but the tensor might have non-zero dimensions depending on how it was arrived at.

On the con side, is there any use case where one would want `Nx.to_scalar/1` to fail for 1-element but higher dimension tensors?

**Comment by polvalente** [comment]
In my opinion, the main point of discussion is whether needing to explicitly "cast" the tensor to a {}-shaped tensor is a downside or a feature.

One could argue that being explict about reshaping removes cognitive overload from the resulting code.

Another question: perhaps we could have an option for to_scalar to accept 1-element tensors regardless of dimension.

@seanmor5 @josevalim WDYT?

**Comment by seanmor5** [comment]
I am not in favor of having to_scalar work for 1-D or more tensors. In my opinion, you'd arrive at a scalar after a reduction or squeeze operation. In which case it's pretty clear that the resulting tensor has a scalar shape and the call to to_scalar should succeed. Any other case would rely on some assumptions about input shape or potentially buggy shape calculations.

**Comment by josevalim** [comment]
Agreed with Sean. Reshape or squeeze it and you should be good!
