### ISSUE TITLE
Add comprehension syntax to while and for loops

### ISSUE THREAD

**Issue by josevalim** [elixir-nx/nx#572]
Today I wrote this code:

```elixir
  defn navigate(tensor) do
    {size, _} = Nx.shape(tensor)

    {_, depth, position, _} =
      while {i = 0, depth = 0, position = 0, tensor}, i < size do
        instruction = tensor[i][0]
        value = tensor[i][1]

        cond do
          instruction == 0 -> {i + 1, depth, position + value, tensor}
          instruction == 1 -> {i + 1, depth + value, position, tensor}
          instruction == 2 -> {i + 1, depth - value, position, tensor}
          :otherwise -> {i + 1, depth, position, tensor}
        end
      end

    depth * position
  end
```

We could allow `<-` as part of `while`, so I could rewrite it to this:

```elixir
  defn navigate(tensor) do
    {depth, position} =
      while {depth = 0, position = 0}, subtensor <- tensor do
        instruction = subtensor[0]
        value = subtensor[1]

        cond do
          instruction == 0 -> {depth, position + value}
          instruction == 1 -> {depth + value, position}
          instruction == 2 -> {depth - value, position}
          :otherwise -> {depth, position}
        end
      end

    depth * position
  end
```

A further step is to introduce a `for` construct, that then works as a `map_reduce`. It will traverse a tensor and allow us to modify the leading dimension of the tensor at the same time, while retaining an accumulator.

Both functionality can be implemented using macros in `defn`, without adding more complexity to compilers.

**Comment by polvalente** [comment]
So in this construct subtensor would always be an iteration over the first dimension of the tensor?

**Comment by josevalim** [comment]
Correct! That’s how scan behaves in JAX.

**Comment by josevalim** [comment]
We have landed generators in while, with supports for tensors and ranges. `for` (also known as `scan`) can be implemented on top of `while` for now.
