### ISSUE TITLE
Iota silently fails when shape is not an actual shape

### ISSUE THREAD

**Issue by seanmor5** [elixir-nx/nx#573]
I was messing around with AoC day 3 and couldn't quite figure out why my solution was failing. Then I realized I forgot to wrap a value in `Nx.iota` in a tuple, so something like:

```elixir
Nx.iota(12) # or any non tuple here
```

Always just returns `Nx.tensor(0)`. I think it's better to raise in these cases with an error so bugs like this are caught faster

**Comment by josevalim** [comment]
@seanmor5 we allow any tensor as shape and a number is a tensor. Of course we could say that an integer could not be a shape but that's the current rationale. WDYT?

**Comment by seanmor5** [comment]
Ah that's right! I think in cases where it is an integer explicitly (not a tensor constructed like Nx.tensor(1)), it should raise

**Comment by josevalim** [comment]
@seanmor5 the point of allowing both though is so we can do this:

    Nx.broadcast(tensor, some_other_tensor)

where `some_other_tensor` can be any tensor. If we accept only tensors but not numbers, it can be inconsistent. There are two categories of functions: creation (eye, iota, random_number, etc) and transformation (broadcast, reshape). We have some options:

1. Do not accept tensors nor numbers in any of them
2. Accept only tensors in creation and transformation (feels unnatural)
3. Accept only tensors in creation and both in transformation
4. Accept none in creation and both in transformation
5. Accept both in both (current status)

What are your thoughts?

**Comment by seanmor5** [comment]
I think staying with 5 is fine then. It is already documented and I like being able to create from an existing tensor :D
