### ISSUE TITLE
"Scalar" term confusion

### ISSUE THREAD

**Issue by floatn** [elixir-nx/nx#579]
I've just been confused by finding out that Nx.to_scalar is used to convert a zero-dimension tensor to scalar. Since, technically, 0-dim tensor is already considered a scalar. I suggest we fix the terms by, for example, calling tensor a 'tensor', 0-dim tensor a 'scalar', and non-tensor scalar a 'number'. Since it sticks to `Kernel.is_number`. WDYT?

**Comment by josevalim** [comment]
I like it. Please do send a PR to rename `Nx.to_scalar` to `Nx.to_number`. :)

**Comment by floatn** [comment]
Ok.
