### ISSUE TITLE
Arbitrary size integers

### ISSUE THREAD

**Issue by rhbvkleef** [elixir-nx/nx#581]
It would be quite useful for me to be able to use huge numbers in my matrices. 64 or 128-bit integers would definitely not be enough. It would be great to have near to the same astronomical limit as that the BEAM provides.

**Comment by josevalim** [comment]
@rhbvkleef tall of the native backends that Nx targets are at most 64-bit integers, so this is not something I believe we can/should provide. If your goal is to leverage bignums then you should probably stay within the BEAM itself and outside of Nx. :)
