### ISSUE TITLE
Implement `Nx.LinAlg.matrix_power`

### ISSUE THREAD

**Issue by rhbvkleef** [elixir-nx/nx#582]
As a consequence of [Advent of Code 2021, day 6](https://adventofcode.com/2021/day/7), we discovered that Nx doesn't have a matrix_power function:

`@spec matrix_power(Nx.t, positive_integer) :: Nx.t`

This function would result in the power of the matrix by dot-product instead of by multiplication. We can solve this problem in linear time, using (source: https://github.com/josevalim/aoc/blob/main/2021/day-06.livemd)

```elixir
def matrix_power(matrix, power) do
  Enum.reduce(1..(power - 1), matrix, fn _, acc ->
    Nx.dot(matrix, acc)
  end
end
```

but, this is `O(n)` where n is the power. It is possible to do this in `O(log n)`, namely with repeated squaring:

```elixir
def matrix_power(matrix, 0) do
  Nx.subtract(matrix, matrix)
end
def matrix_power(matrix, power) do
  Integer.digits(power, 2)
  |> Enum.reverse()
  |> Enum.reduce({nil, matrix}, fn bit, {result_matrix, exp_matrix} ->
    cond do
      result_matrix == nil && bit == 1 -> {exp_matrix, Nx.dot(exp_matrix, exp_matrix)}
      result_matrix == nil && bit == 0 -> {nil, Nx.dot(exp_matrix, exp_matrix)}
      bit == 1 -> {Nx.dot(result_matrix, exp_matrix), Nx.dot(exp_matrix, exp_matrix)}
      bit == 0 -> {result_matrix, Nx.dot(exp_matrix, exp_matrix)}
    end
  end)
  |> elem(0)
end
```

I'm sure that this code is quite ugly, and should be refactored, but the logic should be clear. For external sources, reference can be made to the NumPy implementation: https://github.com/numpy/numpy/blob/main/numpy/linalg/linalg.py#L554. To see this implementation used, refer to [my Advent of Code 2021 day 6 solution](https://github.com/rhbvkleef/aoc2021/blob/master/lib/solutions/year2021/day6.ex)

**Comment by polvalente** [comment]
Wouldn't `matrix_power(matrix, 0), do: eye(matrix)` be the correct implementation instead of `subtract(matrix, matrix)`?

Besides that, I think a PR is welcome, as this kind of operation is common in numerical calculus.

One question that this would raise is that we need to choose between `power` and `matrix_power` for the implementation of the `**` operator in `defn`.

I also would implement it like this only in the BinaryBackend, delegating to respective implementations in EXLA and Torchx, instead of using this direct implementation in `nx.ex`. The grad for this shouldn't be too hard to implement and the performance of having a dedicated implementation can be quite useful.

WDYT @josevalim @seanmor5?

**Comment by seanmor5** [comment]
Agree with performance benefits of having specialized implementations, but IOT reduce API surface of future backend/compilers I think perhaps we go with the pure Nx implementation and then add specialized when we have optional backend functions? There is a very simple implementation in the JAX library as well

**Comment by polvalente** [comment]
> Agree with performance benefits of having specialized implementations, but IOT reduce API surface of future backend/compilers I think perhaps we go with the pure Nx implementation and then add specialized when we have optional backend functions? There is a very simple implementation in the JAX library as well

Yeah, I always forget to take API surface into account :sweat_smile:
This implementation seems fine aside from the `n = 0` case.

Would you like to submit a PR @rhbvkleef?

**Comment by rhbvkleef** [comment]
> Wouldn't matrix_power(matrix, 0), do: eye(matrix) be the correct implementation instead of subtract(matrix, matrix)?

Yes, that would be more correct. I agree.

As far as submitting a PR, I could, but it might take a while.

**Comment by rhbvkleef** [comment]
> I also would implement it like this only in the BinaryBackend, delegating to respective implementations in EXLA and Torchx, instead of using this direct implementation in nx.ex. The grad for this shouldn't be too hard to implement and the performance of having a dedicated implementation can be quite useful.

I don't think performance will be a problem with implementing it like this at all. After all, we're not likely to see high powers. I suspect that we'd run out of useful number range somewhere around 2^16, meaning this would only all Nx.dot at most 32 times for such an exponentiation. The actual calculation of the dot-products would take the large majority of the time in such cases.
