### ISSUE TITLE
Nx.window_reduce Compilation error case

### ISSUE THREAD

**Issue by floatn** [elixir-nx/nx#587]
This
```elixir
defmodule NxTest do
import Nx.Defn

  defn test() do
    Nx.window_reduce(Nx.tensor([1, 2, 3]),
      0, {2}, [padding: :same],
      fn x, acc -> x + acc end
    )
  end
end

NxTest.test() |> IO.inspect()
```
gives me:

== Compilation error in file lib/nx_test.ex ==
** (MatchError) no match of right hand side value: 1
    (nx 0.1.0-dev) lib/nx/binary_backend.ex:623: Nx.BinaryBackend.element_wise_bin_op/4
    (nx 0.1.0-dev) lib/nx/defn/evaluator.ex:147: Nx.Defn.Evaluator.eval_apply/4
    (nx 0.1.0-dev) lib/nx/defn/evaluator.ex:63: Nx.Defn.Evaluator.eval/3
    (nx 0.1.0-dev) lib/nx/defn/evaluator.ex:83: anonymous fn/4 in Nx.Defn.Evaluator.eval_apply/4
    (nx 0.1.0-dev) lib/nx/binary_backend.ex:1353: Nx.BinaryBackend."-window_reduce/6-_@5/2-2-"/4
    (nx 0.1.0-dev) lib/nx/binary_backend.ex:1351: anonymous fn/9 in Nx.BinaryBackend.window_reduce/6
    (elixir 1.12.2) lib/enum.ex:2385: Enum."-reduce/3-lists^foldl/2-0-"/3
    (nx 0.1.0-dev) lib/nx/binary_backend.ex:1345: Nx.BinaryBackend.window_reduce/6
```

**Comment by seanmor5** [comment]
This seems to go wrong in here: https://github.com/elixir-nx/nx/blob/main/nx/lib/nx/defn/evaluator.ex#L81 where the input arguments don't get cast to tensors correctly and the binary backend implementation of add doesn't like that

**Comment by seanmor5** [comment]
Note this doesn't fail outside of `defn`
