### ISSUE TITLE
Nx.tensor error when data is float and type is integer

### ISSUE THREAD

**Issue by tynanbe** [elixir-nx/nx#600]
Since `Nx.as_type` can downcast without issue, it seems that under similar conditions, tensor creation should not fail.
```elixir
> Nx.as_type(Nx.tensor(1.2), {:s, 64})
#Nx.Tensor<
  s64
  1
>

> Nx.tensor(1.2, type: {:s, 64})
** (ArgumentError) argument error
```

**Comment by josevalim** [comment]
Hi @tynanbe,

Can you provide a use case?

I consider this is intentional. `as_type` explicitly warns about losing precision and I would prefer if Nx.tensor safe guarded developers from that. You can call Nx.tensor with no type and then convert after.

**Comment by tynanbe** [comment]
My main thought is when there are tight memory constraints and unknown data coming in.

If someone requests a specific type on tensor creation, they probably have a reason for wanting to change precision right up front.

As a dev, it's surprising to have a type parameter where only some types can be successfully passed. If that's intentional behavior, I think it would ease mental burden and be less confusing to have no type option (or just never use it) for `Nx.tensor` and always require `Nx.as_type` when specifying a desired numerical type.

**Comment by polvalente** [comment]
@josevalim I agree that it would be preferrable to have this conversion be explicit, and this also keeps with the same mindset as we discussed in #565. However, @tynanbe does have a point regarding memory constraints. 

When creating a tensor for EXLA or Torchx, do we first parse it "as is" and then cast the type, or is the parsing done with the type in mind? If the parsing is done "blindly", then this change wouldn't make any difference. If it's informed, I would be in favor of allowing type casting on `Nx.tensor`

**Comment by josevalim** [comment]
Nx.tensor is about creating data from Elixir land. So you can truncate the floats too before calling Nx.tensor too.

> As a dev, it's surprising to have a type parameter where only some types can be successfully passed. 

the surprise argument works both ways. I would be very surprised if a library is discarding precision out of nowhere. And I think losing precision should be done by explicit APIs.

Plus this particular call would convert from f32 to s64, effectively using more space?

**Comment by tynanbe** [comment]
> Plus this particular call would convert from f32 to s64, effectively using more space?

This is just an example of a call that unexpectedly fails.

I agree that explicit operations are best, but I also see nothing implicit about stating what one expects from a function by passing an optional argument.

> Nx.tensor is about creating data from Elixir land. So you can truncate the floats too before calling Nx.tensor.

I honestly wasn't sure if this issue was a bug or not, but your explanation makes fine sense; seemingly there isn't anything to gain from stating the numerical type up front.

After this discussion, however, I'm confused as to why the optional `type` parameter for `Nx.tensor` is provided in the first place. It seems like a convenient substitute for calling `Nx.as_type` when you know what numerical type you want to begin with; but given that perspective, the behavior is inconsistent between the two. As is, the `type` parameter doesn't seem particularly useful from a developer standpoint.

Anyway, thanks for your time. I'm happy to close this issue and use the `Nx.as_type` workflow. It simplifies things greatly for me, as it turns out.

**Comment by polvalente** [comment]
@tynanbe 

> After this discussion, however, I'm confused as to why the optional type parameter for Nx.tensor is provided in the first place

This is mainly so you can get types other than the defaults. For instance: 

```elixir
iex(1)> Nx.tensor([1.0, 2.0])
#Nx.Tensor<
  f32[2]
  [1.0, 2.0]
>
iex(2)> Nx.tensor([1.0, 2.0], type: {:f, 64})
#Nx.Tensor<
  f64[2]
  [1.0, 2.0]
>
iex(3)> Nx.tensor([1.0, 2.0], type: {:bf, 16})
#Nx.Tensor<
  bf16[2]
  [1.0, 2.0]
>
```

or regarding integers:

```elixir
iex(4)> Nx.tensor([1, 2])
#Nx.Tensor<
  s64[2]
  [1, 2]
>
iex(5)> Nx.tensor([-1, 2], type: {:u, 64})
#Nx.Tensor<
  u64[2]
  [18446744073709551615, 2]
>
```

In summary, I think it's more about type promotion or byte size limitation than about type conversion (which is what would be needed for reading floats as integers, since you can assume that `-1` is a valid notation for `-1.0`, but not the other way around).
