### ISSUE TITLE
Unable to compile torchx on Windows 10

### ISSUE THREAD

**Issue by bhadra** [elixir-nx/nx#607]
On the command line the command "mix deps.compile torchx" generates the following error.

==> torchx
could not compile dependency :torchx, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile torchx", update it with "mix deps.update torchx" or clean it with "mix deps.clean torchx"
** (Protocol.UndefinedError) protocol String.Chars not implemented for {:win32, :nt} of type Tuple
    (elixir 1.13.2) lib/string/chars.ex:3: String.Chars.impl_for!/1
    (elixir 1.13.2) lib/string/chars.ex:22: String.Chars.to_string/1
    c:/srijit_data/Bhadra/Code/Elixir/my_app/deps/torchx/torchx/mix.exs:109: Torchx.MixProject.download_and_unzip/2
    (mix 1.13.2) lib/mix/task.ex:461: Mix.Task.run_alias/5
    (mix 1.13.2) lib/mix/tasks/compile.all.ex:92: Mix.Tasks.Compile.All.run_compiler/2
    (mix 1.13.2) lib/mix/tasks/compile.all.ex:72: Mix.Tasks.Compile.All.compile/4
    (mix 1.13.2) lib/mix/tasks/compile.all.ex:59: Mix.Tasks.Compile.All.with_logger_app/2
    (mix 1.13.2) lib/mix/tasks/compile.all.ex:36: Mix.Tasks.Compile.All.run/1

**Comment by josevalim** [comment]
I fixed this issue but it will error saying that Windows is not supported. We would appreciate pull requests to make the toolchain work on Windows. :)

**Comment by josevalim** [comment]
Here is the original issue: #314
