### ISSUE TITLE
Having Issues with Gradient exploding

### ISSUE THREAD

**Issue by tiagodavi** [elixir-nx/nx#614]
Hi Folks. I am wondering if I need to normalize real data before using it with Nx?

I was trying to reproduce this tutorial: https://dockyard.com/blog/2021/04/08/up-and-running-nx with real data, but I am facing issues like below:

```
* (MatchError) no match of right hand side value: <<0, 0, 128, 255>>
    (nx 0.1.0) lib/nx/binary_backend.ex:2126: Nx.BinaryBackend.scalar_to_number/1
    (nx 0.1.0) lib/nx/binary_backend.ex:594: Nx.BinaryBackend.element_wise_bin_op/4
    (nx 0.1.0) lib/nx/defn/evaluator.ex:149: Nx.Defn.Evaluator.eval_apply/4
    (nx 0.1.0) lib/nx/defn/evaluator.ex:63: Nx.Defn.Evaluator.eval/3
    (elixir 1.13.2) lib/enum.ex:1715: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir 1.13.2) lib/enum.ex:1715: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (nx 0.1.0) lib/nx/defn/evaluator.ex:130: Nx.Defn.Evaluator.eval_apply/4
    (nx 0.1.0) lib/nx/defn/evaluator.ex:63: Nx.Defn.Evaluator.eval/3

```

This is my example:

https://github.com/tiagodavi/NxLinearRegression/blob/main/lib/fuel_economy.ex
https://github.com/tiagodavi/NxLinearRegression/blob/main/lib/nx_linear_regression.ex

**Comment by floatn** [comment]
What is your input data?
```elixir
[{1.0, 1.0}, {2.0, 2.0}]
|> NxLinearRegression.train(0.01, 100)
```
works fine.

**Comment by floatn** [comment]
> I am wondering if I need to normalize real data before using it with Nx?

Yes, it'll help.

**Comment by tiagodavi** [comment]
@floatn Thank you.

I was able to fix after normalizing the data!
https://github.com/tiagodavi/NxLinearRegression
