### ISSUE TITLE
Loading TorchScript JIT models in torchx

### ISSUE THREAD

**Issue by laurglia** [elixir-nx/nx#643]
PyTorch C++ front-end supports loading TorchScript JIT models with function `torch::jit::load`: https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/serialization/import.h#L68

It would be beneficial to have this function available in torchx because it would allow loading models that are trained in Python in Elixir without writing the code for models in Elixir.

Do you have any plans for adding support such functionality?

I would be open to implementing it myself as well.

**Comment by josevalim** [comment]
A pull request that adds this functionality into torchx would certainly be welcome!

**Comment by josevalim** [comment]
Closing this for now but a PR is still welcome if someone is interested!
