### ISSUE TITLE
Optional operator handling update broke solve() on EXLA backend

### ISSUE THREAD

**Issue by dognotdog** [elixir-nx/nx#651]
Seems like d19c537c862a19b44e1a18686262c6ef82eed5e0 broke `solve()` with the EXLA backend. EXLA does not have solve, and indeed the `triangular_solve()` fallback should be used, but is not, from here: https://github.com/elixir-nx/nx/blob/bdd14c4abf962caf21e68fa798dbf1063d8b450c/nx/lib/nx/lin_alg.ex#L502

The fallback should be used, but instead `solve()` on EXLA is attempted, which fails:
<img width="697" alt="image" src="https://user-images.githubusercontent.com/1443151/154805485-66540e4b-11db-4e7e-8c58-8b33cbda6cd3.png">

Reverting to 2c534e27e16bc7793c50620d9b3d53f2f1b53c46, solve() with EXLA works fine.

Code that causes this is
```elixir
  def linreg(x, y) do
    linregn(x,y) |> Nx.backend_transfer()
  end

  defnp linregn(x, y) do
    xtx = Nx.dot(Nx.transpose(x), x)
    xty = Nx.dot(Nx.transpose(x), y)
    Nx.LinAlg.solve(xtx, xty)
  end
```
when compiled with the EXLA backend.

**Comment by josevalim** [comment]
This should be fixed in main. Which SHA are you on? :)

**Comment by josevalim** [comment]
In particular this commit should have solved it: https://github.com/elixir-nx/nx/commit/6f77d48b365aa174b131af88878ca559bc209630

**Comment by dognotdog** [comment]
Cool, will test as soon as I can... looks like another part of my code broke on current head, so I can't quite tell if this is fixed, yet.
