### ISSUE TITLE
`Nx.runtime_normal/4` throws an error when used inside defn and the shape is set via tuple

### ISSUE THREAD

**Issue by nickgnd** [elixir-nx/nx#668]
Hey all 👋 
first of all, many many thanks for the amazing work you all are doing with this library and the related ones.
I'm newbie in ML and I'm having fun learning it by playing with Nx.

## The issue

`Nx.random_normal/4` throws an error when used inside a numerical function `defn` and the shape is set via tuple (eg. `Nx.random_normal({10, 5})`). I'm using EXLA as backend.

## My system

I'm tested it on macOS X 11.6.3.

Erlang and Elixir versions below 👇 

```
❯ iex
Erlang/OTP 24 [erts-12.1.5] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Interactive Elixir (1.13.0) - press Ctrl+C to exit (type h() ENTER for help)
```

## How to reproduce

```elixir
Mix.install([
  {:exla, "~> 0.1.0-dev", github: "elixir-nx/nx", sparse: "exla"},
  {:nx, "~> 0.1.0-dev", github: "elixir-nx/nx", sparse: "nx", override: true}
])

Nx.Defn.global_default_options(compiler: EXLA)

defmodule RandomNormalTest do
  import Nx.Defn

  defn create_with_defn(shape) do
    Nx.random_normal(shape, 0.0, 1.0)
  end
end
```

```elixir
RandomNormalTest.create_with_defn({10, 4})
```

Throws this error:

```
** (ArgumentError) invalid dimension in axis 1 in shape. Each dimension must be a positive integer, got #Nx.Tensor<
  s64
  
  Nx.Defn.Expr
  parameter a:1   s64
> in shape {#Nx.Tensor<
   s64
   
   Nx.Defn.Expr
   parameter a:0   s64
 >, #Nx.Tensor<
   s64
   
   Nx.Defn.Expr
   parameter a:1   s64
 >}
    (nx 0.1.0) lib/nx/shape.ex:35: Nx.Shape.validate!/3
    (nx 0.1.0) lib/nx.ex:905: Nx.random_normal/4
    (nx 0.1.0) lib/nx/defn/compiler.ex:104: Nx.Defn.Compiler.runtime_fun/4
    (exla 0.1.0-dev) lib/exla/defn.ex:299: anonymous fn/2 in EXLA.Defn.compile/7
    (exla 0.1.0-dev) lib/exla/defn/locked_cache.ex:40: EXLA.Defn.LockedCache.run/2
    (exla 0.1.0-dev) lib/exla/defn.ex:298: EXLA.Defn.compile/7
    (exla 0.1.0-dev) lib/exla/defn.ex:225: EXLA.Defn.__jit__/4
```

It works fine if, instead of using a tuple to set the shape, a tensor is passed to infer it. Or when the `Nx.runtime_uniform/4` is used within a "standard" function `def …`.

I created a gist with a livebook to reproduce it https://gist.github.com/nickgnd/16b441cf818f20180b2d2afafd7c4db0

Let me know if there is anything else I can do :)
Thanks again 🙇‍♂️

**Comment by seanmor5** [comment]
`defn` converts all arguments to tensors / containers, so `shape` is getting turned into a tuple of scalar tensors instead of an actual shape like you want. You can tell `defn` to not cast with default arguments, for example by passing the shape as an option:

```elixir
  defn create_with_defn(opts \\ []) do
    # list all keyword arguments here
    opts = keyword!(opts, [:shape])
    Nx.random_normal(opts[:shape], 0.0, 1.0)
  end
```

Then you pass shape as an option:

```elixir
create_with_defn(shape: {10, 5})
```

You can checkout Axon for extensive use of this pattern

**Comment by josevalim** [comment]
@seanmor5 I am thinking maybe we should use the same pattern in Nx. It is kind of weird if people can't reproduce the same APIs as us.

WDYT about: `Nx.random_uniform(min, max, shape: ...)` and the default shape is constant?

In any case, I want to reopen this because I think we can at least improve the error message. :)

**Comment by nickgnd** [comment]
Thank you so much @seanmor5 for the quick and exhaustive reply.

> defn converts all arguments to tensors / containers, so shape is getting turned into a tuple of scalar tensors instead of an actual shape like you want.

💡 Something that I missed, thank you for pointing it out. 

I changed my function as you suggested and it works great 💪 

Wish you a good continuation of the week,
Cheers ✌️
