### ISSUE TITLE
Will Nx support other backends for performance?

### ISSUE THREAD

**Issue by NduatiK** [elixir-nx/nx#718]
Hi,
I am attempting to normalize a large number of tensors from numpy files and I am experiencing some performance issues. This is probably a Elixir/immutability issue since Numpy does the same operations pretty fast. 

Are their plans to add a faster backend like Polars with Explorer? 

Should I find just:
- convert the tensor to an Explorer DataFrame
- normalize there 
- then return to Nx for the Deep Learning functionality

Thanks

**Comment by josevalim** [comment]
Please check out the README at the root, it shows both EXLA and Torchx backends for improved performance. :)

**Comment by NduatiK** [comment]
Thanks @josevalim, I _was_ using EXLA, but had made the mistake of defaulting to CUDA. Sean's comments [here](https://github.com/elixir-nx/scidata/issues/13), "transformation work is most efficiently offloaded to the CPU" and "Transferring data from CPU to an accelerator can prove costly", made me move to CPU which is much faster.
