### ISSUE TITLE
Help with conv/3

### ISSUE THREAD

**Issue by adampointer** [elixir-nx/nx#725]
Hi,

I am new to Nx and I am trying to implement a simple moving average using conv as per this stackoverflow post which uses numpy.

https://stackoverflow.com/a/54628145

I naively tried this in Nx but I am getting errors. I assume it is because I cannot use a 1d vector and need encode the batch_size etc into a higher dimensional tensor. However the docs for conv are melting my brain. How would I shape my input and kernel tensors to achieve in Nx what the above post achieves in numpy?

So to simplify my question, np.convolve returns the discrete, linear convolution of two one-dimensional sequences.

How do I shape my inputs to make Nx.conv to behave like np?

Apologies if this is a stupid question.
Thanks

**Comment by josevalim** [comment]
You can use the more intuitive Nx.window_sum/3 for a moving average:

```elixir
value = Nx.tensor([10, 20, 30, 40, 50])
 Nx.window_sum(value, {3}) # window size of 3
```

Use the :padding configuration set to :same or :valid if you want padding or not. Then you can divide by the window size.
