### ISSUE TITLE
Raise error message pointing to inspect_value and inspect_expr if someone tries to use IO inside defn

### ISSUE THREAD

**Issue by josevalim** [elixir-nx/nx#731]

**Comment by polvalente** [comment]
@josevalim is this just for IO.inspect or for any IO function?

**Comment by seanmor5** [comment]
@polvalente I would say at least `IO.inspect`, `IO.puts`, `IO.write`, and `IO.warn` ?

**Comment by josevalim** [comment]
We can detect any IO function and raise a message saying the options available.
