### ISSUE TITLE
EXLA Compilation issues on Intel Mac

### ISSUE THREAD

**Issue by herman-rogers** [elixir-nx/nx#745]
Having the following issue on getting EXLA to compile (both inside of a project and inside of EXLA itself):

<img width="1155" alt="Screen Shot 2022-04-22 at 1 08 51 PM" src="https://user-images.githubusercontent.com/3153479/164761953-75306dc0-401d-4f65-b27c-78fae49a5a2f.png">

After reading about a similar issue [here](https://github.com/elixir-nx/nx/issues/665) and a fix of it [here](https://github.com/elixir-nx/nx/pull/688) I was able to fix it in the same location for bazel's pathing on darwin machines.

<img width="1136" alt="Screen Shot 2022-04-22 at 1 10 31 PM" src="https://user-images.githubusercontent.com/3153479/164762195-4a5b6f43-e7dd-475c-be85-4b87ceb48f43.png">

I did look at the cached lib location and there is no folder there, only the xla_extension folder. After changing the file path I was able to get all tests passing in EXLA:

<img width="1154" alt="Screen Shot 2022-04-22 at 1 11 39 PM" src="https://user-images.githubusercontent.com/3153479/164762363-338b3b86-a039-4f18-bf33-dfeda24e5c37.png">

Edit: It seems like without modification EXLA works on other intel machines so I though I'd just report the issue. It's a good enough fix for me to continue some machine learning work.

**Comment by josevalim** [comment]
Can you please send a PR? I double checked and your fix worked on my machines. :)

**Comment by herman-rogers** [comment]
Yep can do!
