### ISSUE TITLE
Support :reverse option in cumulative functions

### ISSUE THREAD

**Issue by josevalim** [elixir-nx/nx#771]
To match Explorer: https://github.com/elixir-nx/explorer/pull/200

**Comment by Benjamin-Philip** [comment]
@josevalim could you expand on the behaviour of the reverse option?

For some reason, I am not able to compile explorer on my machine, nor am I finding any documentation explaining it in Explorer or Polars.

**Comment by josevalim** [comment]
https://hexdocs.pm/explorer/Explorer.Series.html#cumulative_max/2
