### ISSUE TITLE
Why make Numerical Elixir?

### ISSUE THREAD

**Issue by nalzok** [elixir-nx/nx#812]
I mean no offense, but I am really curious about your motivation. There are big players like Python and Julia for machine learning applications, let alone established frameworks like PyTorch/TensorFlow/JAX, so which niche is Numerical Elixir targeting? What makes the Elixir language suitable for scientific computing? Who should use Numerical Elixir in their projects?

It would be great to add a section about your vision to the README file.

**Comment by josevalim** [comment]
ML in particular can also have good "synergy" with different areas in the ecosystem, such as web development (collocate some ML features _within_ your web app within any additional dependency), embedded systems (deploy neural models/signal processing/etc via https://www.nerves-project.org/), etc. You can also use Broadway to run some particular pipelines (preprocess the data concurrently, batch it, and perform something on it).
