### ISSUE TITLE
Identify NaN in tensors

### ISSUE THREAD

**Issue by RD314** [elixir-nx/nx#814]
I think it would be useful to have inside Nx.defn functions like is_number or is_nan. 
It would be useful especially when working with grad that could return NaN and gradient is used in subsequent formulas.

**Comment by josevalim** [comment]
There is only a concern in people confusing those with guards but we should indeed have similar functions and there is prior art in Numpy.

**Comment by RD314** [comment]
My current workaround is having two functions:
defn is_nan(t) do
  transform(t,&is_nan_d/1)
end
defp is_nan_d(t) do
  try do
    k = Nx.tensor(1, type: {:f, 64})
    Nx.logical_not( Nx.logical_or(Nx.less(k, t), Nx.greater_equal(k,t)))
  rescue
    RuntimeError -> Nx.tensor(1,  type: {:u, 8})
  catch
    _ ->
      k = Nx.tensor(1, type: {:f, 64})
      Nx.logical_not( Nx.logical_or(Nx.less(k, t), Nx.greater_equal(k,t)))
  end
end

Probably it is not the best way how to deal with it (if you see better workaround, please feel free to share.). 

The reason for using "def" func is the that scalar tensor with :nan value in "defn" raises the ArgumentError.

**Comment by polvalente** [comment]
> The reason for using "def" func is the that scalar tensor with :nan value in "defn" raises the ArgumentError.

@RD314 about this, `t + :nan` does indeed raise an error, but `t + Nx.tensor(:nan)` works just fine, so you could have implemented it as:

```elixir
defn is_nan(t) do
  Nx.logical_not(t < Nx.tensor(:nan), t >= t)
end
```

or the simplified version that relies on nan always being different from nan (and is what libtorch ultimately uses):

```elixir
defn is_nan(t) do
  t != t
end
```
