### ISSUE TITLE
Functions set_diagonal(tensor, opts \\ []) , and indexed_set(target, indices, updates)

### ISSUE THREAD

**Issue by RD314** [elixir-nx/nx#817]
It would be great if `set_diagonal(tensor, opts \\ []) ` and ` indexed_set(target, indices, updates) ` can be added. 

It would complement the operations allowed already. Slicing and access syntax allow setting the values to columns or rows, or individual "cells". 

Setting diagonal or other set of "cells" can be now done only by some cycle accessing and setting each diagonal value. 
There are functions that can be used as a head start: 
1) Accesign diagonal: `make_diagonal(tensor, opts \\ [])`, `take_diagonal(tensor, opts \\ [])`.
2) Adding value to the enumerated list of indexes: ` indexed_add(target, indices, updates)`.

For setting the diagonal the workaround is to take the diagonal values and subtract them from matrix, e.g. 
```
#make diagonal zero and add new value
t = Nx.random_uniform({5,5},1,0.1)
new_diagonal = Nx.random_uniform({5},1, 0.1) 
s = t |> Nx.take_diagonal() |> Nx.make_diagonal()
Nx.subtract(t, s) |> Nx.add(Nx.make_diagonal(new_diagonal))
```
The issue I see with this is that subtracting leads to rounding errors, and efficiency of the workaround.

The function ` indexed_set(target, indices, updates) ` has the similar logic and would be great complement to `indexed_add(target, indices, updates)`.

**Comment by josevalim** [comment]
We would love a PR that adds `Nx.put_diagonal/3`. `Nx.indexed_put/3` would be welcome as well.

**Comment by polvalente** [comment]
@RD314 do you plan on sending a PR on this? Just asking so we avoid having multiple people working on the same thing :)

**Comment by RD314** [comment]
@polvalente the short answer Is no. It would be great if you can address this need.

**Comment by polvalente** [comment]
> @polvalente the short answer Is no. It would be great if you can address this need.

@RD314 don't worry! I just didn't want to steal this from you :)
Hopefully we'll have a PR on this later this week

**Comment by Benjamin-Philip** [comment]
> Hopefully we'll have a PR on this later this week

I am working on this right now.
