### ISSUE TITLE
Potential ArgumentError muted by EXLA

### ISSUE THREAD

**Issue by jnnks** [elixir-nx/nx#838]
When predicting using Axon without EXLA, an argument error prevents me from doing the following:
```elixir
# build 3x128x128 tensor
tensor = Nx.tensor([1..128 |> Enum.take(128)])
|> Nx.tile([3, 128, 1])

# build scaling model, witch should not do anything useful
scaler =
  Axon.input("in", shape: {nil, 3, 128, 128})
  |> Axon.resize({330, 330}, method: :linear)

# resize tensor
Axon.predict(scaler, %{}, Nx.stack([frame])) # <-- crashes here
|> IO.inspect(limit: :infinity) 
```
Output:
```
** (ArgumentError) index -128 is out of bounds for axis 2 in shape {1, 3, 128, 128}
    (nx 0.3.0-dev) lib/nx/binary_backend.ex:1910: Nx.BinaryBackend."-take/4-lc$^0/1-0-"/11
    (nx 0.3.0-dev) lib/nx/binary_backend.ex:1906: Nx.BinaryBackend."-take/4-lc$^0/1-0-"/11
    (nx 0.3.0-dev) lib/nx/binary_backend.ex:1906: Nx.BinaryBackend.take/4
    (nx 0.3.0-dev) lib/nx/defn/evaluator.ex:185: Nx.Defn.Evaluator.eval_apply/4
    (nx 0.3.0-dev) lib/nx/defn/evaluator.ex:82: Nx.Defn.Evaluator.eval/3
    (elixir 1.13.2) lib/enum.ex:1715: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir 1.13.2) lib/enum.ex:1715: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (nx 0.3.0-dev) lib/nx/defn/evaluator.ex:163: Nx.Defn.Evaluator.eval_apply/4
```
With EXLA however, no error is raised, but the resulting tensor has incorrect values. The last column is `-32384.0`.
My expectation would be `128`, so leaving the input tensor unchanged.

This problem is also present for "upscaling" tensors. The last few columns will be negative values close to the `s16` minimum.

When resizing to a 3x127x127 tensor no error is raised and no unexpected values are present.

**Comment by jonatanklosko** [comment]
EXLA clamps out of bound indices (because we don't raise from a computation running on the GPU).

![image](https://user-images.githubusercontent.com/17034772/179411261-210e0813-029f-4149-8711-b99c59d5fe10.png)

I think the binary backend should clamp as well, since that's already the case for `tensor[index]` access.

In either case, the out of bound access is a bug in the Axon linear resize.

**Comment by josevalim** [comment]
> In either case, the out of bound access is a bug in the Axon linear resize.

If it is a bug in Axon... wouldn't it be better for it to continue raising in Nx.BinaryBackend for better feedback?

**Comment by jonatanklosko** [comment]
@josevalim we have this:

https://github.com/elixir-nx/nx/blob/01d85d8bfd026226cc63bd16a225b077c86b863b/nx/lib/nx.ex#L203-L221

So I assume it was an explicit decision. I just think we should stay consistent, since `take` is essentially accessing dynamic indices. wdyt?

**Comment by josevalim** [comment]
When we started, our decision was to raise where we can to help catch errors. If in this case clamping is a bug, then I say we made the correct decision. debugging the clamping otherwise would be _very hard_. :)

**Comment by jonatanklosko** [comment]
> If in this case clamping is a bug, then I say we made the correct decision

Not sure if I follow, `t[1]` raises, but my point is that `t[Nx.tensor(1)]` does not. Perhaps it should?

**Comment by josevalim** [comment]
Oh, I see. Access with tensor is built on top of `Nx.slice` and that is by design clamping. For now, I would go with "keep as is" but we can always revisit it later. :)

**Comment by jonatanklosko** [comment]
Sounds good to me!
