### ISSUE TITLE
Mistake in intro-to-nx.livemd

### ISSUE THREAD

**Issue by jan-swiatek** [elixir-nx/nx#852]
Please, correct me if I'm wrong, but there is a mistake in intro-to-nx.livemd file. An example operation is subtraction of two tensors, but in the description you wrote "To solve this problem, add each integer on the left with the corresponding integer on the right."

![image](https://user-images.githubusercontent.com/72558464/181836276-60a7ad2d-691e-48ca-84a4-1fa12e2b9afc.png)

**Comment by josevalim** [comment]
Thank you! Would you like to send a PR? Or should we fix it? :)

**Comment by jan-swiatek** [comment]
Already fixed :)
