### ISSUE TITLE
Another typos in intro-to-nx.livemd

### ISSUE THREAD

**Issue by jan-swiatek** [elixir-nx/nx#854]
I found another typo in intro-to-nx.livemd. I guess it should be "definition".

![image](https://user-images.githubusercontent.com/72558464/181844287-6efe1b18-2483-4f7f-8510-24f7472f4bb0.png)

I'm not 100% sure about second one, but in Nx.Defn.grad documentation, all gradient functions are numerical definitions: `defn`. In the other hand `poly_slope_at/1` is a usual elixir definition: `def`. Is it ok?

![image](https://user-images.githubusercontent.com/72558464/181844758-29dba3e4-0779-421f-87b2-3373352ef712.png)

**Comment by josevalim** [comment]
Yes, it should be a defn too and it should work! If not, please let us know. PR welcome!

**Comment by jan-swiatek** [comment]
Yes, it works with both def and defn. Fixed :)
