### ISSUE TITLE
if/else not behaving as I expect

### ISSUE THREAD

**Issue by wadehenning** [elixir-nx/nx#856]
if/else expressions are not behaving as I expect-- they always evaluate to ``` true```.  For example:

**Code**
```   
test = if Nx.less(2,1) do 42  else 66 end
     IO.inspect(test, label: 'test should be 66')
```
**Expected Result**
``` test should be 66: 66```

**Actual Result**
``` test should be 66: 42```

**Change Code to Alternative Comparison**
```   
test = if Nx.less(1,2) do 42  else 66 end
     IO.inspect(test, label: 'test is always 42')
```
**Result**
``` test is always 42: 42```

**Comment by josevalim** [comment]
When you are inside regular Elixir code, then if has regular Elixir semantics and an Nx tensor will always evaluate to true.

Inside `defn`, then everything is a numerical expression, and it should behave as you expect.
