### ISSUE TITLE
Nx.log(0) raises error on binary backend but returns -Inf in EXLA 

### ISSUE THREAD

**Issue by germanftorres** [elixir-nx/nx#874]
Currently Nx.log raises an error when you pass 0 as argument. when using the binary backend implementation.
```
>Nx.log(0)

** (ArithmeticError) bad argument in arithmetic expression
    (stdlib 3.15.2) :math.log(0)
    (complex 0.4.1) lib/complex.ex:868: Complex.ln/1
    (nx 0.2.1) lib/nx/binary_backend.ex:870: Nx.BinaryBackend."-element_wise_unary_op/3-lbc$^1/2-18-"/5
    (nx 0.2.1) lib/nx/binary_backend.ex:869: Nx.BinaryBackend.element_wise_unary_op/3
``` 

But using EXLA compiler it returns -Inf

```
>Nx.global_default_backend(EXLA.Backend)

>Nx.log(0)

#Nx.Tensor<
  f32
  EXLA.Backend<host:0, 0.1207864525.756416528.148023>
  -Inf
>
```

Infinity handling should be consistent between different implementations.

**Comment by polvalente** [comment]
Which cersion are you using? Is it Hex or GitHub main?

**Comment by polvalente** [comment]
Reading the stacktrace more closely, this is actually a problem with the Complex library. We can leave this open to track, but the fix is there instead.

**Comment by germanftorres** [comment]
Thanks for submitting the issue in the Complex repo.
