### ISSUE TITLE
How can I emulate jax.lax.scan?

### ISSUE THREAD

**Issue by JWalker1995** [elixir-nx/nx#889]
Hi! First off, thank you for this awesome library! I'm trying to implement a scan operation like [jax.lax.scan](https://jax.readthedocs.io/en/latest/_autosummary/jax.lax.scan.html). I need each reduction output, not just the final one.

This is what I have, which fails because, understandably, list operations aren't supported in defn (`undefined function |/2`). Is there a better way to do this, or is support for a more generic scan operation planned?
```elixir
defmodule X do
  import Nx.Defn

  defn scan(f, init, xs) do
    {size, _} = Nx.shape(xs)
    out = []

    {_, _, carry, out} =
      while {i = 0, xs, init, out}, i < size do
        carry = f.(init, xs[i])
        {i + 1, xs, carry, [carry | out]}
      end

    {carry, out}
  end
end
```

**Comment by josevalim** [comment]
Instead of collecting carries, you should create a tensor and update its leading dimension. So you would do something like:

    out = Nx.broadcast(0, {compute_the_size})
    while ... do
      out = Nx.put_slice(out, i, carry)
    end

This is pseudo-code, you will need to figure out the arguments. :) We want to make it easier with #572.

**Comment by seanmor5** [comment]
@JWalker1995 There's also a draft scan implementation here: https://github.com/elixir-nx/axon/pull/341

Notice that you need to include the environment because `while` bodies are not closures

**Comment by JWalker1995** [comment]
Thank you both. That's very helpful.
