### ISSUE TITLE
Error Loading Module 'Elixir.NX'

### ISSUE THREAD

**Issue by armoredsky** [elixir-nx/nx#892]
Getting a failed: :badfile error trying to use NX. 

Fresh brew install of latest elixir, deps only has 
 ```elixir
defp deps do
    [
      {:mix_test_watch, "~> 1.0", only: :dev, runtime: false},
      {:temp, "~> 0.4"},
      {:ksuid, "~> 0.1.2"},
      {:nx, "~> 0.3.0"},
      {:scidata, "~> 0.1.8"}
    ]
  end
```
  running "iex -S mix"
and trying to autocomplete, or use NX in anyway results in the picture below. 

I've removed deps and _build, rebuilt everything several times. I've tried versions 0.1.0, 0.2.0, 0.2.1, and 0.3.0 to the same affect. Which does lead me to believe it is probably on my side, but i've never seen this from any other dependence.

![Screen Shot 2022-08-30 at 10 16 58 PM](https://user-images.githubusercontent.com/3985865/187585052-e8c453f8-1303-4448-b2d8-d9d2b6e8c297.png)

**Comment by josevalim** [comment]
Note it should be `Nx`. On case insensitive fileystems, `NX` ends up loading th `Nx.beam` file anyway, leading to the error message above.

**Comment by armoredsky** [comment]
omg, that second set of eyes is really helpful. thank you so much for the quick response.
