### ISSUE TITLE
EXLA output goes directly to livebook console

### ISSUE THREAD

**Issue by petrkozorezov** [elixir-nx/nx#932]
I’m trying to use hooks to debug my defn functions in livebook, but I see `IO.inspect` output only on default Binary backend and doesn’t see it on EXLA. The EXLA output goes directly to the livebook console.
I don't know is this a bug or a feature (of EXLA or Livebook), but it's confusing a little bit.

**Comment by josevalim** [comment]
Can you please give more context? What is the code? How are you running it? Can you provide a minimal example?

**Comment by petrkozorezov** [comment]
> Can you please give more context? What is the code? How are you running it? Can you provide a minimal example?

Sure. I'm running this code in on my server machine in livebook.

```elixir
Mix.install(
  [
    {:nx, "~> 0.3"},
    {:exla, "~> 0.3"},
  ],
  config: [
    nx: [
      default_backend: EXLA.Backend,
      default_defn_options: [compiler: EXLA]
    ]
  ]
)
```
```elixir
defmodule Hooks do
  import Nx.Defn

  defn add_and_mult(a, b) do
    add = hook(a + b, fn tensor -> IO.inspect({:add, tensor}) end)
    mult = hook(a * b, fn tensor -> IO.inspect({:mult, tensor}) end)
    {add, mult}
  end
end
```

```
λ livebook --version
Erlang/OTP 24 [erts-12.2] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit]

Elixir 1.13.4 (compiled with Erlang/OTP 24)

Livebook 0.6.3
```

**Comment by josevalim** [comment]
Ok, thanks! I know why it happens! The hooks for EXLA is running on another group leader but we can address it. :)

**Comment by petrkozorezov** [comment]
Yeah, looks like a problem with a group leader.
