### ISSUE TITLE
How about renaming `Nx.log/1` to `Nx.ln/1`?

### ISSUE THREAD

**Issue by nallwhy** [elixir-nx/nx#939]
The name `Nx.log/1` makes me confused.

Following https://en.wikipedia.org/wiki/Natural_logarithm, `ln` is unambiguously but `log` has different meanings in different contexts.

If `Nx.log2/1`, `Nx.log10/` is added later, it will be more confusing because those functions look like handy functions of `Nx.log/2` with a fixed base(2, 10).

**Comment by polvalente** [comment]
The problem with that is that `log` is the name used for `ln` in NumPy, Jax and PyTorch, all of which are reference libraries in the numerical computing area. MATLAB and Julia also use that standard, as it seems, as well as the `:math` module in Erlang (which is what we use in Elixir).

For what it's worth, I also dislike this ambiguity, but I don't think it would be a good idea to break this pattern.
