### ISSUE TITLE
Support :mps as default

### ISSUE THREAD

**Issue by josevalim** [elixir-nx/nx#944]

**Comment by Benjamin-Philip** [comment]
@josevalim, could you expand on this? Do you mean support it as a default device in `Torchx.default_device/0`?

**Comment by josevalim** [comment]
Yes, but we checked this and it is not viable as many operations are missing :(

**Comment by Benjamin-Philip** [comment]
> it is not viable as many operations are missing :(

Ok. How are supporting it as a device at all let alone as a default one in this care? Are we supporting it simply because Libtorch is offering it as a backend? I'm guessing said operations need to be added in Libtorch.

**Comment by josevalim** [comment]
We already support mps as a device but it only handles some types and operations.
