### ISSUE TITLE
In nx.slice() what is 4th parameter can i pass , it raising an error

### ISSUE THREAD

**Issue by creddyravindra** [elixir-nx/nx#956]
we convert img to `Nx.to_nx` in that we got {1080,1080,3}
we are trying to slice the image
by using `Nx.slice(img,[150,0,0],[880,1080,3])`
its working fine in cmd
but if we are trying to write in  main program its need 4 th parameter list 
how can we solve this

**Comment by josevalim** [comment]
Hi @creddyravindra!

Please check the docs: https://hexdocs.pm/nx/Nx.html#slice/4

You can also use the ElixirForum for further questions and clarifications! If something is failing, please also include the error message, stacktrace and so on when posting there.
