### ISSUE TITLE
2Gb tensor serialization/deserialization

### ISSUE THREAD

**Issue by petrkozorezov** [elixir-nx/nx#967]
I'm trying to serialize/deserialize big (a few Gb) tensors and facing a node crash with a strange, huge allocation attempt. And my server has enough memory for that (128Gb).

```elixir
Mix.install(
  [
    {:nx, "~> 0.3.0"},
    {:exla, "~> 0.3.0"},
  ],
  config: [
    nx: [
      default_backend: EXLA.Backend,
      default_defn_options: [compiler: EXLA]
    ]
  ]
)
```

```elixir
Nx.iota({2 * 1024 * 1024 * 1024 |> div(8)}, type: :f64)
|> Nx.serialize()
|> :erlang.list_to_binary()
|> Nx.deserialize()
```

```
binary_alloc: Cannot allocate 18446744071562067968 bytes of memory (of type "binary").
Crash dump is being written to: erl_crash.dump...done
```

```
$ free -g
               total        used        free      shared  buff/cache   available
Mem:             125          63          39           0          22          61
```

But everything works with from/to_binary

```elixir
Nx.iota({2 * 1024 * 1024 * 1024 |> div(8)}, type: :f64)
|> Nx.to_binary()
|> Nx.from_binary(:f64)
```

Erlang version
```
Erlang/OTP 24 [erts-12.3.2.2] [source] [64-bit] [smp:32:32] [ds:32:32:10] [async-threads:1] [jit]
```

**Comment by josevalim** [comment]
Can you please try a more recent Erlang? The amount of memory being allocated seems to indicate this is an Erlang serialization/deserialization bug.

**Comment by petrkozorezov** [comment]
> Can you please try a more recent Erlang? The amount of memory being allocated seems to indicate this is an Erlang serialization/deserialization bug.

The same on R25.1 (the latest version I have in NixOS), but I agree, this looks like a bug in `term_to_binary()`.

**Comment by josevalim** [comment]
Thanks! Reproduced and reported here: https://github.com/erlang/otp/issues/6393 - closing this one. Follow upstream for updates!
