### ISSUE TITLE
Telemetry events for XLA compilations

### ISSUE THREAD

**Issue by laursisask** [elixir-nx/nx#974]
My organization has encountered a problem where there are sometimes spikes in CPU usage and latency with Nx & EXLA. We suspect that one reason this is happening is that some JIT-compiled functions are compiled over and over again.

Currently, EXLA has debug mode which logs out information about XLA compilations, e.g.

```
18:25:45.945 [debug] domain=elixir file=lib/exla/defn.ex line=375  EXLA defn evaluation in 0.7ms
18:25:46.024 [debug] domain=elixir file=lib/exla/defn.ex line=412  EXLA compilation in 79.0ms
18:25:46.024 [debug] domain=elixir file=lib/exla/defn.ex line=271  EXLA device 0 lock in 0.0ms
```

It would be helpful if in addition to these logs there were telemetry events to which applications could listen.

The events could contain measurements for defn evaluation time, compilation time, and the time waiting for EXLA lock. In metadata, could include the reference to function being compiled and the argument shapes.

Then, event handlers could send metrics about how many compilations are happening to observability platforms like Datadog.

If you agree that adding such functionality to exla would fit in the library, then I can open a pull request, and we can discuss lower-level details like event names in there.

**Comment by josevalim** [comment]
Yes, a PR is definitely welcome!

**Comment by seanmor5** [comment]
+1, this would be great!
