### ISSUE TITLE
Nx.global_default_backend with device :cuda is failing

### ISSUE THREAD

**Issue by zabirauf** [elixir-nx/nx#999]
When I run the following in the [Notebook](https://github.com/elixir-nx/bumblebee/blob/main/notebooks/stable_diffusion.livemd)  to use the CUDA based device then I get the error. I see the following directly in code comments so I'm assuming it should work. The [documentation](https://hexdocs.pm/nx/Nx.html#global_default_backend/1) is also not clear on how do I setup CUDA as my device in a livebook. Thanks

```elixir
Nx.global_default_backend({EXLA.Backend, device: :cuda})
```

```elixir
** (ArgumentError) unknown keys [:device] in [device: :cuda], the allowed keys are: [:client, :device_id]
```

**Comment by josevalim** [comment]
Great catch. It should be `client: :cuda`. But in theory you don't have to do anything besides setting the environment variable `XLA_TARGET=cuda111` or `XLA_TARGET=cuda118` depending on your CUDA version. Then it will be automatically picked. See: https://github.com/elixir-nx/xla
